CREATE TABLE [dbo].[ACE_NDC_GENERIC] (
    [PRODUCT_NDC_9] NVARCHAR (10) NOT NULL,
    [NDC_9]         NVARCHAR (10) NOT NULL,
    [CHARLEN]       TINYINT       NOT NULL,
    PRIMARY KEY CLUSTERED ([NDC_9] ASC)
);

