CREATE TABLE [dbo].[ACE_LIST_PROVIDER_SPECIALITY] (
    [SPECIALITY_CD]    NVARCHAR (20) NOT NULL,
    [SPECIALITY_DESC]  NVARCHAR (50) NOT NULL,
    [CREATE_DATE]      DATE          NOT NULL,
    [LAST_UPDATE_DATE] DATE          NOT NULL,
    PRIMARY KEY CLUSTERED ([SPECIALITY_CD] ASC)
);

