CREATE TABLE [dbo].[ACE_DIAGNOSIS_DB_TBL] (
    [DIAGNOSIS_CD]         NVARCHAR (10)   NOT NULL,
    [DIAGNOSIS_VALIDITY]   NVARCHAR (1)    NOT NULL,
    [DIAGNOSIS_SHORT_DESC] NVARCHAR (40)   NOT NULL,
    [DIAGNOSIS_LONG_DESC]  NVARCHAR (80)   NOT NULL,
    [DIAGNOSIS_FULL_DESC]  NVARCHAR (2048) NULL,
    [DIAGNOSIS_STATUS]     NVARCHAR (1)    NULL,
    [CODE_TYPE]            INT             NULL,
    [DIAGNOSIS_CODE_TYPE]  NVARCHAR (5)    NOT NULL,
    PRIMARY KEY CLUSTERED ([DIAGNOSIS_CD] ASC)
);

