CREATE TABLE [dbo].[ACE_CLIENT_MEMBER] (
    [REF_ID]           BIGINT        NOT NULL,
    [CLIENT_ID]        INT           NOT NULL,
    [MBR_ID]           NVARCHAR (20) NOT NULL,
    [FIRST_NAME]       NVARCHAR (20) NOT NULL,
    [MIDDLE_NAME]      NVARCHAR (20) NULL,
    [LAST_NAME]        NVARCHAR (20) NOT NULL,
    [NAME_SUFFIX]      NVARCHAR (20) NULL,
    [ADDRESS1]         NVARCHAR (50) NULL,
    [ADDRESS2]         NVARCHAR (50) NULL,
    [CITY]             NVARCHAR (20) NULL,
    [STATE_CD]         NVARCHAR (2)  NULL,
    [ZIP_CODE]         NVARCHAR (10) NULL,
    [COUNTY_CD]        NVARCHAR (5)  NULL,
    [DOB]              DATE          NOT NULL,
    [PCP_ID]           INT           NOT NULL,
    [LANGUAGE]         NVARCHAR (20) NULL,
    [ETHNICITY]        NVARCHAR (20) NULL,
    [GENDER]           NVARCHAR (1)  NOT NULL,
    [HP_CODE]          NVARCHAR (10) NOT NULL,
    [HP_NAME]          NVARCHAR (10) NOT NULL,
    [LOB]              NVARCHAR (10) NOT NULL,
    [ORIG_EFF_DATE]    DATE          NOT NULL,
    [TERM_DATE]        DATE          NULL,
    [ACE_ID]           BIGINT        NULL,
    [ACTIVE_ID]        SMALLINT      NOT NULL,
    [CREATE_DATE]      DATE          NOT NULL,
    [LAST_UPDATE_DATE] DATE          NOT NULL,
    [LAST_UPDATE_BY]   NCHAR (30)    NULL,
    PRIMARY KEY CLUSTERED ([REF_ID] ASC)
);

