CREATE TABLE [dbo].[ALT_MAPPING_TABLES] (
    [URN]                INT          IDENTITY (1, 1) NOT NULL,
    [SOURCE]             VARCHAR (50) NULL,
    [DESTINATION]        VARCHAR (50) NULL,
    [TYPE]               VARCHAR (50) NULL,
    [SOURCE_VALUE]       VARCHAR (50) NULL,
    [DESTINATION_VALUE]  VARCHAR (50) NULL,
    [A_LAST_UPDATE_DATE] DATETIME     DEFAULT (getdate()) NULL,
    [A_LAST_UPDATE_BY]   VARCHAR (20) DEFAULT ('') NULL,
    [A_LAST_UPDATE_FLAG] VARCHAR (1)  DEFAULT ('Y') NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

