CREATE TABLE [dbo].[LIST_HEDIS_CODE_1] (
    [VALUE_SET_NAME]    VARCHAR (50) NULL,
    [VALUE_SET_OID]     VARCHAR (50) NULL,
    [VALUE_SET_VER]     VARCHAR (50) NULL,
    [VALUE_CODE]        VARCHAR (50) NULL,
    [VALUE_CODE_NAME]   VARCHAR (50) NULL,
    [VALUE_CODE_SYSTEM] VARCHAR (50) NULL,
    [CODE_SYSTEM_OID]   VARCHAR (50) NULL,
    [CODE_SYSTEM_VER]   VARCHAR (50) NULL
);

