CREATE TABLE [dbo].[ntfExportTable] (
    [NtfExportKey]             INT          IDENTITY (1, 1) NOT NULL,
    [DataDate]                 DATE         DEFAULT (CONVERT([date],getdate())) NOT NULL,
    [CreatedDate]              DATETIME     DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                VARCHAR (50) DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]          DATETIME     DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]            VARCHAR (50) DEFAULT (suser_sname()) NOT NULL,
    [ENTITY]                   VARCHAR (50) NULL,
    [SITE]                     VARCHAR (50) NULL,
    [UID_STATE]                VARCHAR (50) NULL,
    [UID_PROVIDER]             VARCHAR (50) NULL,
    [PracticeName]             VARCHAR (50) NULL,
    [Treatment_Type]           VARCHAR (50) NULL,
    [Member_ID]                VARCHAR (50) NULL,
    [Case_ID]                  VARCHAR (50) NULL,
    [CaseType]                 VARCHAR (50) NULL,
    [ADMIT_NOTIFICATION_DATE]  VARCHAR (50) NULL,
    [ADIMSSION_DATE]           VARCHAR (50) NULL,
    [DISCHARGE_DATE]           VARCHAR (50) NULL,
    [DISCHARGE_DISPOSITION]    VARCHAR (50) NULL,
    [FOLLOW_UP_VISIT_DUE_DATE] VARCHAR (50) NULL,
    [SCHEDULED_VISIT_DATE]     VARCHAR (50) NULL,
    [PRIMARY_DIAGNOSIS]        VARCHAR (50) NULL,
    [AdmitHospital]            VARCHAR (50) NULL,
    [Client_ID]                VARCHAR (50) NULL,
    [Exported]                 VARCHAR (50) NULL,
    [ExportedDate]             VARCHAR (50) NULL,
    [Benefit_Plan]             VARCHAR (50) NULL,
    [PHoneNumber]              VARCHAR (50) NULL,
    [Carrier_Type]             VARCHAR (50) NULL,
    [Member_First_Name]        VARCHAR (50) NULL,
    [MEMBER_LAST_NAME]         VARCHAR (50) NULL,
    [MEMBER_DOB]               VARCHAR (50) NULL,
    [DataSource]               VARCHAR (50) NULL,
    [ntfEventType]             VARCHAR (50) NULL,
    [AdiLineneageKey]          VARCHAR (50) NULL
);

