CREATE TABLE [dbo].[Rick_Physician_Roster] (
    [Practice]        VARCHAR (250) NULL,
    [Address]         VARCHAR (350) NULL,
    [Address2]        VARCHAR (250) NULL,
    [City]            VARCHAR (250) NULL,
    [State]           VARCHAR (250) NULL,
    [Zip]             VARCHAR (250) NULL,
    [County]          VARCHAR (250) NULL,
    [Phone]           VARCHAR (250) NULL,
    [Fax]             VARCHAR (250) NULL,
    [First Name]      VARCHAR (250) NULL,
    [Last Name]       VARCHAR (250) NULL,
    [Full Name]       VARCHAR (250) NULL,
    [Email]           VARCHAR (250) NULL,
    [Gender]          VARCHAR (250) NULL,
    [Title]           VARCHAR (250) NULL,
    [Specialty]       VARCHAR (250) NULL,
    [SIC Code]        VARCHAR (250) NULL,
    [Employees]       VARCHAR (250) NULL,
    [Sales]           VARCHAR (250) NULL,
    [Latitude]        VARCHAR (250) NULL,
    [Longitude]       VARCHAR (250) NULL,
    [Website]         VARCHAR (250) NULL,
    [Sq Footage]      VARCHAR (250) NULL,
    [LocationAddress] VARCHAR (250) NULL,
    [Specialty 2]     VARCHAR (250) NULL,
    [Specialty 3]     VARCHAR (250) NULL,
    [Specialty 4]     VARCHAR (250) NULL,
    [Specialty 5]     VARCHAR (250) NULL,
    [NPI]             VARCHAR (250) NULL,
    [id]              VARCHAR (250) NULL
);

