CREATE TABLE [dbo].[tmp_MbrAttritionTrend] (
    [SUBSCRIBER_ID] VARCHAR (20) NOT NULL,
    [LOB_ID]        VARCHAR (20) NULL,
    [PLAN_ID]       VARCHAR (20) NULL,
    [PRODUCT_CODE]  VARCHAR (20) NULL,
    [SUBGRP_ID]     VARCHAR (20) NULL,
    [AUTO_ASSIGN]   VARCHAR (20) NULL,
    [MBR_MTH]       INT          NULL,
    [MBR_YEAR]      INT          NULL,
    [JAN17]         INT          NULL,
    [FEB17]         INT          NULL,
    [MAR17]         INT          NULL,
    [APR17]         INT          NULL,
    [MAY17]         INT          NULL,
    [JUN17]         INT          NULL,
    [JUL17]         INT          NULL,
    [AUG17]         INT          NULL,
    [SEP17]         INT          NULL,
    [OCT17]         INT          NULL,
    [NOV17]         INT          NULL,
    [DEC17]         INT          NULL,
    [JAN18]         INT          NULL,
    [FEB18]         INT          NULL,
    [MAR18]         INT          NULL,
    [APR18]         INT          NULL,
    [MAY18]         INT          NULL,
    [JUN18]         INT          NULL,
    [JUL18]         INT          NULL,
    [AUG18]         INT          NULL,
    [SEP18]         INT          NULL,
    [OCT18]         INT          NULL,
    [NOV18]         INT          NULL,
    [DEC18]         INT          NULL,
    [MM17]          INT          NULL,
    [MM18]          INT          NULL
);

