CREATE TABLE [dbo].[tmpSalesforce_Provider_Medical_License__c] (
    [Id]                                VARCHAR (50)  NULL,
    [OwnerId]                           VARCHAR (50)  NULL,
    [IsDeleted]                         VARCHAR (50)  NULL,
    [Name]                              VARCHAR (100) NULL,
    [CreatedDate]                       DATETIME      NULL,
    [CreatedById]                       VARCHAR (50)  NULL,
    [LastModifiedDate]                  DATETIME      NULL,
    [LastModifiedById]                  VARCHAR (50)  NULL,
    [SystemModstamp]                    VARCHAR (50)  NULL,
    [LastActivityDate]                  DATETIME      NULL,
    [Provider_Name__c]                  VARCHAR (100) NULL,
    [Medical_License__c]                VARCHAR (50)  NULL,
    [State__c]                          VARCHAR (50)  NULL,
    [Expiration_Date__c]                DATETIME      NULL,
    [License_Type__c]                   VARCHAR (100) NULL,
    [License_Unlimited__c]              VARCHAR (50)  NULL,
    [License_Limitation_Explanation__c] VARCHAR (200) NULL,
    [License_Status__c]                 VARCHAR (50)  NULL,
    [Start_Date__c]                     DATETIME      NULL,
    [License_Name__c]                   VARCHAR (100) NULL,
    [A_LAST_UPDATE_DATE]                DATETIME      DEFAULT (getdate()) NULL,
    [A_LAST_UPDATE_BY]                  VARCHAR (20)  DEFAULT ('PKG ImportTmp') NULL,
    [A_LAST_UPDATE_FLAG]                VARCHAR (1)   DEFAULT ('Y') NULL
);

