CREATE TABLE [dbo].[tmpWLC_Careopps] (
    [URN]                               INT           IDENTITY (1, 1) NOT NULL,
    [ProviderID]                        VARCHAR (50)  NULL,
    [ProviderName]                      VARCHAR (150) NULL,
    [MemberName]                        VARCHAR (150) NULL,
    [Subscriber]                        VARCHAR (50)  NULL,
    [DOB]                               VARCHAR (50)  NULL,
    [Phone]                             VARCHAR (50)  NULL,
    [STAR Flag]                         VARCHAR (50)  NULL,
    [Measure]                           VARCHAR (50)  NULL,
    [ComplianceStatus]                  VARCHAR (50)  NULL,
    [ComplianceDetail]                  VARCHAR (50)  NULL,
    [LastKnownServiceDate]              VARCHAR (50)  NULL,
    [ServiceStartDate]                  VARCHAR (50)  NULL,
    [ServiceEndDate]                    VARCHAR (50)  NULL,
    [ClaimsThruDate]                    VARCHAR (50)  NULL,
    [StarMeasureComplianceUpdatedThru ] VARCHAR (50)  NULL,
    [FileDate]                          VARCHAR (50)  NULL,
    [A_LAST_UPDATE_DATE]                DATETIME      NULL,
    [A_LAST_UPDATE_FLAG]                NVARCHAR (1)  NULL,
    [A_LAST_UPDATE_BY]                  NVARCHAR (16) NULL,
    [NPI]                               VARCHAR (50)  NULL,
    [NPIName]                           VARCHAR (150) NULL,
    [MedicareID]                        VARCHAR (50)  NULL,
    [P4Q]                               VARCHAR (50)  NULL,
    [Category]                          VARCHAR (150) NULL,
    [BaseValue]                         VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

