CREATE TABLE [dbo].[TR_LIST_HEDIS_CODE] (
    [VALUE_SET_NAME]    VARCHAR (100)  NULL,
    [VALUE_SET_OID]     VARCHAR (100)  NULL,
    [VALUE_SET_VER]     VARCHAR (50)   NULL,
    [VALUE_CODE_SYSTEM] VARCHAR (50)   NULL,
    [VALUE_CODE]        NVARCHAR (MAX) NULL
);

