CREATE TABLE [dbo].[UHC_IP_Admits] (
    [URN]                      INT           IDENTITY (1, 1) NOT NULL,
    [MEDICAID_ID]              VARCHAR (50)  NULL,
    [MEMBER_LAST_NAME]         VARCHAR (50)  NULL,
    [MEMBER_FIRST_NAME]        VARCHAR (50)  NULL,
    [DATE_OF_BIRTH]            DATE          NULL,
    [ADMIT_DATE]               DATETIME      NULL,
    [ADMIT_HOSPITAL]           VARCHAR (250) NULL,
    [PRIMARY_DIAGNOSIS_CODE]   VARCHAR (50)  NULL,
    [PRIMARY_DIAGNOSIS_DESC]   VARCHAR (250) NULL,
    [SECONDARY_DIAGNOSIS_CODE] VARCHAR (50)  NULL,
    [SECONDARY_DIAGNOSIS_DESC] VARCHAR (250) NULL,
    [DISCHARGE_DATE]           DATE          NULL,
    [FOLLOWUP_DUE_DATE]        DATE          NULL,
    [FOLLOWUP_COMPLETE_DATE]   DATE          NULL,
    [SEVEN_DAY_FOLLOWUP_FLAG]  VARCHAR (50)  NULL,
    [IPRO_ADMIT_RISK_SCORE]    VARCHAR (20)  NULL,
    [PLAN_CODE]                VARCHAR (20)  NULL,
    [PLAN_DESC]                VARCHAR (50)  NULL,
    [UHC_SUBSCRIBER_ID]        VARCHAR (20)  NULL,
    [UHC_UNIQUE_SYSTEM_ID]     VARCHAR (50)  NULL,
    [MEMBER_ADDRESS]           VARCHAR (50)  NULL,
    [MEMBER_CITY]              VARCHAR (50)  NULL,
    [MEMBER_STATE]             VARCHAR (50)  NULL,
    [MEMBER_COUNTY]            VARCHAR (50)  NULL,
    [MEMBER_ZIP]               VARCHAR (50)  NULL,
    [MEMBER_PHONE]             VARCHAR (50)  NULL,
    [PCP_NAME]                 VARCHAR (250) NULL,
    [PCP_ADDRESS]              VARCHAR (50)  NULL,
    [PCP_CITY]                 VARCHAR (50)  NULL,
    [PCP_STATE]                VARCHAR (50)  NULL,
    [PCP_COUNTY]               VARCHAR (50)  NULL,
    [PCP_ZIP]                  VARCHAR (50)  NULL,
    [PCP_PRACTICE_TIN]         VARCHAR (50)  NULL,
    [PCP_PRACTICE_NAME]        VARCHAR (250) NULL,
    [FILE_GENERATION_DATE]     DATE          NULL,
    [A_LAST_UPDATE_DATE]       DATE          DEFAULT (getdate()) NULL,
    [A_LAST_UPDATE_BY]         VARCHAR (255) DEFAULT ('PKG Import') NULL,
    [A_LAST_UPDATE_FLAG]       VARCHAR (1)   DEFAULT ('Y') NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

