CREATE TABLE [dbo].[UHC_Pharmacy] (
    [URN]                           INT           IDENTITY (1, 1) NOT NULL,
    [MEDICAID_ID]                   VARCHAR (20)  NULL,
    [MEMBER_LAST_NAME]              VARCHAR (50)  NULL,
    [MEMBER_FIRST_NAME]             VARCHAR (50)  NULL,
    [DATE_OF_BIRTH]                 DATE          NULL,
    [MEDICATION_NAME]               VARCHAR (100) NULL,
    [DAYS_SUPPLY]                   VARCHAR (20)  NULL,
    [PRESCRIBE_DATE]                VARCHAR (20)  NULL,
    [PRESCRIPTION_NUMBER]           VARCHAR (20)  NULL,
    [PRESCRIBING_PROVIDER]          VARCHAR (50)  NULL,
    [PRESCRIBING_PROVIDER_PRACTICE] VARCHAR (100) NULL,
    [PRESCRIBING_PROVIDER_PHONE]    VARCHAR (20)  NULL,
    [FILL_DATE]                     DATE          NULL,
    [FILL_PHARMACY]                 VARCHAR (100) NULL,
    [IPRO_ADMIT_RISK_SCORE]         VARCHAR (20)  NULL,
    [PLAN_CODE]                     VARCHAR (20)  NULL,
    [PLAN_DESC]                     VARCHAR (100) NULL,
    [UHC_SUBSCRIBER_ID]             VARCHAR (20)  NULL,
    [UHC_UNIQUE_SYSTEM_ID]          VARCHAR (20)  NULL,
    [MEMBER_ADDRESS]                VARCHAR (100) NULL,
    [MEMBER_CITY]                   VARCHAR (50)  NULL,
    [MEMBER_STATE]                  VARCHAR (50)  NULL,
    [MEMBER_COUNTY]                 VARCHAR (50)  NULL,
    [MEMBER_ZIP]                    VARCHAR (20)  NULL,
    [MEMBER_PHONE]                  VARCHAR (20)  NULL,
    [PCP_NAME]                      VARCHAR (150) NULL,
    [PCP_ADDRESS]                   VARCHAR (50)  NULL,
    [PCP_CITY]                      VARCHAR (50)  NULL,
    [PCP_STATE]                     VARCHAR (50)  NULL,
    [PCP_COUNTY]                    VARCHAR (50)  NULL,
    [PCP_ZIP]                       VARCHAR (20)  NULL,
    [PCP_PRACTICE_TIN]              VARCHAR (20)  NULL,
    [PCP_PRACTICE_NAME]             VARCHAR (150) NULL,
    [FILE_GENERATION_DATE]          DATE          NULL,
    [A_LAST_UPDATE_DATE]            DATETIME      DEFAULT (getdate()) NULL,
    [A_LAST_UPDATE_BY]              VARCHAR (50)  NULL,
    [A_LAST_UPDATE_FLAG]            VARCHAR (1)   DEFAULT ('Y') NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

