CREATE TABLE [dbo].[UHC_Eligibility] (
    [COMPANY_CODE]          VARCHAR (50) NULL,
    [LINE_OF_BUSINESS_DESC] VARCHAR (50) NULL,
    [MEDICAID_NO]           VARCHAR (50) NULL,
    [MEDICARE_NO]           VARCHAR (50) NULL,
    [SUBSCRIBER_ID]         VARCHAR (50) NULL,
    [MEMB_FIRST_NAME]       VARCHAR (50) NULL,
    [MEMB_MIDDLE_INITIAL]   VARCHAR (50) NULL,
    [MEMB_LAST_NAME]        VARCHAR (50) NULL,
    [GENDER]                VARCHAR (50) NULL,
    [DOB]                   VARCHAR (50) NULL,
    [MEMB_ADDRESS_LINE_1]   VARCHAR (50) NULL,
    [MEMB_ADDRESS_LINE_2]   VARCHAR (50) NULL,
    [MEMB_CITY]             VARCHAR (50) NULL,
    [MEMB_STATE]            VARCHAR (50) NULL,
    [MEMB_ZIP]              VARCHAR (50) NULL,
    [PROVIDER_ID]           VARCHAR (50) NULL,
    [NATIONAL_PROVIDER_ID]  VARCHAR (50) NULL,
    [MPIN]                  VARCHAR (50) NULL,
    [PROV_FULL_NAME ]       VARCHAR (50) NULL
);

