CREATE TABLE [dbo].[z_tmpUHCMidTerm] (
    [MTH]                            INT          NULL,
    [MEMBER_ID]                      VARCHAR (20) NULL,
    [MEMBER_ORG_EFF_DATE]            DATETIME     NULL,
    [MEMBER_CONT_EFF_DATE]           DATETIME     NULL,
    [MEMBER_CUR_EFF_DATE]            DATETIME     NULL,
    [MEMBER_CUR_TERM_DATE]           DATETIME     NULL,
    [PCP_NPI]                        VARCHAR (20) NULL,
    [PCP_ZIP_C]                      VARCHAR (20) NULL,
    [PCP_EFFECTIVE_DATE]             DATETIME     NULL,
    [PCP_TERM_DATE]                  DATETIME     NULL,
    [PCP_PRACTICE_TIN]               VARCHAR (20) NULL,
    [PCP_GROUP_ID]                   VARCHAR (20) NULL,
    [PCP_PRACTICE_NAME]              VARCHAR (50) NULL,
    [AUTO_ASSIGN]                    VARCHAR (20) NULL,
    [MEMBER_STATUS]                  VARCHAR (20) NULL,
    [MEMBER_TERM_DATE]               DATETIME     NULL,
    [IPRO_ADMIT_RISK_SCORE]          FLOAT (53)   NULL,
    [TOTAL_COSTS_LAST_12_MOS]        FLOAT (53)   NULL,
    [COUNT_OPEN_CARE_OPPS]           FLOAT (53)   NULL,
    [INP_COSTS_LAST_12_MOS]          FLOAT (53)   NULL,
    [ER_COSTS_LAST_12_MOS]           FLOAT (53)   NULL,
    [OUTP_COSTS_LAST_12_MOS]         FLOAT (53)   NULL,
    [PHARMACY_COSTS_LAST_12_MOS]     FLOAT (53)   NULL,
    [PRIMARY_CARE_COSTS_LAST_12_MOS] FLOAT (53)   NULL,
    [BEHAVIORAL_COSTS_LAST_12_MOS]   FLOAT (53)   NULL,
    [OTHER_OFFICE_COSTS_LAST_12_MOS] FLOAT (53)   NULL,
    [INP_ADMITS_LAST_12_MOS]         FLOAT (53)   NULL,
    [MEMBER_MONTH_COUNT]             FLOAT (53)   NULL,
    [ACE_MemberByPCP_URN]            VARCHAR (20) NULL,
    [ACE_Membership_URN]             VARCHAR (20) NULL
);

