CREATE TABLE [dbo].[zz_ALT_Medical_Claims] (
    [Member_ID]                     VARCHAR (100)   NULL,
    [Alternate_ID]                  VARCHAR (100)   NULL,
    [Claim_Number]                  VARCHAR (100)   NULL,
    [Line_Number]                   VARCHAR (5)     NULL,
    [Place_of_Service]              VARCHAR (100)   NULL,
    [Service_Date]                  DATETIME        NULL,
    [Date_of_Service_From_Date]     DATETIME        NULL,
    [Date_of_Service_To_Date]       DATETIME        NULL,
    [Patient_Name]                  VARCHAR (100)   NULL,
    [Patient_Birth_Date]            DATETIME        NULL,
    [Patient_Gender]                VARCHAR (20)    NULL,
    [LOB]                           VARCHAR (100)   NULL,
    [Plan_Name]                     VARCHAR (100)   NULL,
    [Provider_ID]                   VARCHAR (100)   NULL,
    [Provider_Name]                 VARCHAR (100)   NULL,
    [Provider_Address]              VARCHAR (100)   NULL,
    [Provider_City]                 VARCHAR (100)   NULL,
    [Provider_State]                VARCHAR (100)   NULL,
    [Provider_Zip]                  VARCHAR (20)    NULL,
    [Diagnosis_Codes_1]             VARCHAR (10)    NULL,
    [Diagnosis_Codes_2]             VARCHAR (10)    NULL,
    [Diagnosis_Codes_1_15]          VARCHAR (10)    NULL,
    [Diagnosis_Code_Version]        VARCHAR (10)    NULL,
    [CPT_HCPCS_Codes_1]             VARCHAR (10)    NULL,
    [CPT_HCPCS_Codes_2]             VARCHAR (10)    NULL,
    [CPT_HCPCS_Codes_1_20]          VARCHAR (10)    NULL,
    [CPT_Modifiers_1]               VARCHAR (10)    NULL,
    [CPT_Modifiers_2]               VARCHAR (10)    NULL,
    [CPT_Modifiers_n]               VARCHAR (10)    NULL,
    [Revenue_Codes]                 VARCHAR (10)    NULL,
    [Type_Of_Bill_Code]             VARCHAR (3)     NULL,
    [Admission_Type]                VARCHAR (1)     NULL,
    [Claim_Status]                  VARCHAR (10)    NULL,
    [Total_Charge]                  DECIMAL (18, 2) NULL,
    [Amount_Paid]                   DECIMAL (18, 2) NULL,
    [Balance_Due]                   DECIMAL (18, 2) NULL,
    [Claim_Addtional_Information_1] VARCHAR (100)   NULL,
    [Claim_Addtional_Information_2] VARCHAR (100)   NULL,
    [Claim_Addtional_Information_n] VARCHAR (100)   NULL,
    [LAST_UPDATE_BY]                VARCHAR (50)    NULL,
    [LAST_UPDATE_DATE]              DATETIME        NULL
);

