CREATE TABLE [dbo].[zz_ALT_Authorization] (
    [Authorizationid]              VARCHAR (50)  NULL,
    [Auth_Line_Number]             VARCHAR (4)   NULL,
    [Place_Of_Service]             VARCHAR (4)   NULL,
    [Auth_Type]                    VARCHAR (50)  NULL,
    [Auth_Priority]                VARCHAR (15)  NULL,
    [Auth_Status]                  VARCHAR (50)  NULL,
    [MemberID]                     VARCHAR (100) NULL,
    [LOB_Program_Type]             VARCHAR (50)  NULL,
    [Program_Name]                 VARCHAR (50)  NULL,
    [Notification_Date]            VARCHAR (8)   NULL,
    [Caller_Name]                  VARCHAR (100) NULL,
    [Caller_Phone]                 VARCHAR (20)  NULL,
    [effdate]                      DATETIME      NULL,
    [termdate]                     DATETIME      NULL,
    [refertoprovid]                VARCHAR (15)  NULL,
    [referfromprovid]              VARCHAR (15)  NULL,
    [Facility_ID]                  VARCHAR (15)  NULL,
    [Diagnosis_Codes_1]            VARCHAR (10)  NULL,
    [Diagnosis_Codes_2]            VARCHAR (10)  NULL,
    [Diagnosis_Codes_n]            VARCHAR (10)  NULL,
    [Diagnosis_Code_Version]       VARCHAR (10)  NULL,
    [CPT_HCPCS_Codes_1]            VARCHAR (10)  NULL,
    [CPT_HCPCS_Codes_2]            VARCHAR (10)  NULL,
    [CPT_HCPCS_Codes_n]            VARCHAR (10)  NULL,
    [Claim_Type]                   VARCHAR (4)   NULL,
    [Discharge_Diagnosis]          VARCHAR (8)   NULL,
    [Actual_Discharge_Date]        VARCHAR (8)   NULL,
    [Requested_Days_Units]         VARCHAR (8)   NULL,
    [Approved_Days_Units]          VARCHAR (8)   NULL,
    [Treatment_Type]               VARCHAR (15)  NULL,
    [Discharge_Status_Code]        VARCHAR (4)   NULL,
    [Admission_Type]               VARCHAR (4)   NULL,
    [Decision_Status]              VARCHAR (50)  NULL,
    [Decision_Reason_Code]         VARCHAR (50)  NULL,
    [Closed_Reason]                VARCHAR (50)  NULL,
    [Closed_Date]                  DATETIME      NULL,
    [Auth_Reviewer]                VARCHAR (50)  NULL,
    [Auth_Notes_1]                 VARCHAR (100) NULL,
    [Auth_Notes_2]                 VARCHAR (100) NULL,
    [Auth_Notes_n]                 VARCHAR (100) NULL,
    [Auth_Addtional_Information_1] VARCHAR (100) NULL,
    [Auth_Addtional_Information_2] VARCHAR (100) NULL,
    [Auth_Addtional_Information_n] VARCHAR (100) NULL,
    [LAST_UPDATE_BY]               VARCHAR (50)  NULL,
    [LAST_UPDATE_DATE]             DATETIME      NULL
);

