CREATE TABLE [dbo].[zz_ALT_Provider] (
    [PROVIDER_ID]                      VARCHAR (25)  NULL,
    [PROVIDER_FNAME]                   VARCHAR (100) NULL,
    [PROVIDER_MNAME]                   VARCHAR (50)  NULL,
    [PROVIDER_LNAME]                   VARCHAR (100) NULL,
    [PROVIDER_PREFIX]                  VARCHAR (25)  NULL,
    [PROVIDER_SUFFIX]                  VARCHAR (25)  NULL,
    [ADDRESS_1]                        VARCHAR (100) NULL,
    [ADDRESS_2]                        VARCHAR (100) NULL,
    [CITY]                             VARCHAR (100) NULL,
    [STATE]                            VARCHAR (50)  NULL,
    [ZIP_CODE]                         VARCHAR (20)  NULL,
    [PHONE_OFFICE]                     VARCHAR (20)  NULL,
    [DEGREE]                           VARCHAR (100) NULL,
    [ETHNICITY]                        VARCHAR (100) NULL,
    [GENDER]                           VARCHAR (1)   NULL,
    [DOB]                              DATE          NULL,
    [NPI]                              INT           NULL,
    [TIN]                              VARCHAR (50)  NULL,
    [PRIM_SPECIALTY]                   VARCHAR (100) NULL,
    [AFFILIATION_NAMES]                VARCHAR (200) NULL,
    [LANGUAGES_SPOKEN]                 VARCHAR (150) NULL,
    [EDUCATION]                        VARCHAR (150) NULL,
    [PROVIDER_ADDTIONAL_INFORMATION_1] VARCHAR (100) NULL,
    [PROVIDER_ADDTIONAL_INFORMATION_2] VARCHAR (100) NULL,
    [PROVIDER_ADDTIONAL_INFORMATION_N] VARCHAR (100) NULL,
    [ALTERNATE_ID_1]                   VARCHAR (100) NULL,
    [ALTERNATE_ID_2]                   VARCHAR (100) NULL,
    [ALTERNATE_ID_N]                   VARCHAR (100) NULL,
    [LAST_UPDATE_BY]                   VARCHAR (50)  NULL,
    [LAST_UPDATE_DATE]                 DATETIME      NULL
);

