CREATE TABLE [dbo].[zz_ALT_Pharmacy_Claims] (
    [Member_ID]                  VARCHAR (100)   NULL,
    [Alternate_ID]               VARCHAR (100)   NULL,
    [Claim_Number]               VARCHAR (100)   NULL,
    [Fill_Date]                  DATETIME        NULL,
    [Written_Date]               DATETIME        NULL,
    [Refill_Indicator]           VARCHAR (10)    NULL,
    [Refill_Number]              VARCHAR (10)    NULL,
    [Days_Supply]                INT             NULL,
    [Quantity_Supply]            DECIMAL (18, 2) NULL,
    [Rx_Number]                  VARCHAR (100)   NULL,
    [Patient_Name]               VARCHAR (200)   NULL,
    [Patient_Birth_Date]         DATETIME        NULL,
    [Patient_Gender]             VARCHAR (20)    NULL,
    [Physician_ID]               VARCHAR (100)   NULL,
    [Physician_Name]             VARCHAR (200)   NULL,
    [Physician_Address]          VARCHAR (200)   NULL,
    [Physician_City]             VARCHAR (100)   NULL,
    [Physician_State]            VARCHAR (100)   NULL,
    [Physician_Zip]              VARCHAR (20)    NULL,
    [NDC_Codes]                  VARCHAR (50)    NULL,
    [Pharmacy_ID]                VARCHAR (100)   NULL,
    [Pharmacy_Name]              VARCHAR (200)   NULL,
    [Pharmacy_Address]           VARCHAR (200)   NULL,
    [Pharmacy_City]              VARCHAR (100)   NULL,
    [Pharmacy_State]             VARCHAR (100)   NULL,
    [Pharmacy_Zip]               VARCHAR (20)    NULL,
    [Total_Charge]               DECIMAL (18, 2) NULL,
    [Amount_Paid]                DECIMAL (18, 2) NULL,
    [Balance_Due]                DECIMAL (18, 2) NULL,
    [RX_Addtional_Information_1] VARCHAR (100)   NULL,
    [RX_Addtional_Information_2] VARCHAR (100)   NULL,
    [RX_Addtional_Information_n] VARCHAR (100)   NULL,
    [LAST_UPDATE_BY]             VARCHAR (50)    NULL,
    [LAST_UPDATE_DATE]           DATETIME        NULL
);

