CREATE TABLE [ast].[fctProviderRoster_DevPrBk] (
    [fctProviderRosterSkey]  INT           IDENTITY (1, 1) NOT NULL,
    [SourceJobName]          VARCHAR (50)  NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [DataDate]               DATE          NOT NULL,
    [CreatedDate]            DATETIME      NOT NULL,
    [CreatedBy]              VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]        DATE          NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  NOT NULL,
    [IsActive]               BIT           NOT NULL,
    [RowEffectiveDate]       DATE          NOT NULL,
    [RowExpirationDate]      DATE          NOT NULL,
    [NPI]                    CHAR (20)     NULL,
    [TIN]                    VARCHAR (10)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [Degree]                 VARCHAR (100) NULL,
    [PrimarySpeciality]      VARCHAR (100) NULL,
    [Sub_Speciality]         VARCHAR (100) NULL,
    [GroupName]              VARCHAR (100) NULL,
    [PrimaryAddress]         VARCHAR (100) NULL,
    [PrimaryCity]            VARCHAR (35)  NULL,
    [PrimaryState]           VARCHAR (25)  NULL,
    [PrimaryZipcode]         VARCHAR (20)  NULL,
    [PrimaryPOD]             VARCHAR (50)  NULL,
    [PrimaryQuadrant]        VARCHAR (50)  NULL,
    [PrimaryAddressPhoneNum] VARCHAR (35)  NULL,
    [BillingAddress]         VARCHAR (100) NULL,
    [BillingCity]            VARCHAR (35)  NULL,
    [BillingState]           VARCHAR (25)  NULL,
    [BillingZipcode]         VARCHAR (20)  NULL,
    [BillingPOD]             VARCHAR (50)  NULL,
    [BillingAddressPhoneNum] VARCHAR (35)  NULL,
    [Comments]               VARCHAR (100) NULL,
    [AccountType]            VARCHAR (50)  NULL,
    [NetworkContact]         VARCHAR (50)  NULL,
    [Chapter]                VARCHAR (50)  NULL,
    [ProviderType]           VARCHAR (20)  NULL,
    [AceProviderID]          VARCHAR (15)  NULL,
    [AceAccountID]           VARCHAR (15)  NULL,
    [Ethnicity]              VARCHAR (50)  NULL,
    [LanguagesSpoken]        VARCHAR (50)  NULL,
    [Provider_DOB]           DATE          NULL,
    [Provider_Gender]        CHAR (1)      NULL,
    [PrimaryCounty]          VARCHAR (25)  NULL,
    [ClientProviderID]       VARCHAR (500) NULL,
    [TinClientKey]           INT           NULL,
    [TinLob]                 VARCHAR (50)  NULL,
    [TinHealthPlan]          VARCHAR (100) NULL,
    [TinHpEffDate]           DATE          NULL,
    [TinHpExpDate]           DATE          NULL,
    [PrvdrTin]               VARCHAR (12)  NULL,
    [PrvdrClientKey]         INT           NULL,
    [PrvdrLOB]               VARCHAR (50)  NULL,
    [PrvdrHealthPlan]        VARCHAR (100) NULL,
    [PrvdrHpEffDate]         DATE          NULL,
    [PrvdrHpExpDate]         DATE          NULL
);

