CREATE TABLE [ast].[fctProviderRoster_DevPR] (
    [fctProviderRosterSkey]  INT           IDENTITY (1, 1) NOT NULL,
    [SourceJobName]          VARCHAR (50)  NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [DataDate]               DATE          NOT NULL,
    [CreatedDate]            DATETIME      CONSTRAINT [DF_astFctProvRoster_DevPR_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              VARCHAR (50)  CONSTRAINT [DF_astFctProvRoster_DevPR_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]        DATE          CONSTRAINT [DF_astFctProvRoster_DevPR_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  CONSTRAINT [DF_astFctProvRoster_DevPR_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [IsActive]               BIT           CONSTRAINT [DF_astFctProvRoster_DevPR_IsActive] DEFAULT ((1)) NOT NULL,
    [RowEffectiveDate]       DATE          DEFAULT (CONVERT([date],getdate())) NOT NULL,
    [RowExpirationDate]      DATE          DEFAULT (CONVERT([date],'12/31/2099')) NOT NULL,
    [NPI]                    CHAR (20)     NULL,
    [TIN]                    VARCHAR (10)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [Degree]                 VARCHAR (100) NULL,
    [PrimarySpeciality]      VARCHAR (100) NULL,
    [Sub_Speciality]         VARCHAR (100) NULL,
    [GroupName]              VARCHAR (100) NULL,
    [PrimaryAddress]         VARCHAR (100) NULL,
    [PrimaryCity]            VARCHAR (35)  NULL,
    [PrimaryState]           VARCHAR (25)  NULL,
    [PrimaryZipcode]         VARCHAR (20)  NULL,
    [PrimaryPOD]             VARCHAR (50)  NULL,
    [PrimaryQuadrant]        VARCHAR (50)  NULL,
    [PrimaryAddressPhoneNum] VARCHAR (35)  NULL,
    [BillingAddress]         VARCHAR (100) NULL,
    [BillingCity]            VARCHAR (35)  NULL,
    [BillingState]           VARCHAR (25)  NULL,
    [BillingZipcode]         VARCHAR (20)  NULL,
    [BillingPOD]             VARCHAR (50)  NULL,
    [BillingAddressPhoneNum] VARCHAR (35)  NULL,
    [Comments]               VARCHAR (100) NULL,
    [AccountType]            VARCHAR (50)  NULL,
    [NetworkContact]         VARCHAR (50)  NULL,
    [Chapter]                VARCHAR (50)  NULL,
    [ProviderType]           VARCHAR (20)  NULL,
    [AceProviderID]          VARCHAR (15)  NULL,
    [AceAccountID]           VARCHAR (15)  NULL,
    [Ethnicity]              VARCHAR (50)  NULL,
    [LanguagesSpoken]        VARCHAR (50)  NULL,
    [Provider_DOB]           DATE          NULL,
    [Provider_Gender]        CHAR (1)      NULL,
    [PrimaryCounty]          VARCHAR (25)  NULL,
    [ClientProviderID]       VARCHAR (500) NULL,
    [TinClientKey]           INT           DEFAULT ((0)) NULL,
    [TinLob]                 VARCHAR (50)  DEFAULT ('Unknown') NULL,
    [TinHealthPlan]          VARCHAR (100) DEFAULT ('Unknown') NULL,
    [TinHpEffDate]           DATE          DEFAULT ('01/01/1900') NULL,
    [TinHpExpDate]           DATE          DEFAULT ('01/01/1900') NULL,
    [PrvdrTin]               VARCHAR (12)  DEFAULT ('00000000') NULL,
    [PrvdrClientKey]         INT           DEFAULT ((0)) NULL,
    [PrvdrLOB]               VARCHAR (50)  DEFAULT ('Unknown') NULL,
    [PrvdrHealthPlan]        VARCHAR (100) DEFAULT ('Unknown') NULL,
    [PrvdrHpEffDate]         DATE          DEFAULT ('01/01/1900') NULL,
    [PrvdrHpExpDate]         DATE          DEFAULT ('01/01/1900') NULL,
    PRIMARY KEY CLUSTERED ([fctProviderRosterSkey] ASC)
);

