CREATE TABLE [ast].[fctProviderRoster] (
    [fctProviderRosterSkey]  INT           IDENTITY (1, 1) NOT NULL,
    [SourceJobName]          VARCHAR (50)  NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [DataDate]               DATE          NOT NULL,
    [CreatedDate]            DATETIME      CONSTRAINT [DF_astFctProvRoster_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              VARCHAR (50)  CONSTRAINT [DF_astFctProvRoster_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]        DATE          CONSTRAINT [DF_astFctProvRoster_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  CONSTRAINT [DF_astFctProvRoster_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [IsActive]               BIT           CONSTRAINT [DF_astFctProvRoster_IsActive] DEFAULT ((1)) NOT NULL,
    [RowEffectiveDate]       DATE          DEFAULT (CONVERT([date],getdate())) NOT NULL,
    [RowExpirationDate]      DATE          DEFAULT (CONVERT([date],'12/31/2099')) NOT NULL,
    [ClientKey]              INT           NOT NULL,
    [LOB]                    VARCHAR (50)  NULL,
    [transLOB]               VARCHAR (50)  NULL,
    [ClientProviderID]       VARCHAR (50)  NULL,
    [transClientProviderID]  VARCHAR (50)  NULL,
    [NPI]                    VARCHAR (10)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [transLastName]          VARCHAR (50)  NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [transFirstName]         VARCHAR (50)  NULL,
    [Degree]                 VARCHAR (100) NULL,
    [transDegree]            VARCHAR (100) NULL,
    [TIN]                    VARCHAR (10)  NULL,
    [PrimarySpeciality]      VARCHAR (100) NULL,
    [transPrimarySpeciality] VARCHAR (100) NULL,
    [Sub_Speciality]         VARCHAR (100) NULL,
    [transSub_Speciality]    VARCHAR (100) NULL,
    [GroupName]              VARCHAR (100) NULL,
    [transGroupName]         VARCHAR (100) NULL,
    [EffectiveDate]          DATE          NULL,
    [ExpirationDate]         DATE          NULL,
    [PrimaryAddress]         VARCHAR (100) NULL,
    [transPrimaryAddress]    VARCHAR (100) NULL,
    [PrimaryCity]            VARCHAR (35)  NULL,
    [transPrimaryCity]       VARCHAR (35)  NULL,
    [PrimaryState]           VARCHAR (25)  NULL,
    [transPrimaryState]      VARCHAR (25)  NULL,
    [PrimaryZipcode]         VARCHAR (20)  NULL,
    [PrimaryPOD]             VARCHAR (50)  NULL,
    [transPrimaryPOD]        VARCHAR (50)  NULL,
    [PrimaryQuadrant]        VARCHAR (50)  NULL,
    [transPrimaryQuadrant]   VARCHAR (50)  NULL,
    [PrimaryAddressPhoneNum] VARCHAR (35)  NULL,
    [BillingAddress]         VARCHAR (100) NULL,
    [transBillingAddress]    VARCHAR (100) NULL,
    [BillingCity]            VARCHAR (35)  NULL,
    [transBillingCity]       VARCHAR (35)  NULL,
    [BillingState]           VARCHAR (25)  NULL,
    [transBillingState]      VARCHAR (25)  NULL,
    [BillingZipcode]         VARCHAR (20)  NULL,
    [BillingPOD]             VARCHAR (50)  NULL,
    [transBillingPOD]        VARCHAR (50)  NULL,
    [BillingAddressPhoneNum] VARCHAR (35)  NULL,
    [Comments]               VARCHAR (100) NULL,
    [transComments]          VARCHAR (100) NULL,
    [HealthPlan]             VARCHAR (50)  NULL,
    [transHealthPlan]        VARCHAR (50)  NULL,
    [AccountType]            VARCHAR (50)  NULL,
    [NetworkContact]         VARCHAR (50)  NULL,
    [transNetworkContact]    VARCHAR (50)  NULL,
    [Chapter]                VARCHAR (50)  NULL,
    [transChapter]           VARCHAR (50)  NULL,
    [ProviderType]           VARCHAR (20)  NULL,
    [AceProviderID]          VARCHAR (15)  NULL,
    [AceAccountID]           VARCHAR (15)  NULL,
    [Ethnicity]              VARCHAR (50)  NULL,
    [LanguagesSpoken]        VARCHAR (50)  NULL,
    [Provider_DOB]           DATE          NULL,
    [Provider_Gender]        CHAR (1)      NULL,
    [TransAceProviderID]     VARCHAR (15)  NULL,
    [TransAceAccountID]      VARCHAR (15)  NULL,
    [TransEthnicity]         VARCHAR (50)  NULL,
    [TransLanguagesSpoken]   VARCHAR (50)  NULL,
    [PrimaryCounty]          VARCHAR (25)  NULL,
    [ProviderLOB]            VARCHAR (50)  NULL,
    [ProviderHealthPlan]     VARCHAR (50)  NULL,
    [ProviderHP_EffDate]     DATETIME      NULL,
    [ProviderHP_ExpDate]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([fctProviderRosterSkey] ASC)
);

