CREATE TABLE [ast].[MbrAetMbrByPcp] (
    [URN]               INT           IDENTITY (1, 1) NOT NULL,
    [Month]             VARCHAR (10)  NULL,
    [PbgNumber]         VARCHAR (20)  NULL,
    [PbgName]           VARCHAR (50)  NULL,
    [SubgroupNumber]    VARCHAR (20)  NULL,
    [SubgroupName]      VARCHAR (50)  NULL,
    [TIN]               VARCHAR (15)  NULL,
    [TINName]           VARCHAR (100) NULL,
    [PhysicianNumber]   VARCHAR (20)  NULL,
    [NPI]               VARCHAR (15)  NULL,
    [PhysicianName]     VARCHAR (100) NULL,
    [PhysicianAddress]  VARCHAR (75)  NULL,
    [MSCIndicator]      VARCHAR (50)  NULL,
    [SpecialtyCategory] VARCHAR (50)  NULL,
    [Legacy]            VARCHAR (50)  NULL,
    [SrcMemberID]       VARCHAR (20)  NULL,
    [MemberID]          VARCHAR (50)  NULL,
    [LastName]          VARCHAR (50)  NULL,
    [FirstName]         VARCHAR (50)  NULL,
    [DOB]               VARCHAR (20)  NULL,
    [Age]               VARCHAR (3)   NULL,
    [Gender]            VARCHAR (5)   NULL,
    [Address]           VARCHAR (150) NULL,
    [PhoneNumber]       VARCHAR (35)  NULL,
    [HICN]              VARCHAR (20)  NULL,
    [EffectiveDate]     VARCHAR (20)  NULL,
    [TermDate]          VARCHAR (20)  NULL,
    [Product]           VARCHAR (50)  NULL,
    [GroupIndicator]    VARCHAR (50)  NULL,
    [PartDInd]          VARCHAR (5)   NULL,
    [RaFactorType]      VARCHAR (20)  NULL,
    [RiskScore]         VARCHAR (10)  NULL,
    [PulseScore]        VARCHAR (20)  NULL,
    [CmInd]             VARCHAR (50)  NULL,
    [SrcFileName]       VARCHAR (100) NOT NULL,
    [InQuarantine]      TINYINT       CONSTRAINT [DF_astAetMbrByPcp_InQuarantine] DEFAULT ((0)) NOT NULL,
    [LoadDate]          DATE          NOT NULL,
    [DataDate]          DATE          NOT NULL,
    [CreateDate]        DATETIME2 (7) CONSTRAINT [Df_astAetMbrByPcp_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]          VARCHAR (50)  CONSTRAINT [Df_astAetMbrByPcp_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    CONSTRAINT [PK_astMbrAetMbrByPcp_URN] PRIMARY KEY CLUSTERED ([URN] ASC),
    CONSTRAINT [Ck_astAetMbrByPcp_InQuarantine] CHECK ([InQuarantine]=(1) OR [InQuarantine]=(0))
);

