CREATE TABLE [ast].[MbrUhcMbrByPcp] (
    [mbrUhcMbrByPcpKey]    INT           IDENTITY (1, 1) NOT NULL,
    [MEMBER_FIRST_NAME]    VARCHAR (255) NULL,
    [MEMBER_MI]            VARCHAR (255) NULL,
    [MEMBER_LAST_NAME]     VARCHAR (255) NULL,
    [UHC_SUBSCRIBER_ID]    VARCHAR (255) NOT NULL,
    [CLASS]                VARCHAR (255) NULL,
    [PLAN_ID]              VARCHAR (255) NULL,
    [PRODUCT_CODE]         VARCHAR (255) NULL,
    [SUBGRP_ID]            VARCHAR (255) NULL,
    [SUBGRP_NAME]          VARCHAR (255) NULL,
    [MEDICARE_ID]          VARCHAR (255) NULL,
    [MEDICAID_ID]          VARCHAR (255) NULL,
    [AGE]                  VARCHAR (255) NULL,
    [DATE_OF_BIRTH]        VARCHAR (255) NULL,
    [GENDER]               VARCHAR (255) NULL,
    [RELATIONSHIP_CODE]    VARCHAR (255) NULL,
    [LANG_CODE]            VARCHAR (255) NULL,
    [MEMBER_HOME_ADDRESS]  VARCHAR (255) NULL,
    [MEMBER_HOME_ADDRESS2] VARCHAR (255) NULL,
    [MEMBER_HOME_CITY]     VARCHAR (255) NULL,
    [MEMBER_HOME_STATE]    VARCHAR (255) NULL,
    [MEMBER_HOME_ZIP]      VARCHAR (255) NULL,
    [MEMBER_HOME_PHONE]    VARCHAR (255) NULL,
    [MEMBER_MAIL_ADDRESS]  VARCHAR (255) NULL,
    [MEMBER_MAIL_ADDRESS2] VARCHAR (255) NULL,
    [MEMBER_MAIL_CITY]     VARCHAR (255) NULL,
    [MEMBER_MAIL_STATE]    VARCHAR (255) NULL,
    [MEMBER_MAIL_ZIP]      VARCHAR (255) NULL,
    [MEMBER_MAIL_PHONE]    VARCHAR (255) NULL,
    [MEMBER_COUNTY_CODE]   VARCHAR (255) NULL,
    [MEMBER_COUNTY]        VARCHAR (255) NULL,
    [MEMBER_BUS_PHONE]     VARCHAR (255) NULL,
    [DUAL_COV_FLAG]        VARCHAR (255) NULL,
    [MEMBER_ORG_EFF_DATE]  VARCHAR (255) NULL,
    [MEMBER_CONT_EFF_DATE] VARCHAR (255) NULL,
    [MEMBER_CUR_EFF_DATE]  VARCHAR (255) NULL,
    [MEMBER_CUR_TERM_DATE] VARCHAR (255) NULL,
    [CLASS_PLAN_ID]        VARCHAR (255) NULL,
    [RESP_LAST_NAME]       VARCHAR (255) NULL,
    [RESP_FIRST_NAME]      VARCHAR (255) NULL,
    [RESP_ADDRESS]         VARCHAR (255) NULL,
    [RESP_ADDRESS2]        VARCHAR (255) NULL,
    [RESP_CITY]            VARCHAR (255) NULL,
    [RESP_STATE]           VARCHAR (255) NULL,
    [RESP_ZIP]             VARCHAR (255) NULL,
    [RESP_PHONE]           VARCHAR (255) NULL,
    [BROKER_ID]            VARCHAR (255) NULL,
    [PCP_UHC_ID]           VARCHAR (255) NULL,
    [PCP_FIRST_NAME]       VARCHAR (255) NULL,
    [PCP_LAST_NAME]        VARCHAR (255) NULL,
    [PCP_MPIN]             VARCHAR (255) NULL,
    [PCP_NPI]              VARCHAR (255) NULL,
    [PCP_PROV_TYPE_ID]     VARCHAR (255) NULL,
    [PCP_PROV_TYPE]        VARCHAR (255) NULL,
    [PCP_INDICATOR]        VARCHAR (255) NULL,
    [CMG]                  VARCHAR (255) NULL,
    [PCP_PHONE]            VARCHAR (255) NULL,
    [PCP_FAX]              VARCHAR (255) NULL,
    [PCP_ADDRESS]          VARCHAR (255) NULL,
    [PCP_ADDRESS2]         VARCHAR (255) NULL,
    [PCP_CITY]             VARCHAR (255) NULL,
    [PCP_STATE]            VARCHAR (255) NULL,
    [PCP_ZIP]              VARCHAR (255) NULL,
    [PCP_COUNTY]           VARCHAR (255) NULL,
    [PCP_EFFECTIVE_DATE]   VARCHAR (255) NULL,
    [PCP_TERM_DATE]        VARCHAR (255) NULL,
    [PCP_PRACTICE_TIN]     VARCHAR (255) NULL,
    [PCP_GROUP_ID]         VARCHAR (255) NULL,
    [PCP_PRACTICE_NAME]    VARCHAR (255) NULL,
    [IND_PRACT_ID]         VARCHAR (255) NULL,
    [IND_PRACT_NAME]       VARCHAR (255) NULL,
    [RECERT_DATE]          VARCHAR (255) NULL,
    [ETHNICITY]            VARCHAR (255) NULL,
    [ETHNICITY_DESC]       VARCHAR (255) NULL,
    [AUTO_ASSIGN]          VARCHAR (255) NULL,
    [ASAP_ID]              VARCHAR (255) NULL,
    [FEW_ID]               VARCHAR (255) NULL,
    [LST_HRA_DATE]         VARCHAR (255) NULL,
    [NXT_HRA_DATE]         VARCHAR (255) NULL,
    [HRA_ID]               VARCHAR (255) NULL,
    [MEMBER_EMAIL]         VARCHAR (255) NULL,
    [SrcFileName]          VARCHAR (100) NOT NULL,
    [LoadType]             VARCHAR (1)   NOT NULL,
    [InQuarantine]         TINYINT       CONSTRAINT [DF_astMbrUHCMbrByPcp_InQuarantine] DEFAULT ((0)) NOT NULL,
    [LoadDate]             DATE          NOT NULL,
    [DataDate]             DATE          NOT NULL,
    [CreateDate]           DATETIME2 (7) CONSTRAINT [Df_astMbrUHCMbrByPcp_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]             VARCHAR (50)  CONSTRAINT [Df_astMbrUHCMbrByPcp_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]      DATETIME2 (7) CONSTRAINT [DF_astMbrUHCMbrByPcp_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]        VARCHAR (50)  CONSTRAINT [DF_astMbrUHCMbrByPcp_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    CONSTRAINT [PK_astMbrUhcMbrByPcp_mbrUhcMbrByPcpKey] PRIMARY KEY CLUSTERED ([mbrUhcMbrByPcpKey] ASC),
    CONSTRAINT [Ck_astMbrUHCMbrByPcp_InQuarantine] CHECK ([InQuarantine]=(1) OR [InQuarantine]=(0)),
    CONSTRAINT [CK_astMbrUhcMbrByPcp_LoadType] CHECK ([LoadType]='O' OR [LoadType]='S' OR [LoadType]='P')
);

