CREATE TABLE [ast].[MbrUhcMbrHighRisk] (
    [MbrUhcMbrHighRisk_URN] INT           IDENTITY (1, 1) NOT NULL,
    [MEMBER_FIRST_NAME]     VARCHAR (255) NULL,
    [MEMBER_MI]             VARCHAR (255) NULL,
    [MEMBER_LAST_NAME]      VARCHAR (255) NULL,
    [UHC_SUBSCRIBER_ID]     VARCHAR (255) NULL,
    [CLASS]                 VARCHAR (255) NULL,
    [PLAN_ID]               VARCHAR (255) NULL,
    [PRODUCT_CODE]          VARCHAR (255) NULL,
    [SUBGRP_ID]             VARCHAR (255) NULL,
    [SUBGRP_NAME]           VARCHAR (255) NULL,
    [MEDICARE_ID]           VARCHAR (255) NULL,
    [MEDICAID_ID]           VARCHAR (255) NULL,
    [EffectiveDate]         DATE          NULL,
    [TerminationDate]       DATE          NULL,
    [AGE]                   VARCHAR (255) NULL,
    [DATE_OF_BIRTH]         VARCHAR (255) NULL,
    [GENDER]                VARCHAR (255) NULL,
    [RELATIONSHIP_CODE]     VARCHAR (255) NULL,
    [LANG_CODE]             VARCHAR (255) NULL,
    [MEMBER_HOME_ADDRESS]   VARCHAR (255) NULL,
    [MEMBER_HOME_ADDRESS2]  VARCHAR (255) NULL,
    [MEMBER_HOME_CITY]      VARCHAR (255) NULL,
    [MEMBER_HOME_STATE]     VARCHAR (255) NULL,
    [MEMBER_HOME_ZIP]       VARCHAR (255) NULL,
    [MEMBER_HOME_PHONE]     VARCHAR (255) NULL,
    [MEMBER_MAIL_ADDRESS]   VARCHAR (255) NULL,
    [MEMBER_MAIL_ADDRESS2]  VARCHAR (255) NULL,
    [MEMBER_MAIL_CITY]      VARCHAR (255) NULL,
    [MEMBER_MAIL_STATE]     VARCHAR (255) NULL,
    [MEMBER_MAIL_ZIP]       VARCHAR (255) NULL,
    [MEMBER_MAIL_PHONE]     VARCHAR (255) NULL,
    [MEMBER_COUNTY_CODE]    VARCHAR (255) NULL,
    [MEMBER_COUNTY]         VARCHAR (255) NULL,
    [MEMBER_BUS_PHONE]      VARCHAR (255) NULL,
    [DUAL_COV_FLAG]         VARCHAR (255) NULL,
    [COB_FLAG]              VARCHAR (20)  NULL,
    [MEMBER_ORG_EFF_DATE]   VARCHAR (255) NULL,
    [MEMBER_CONT_EFF_DATE]  VARCHAR (255) NULL,
    [MEMBER_CUR_EFF_DATE]   VARCHAR (255) NULL,
    [MEMBER_CUR_TERM_DATE]  VARCHAR (255) NULL,
    [CLASS_PLAN_ID]         VARCHAR (255) NULL,
    [RESP_LAST_NAME]        VARCHAR (255) NULL,
    [RESP_FIRST_NAME]       VARCHAR (255) NULL,
    [RESP_ADDRESS]          VARCHAR (255) NULL,
    [RESP_ADDRESS2]         VARCHAR (255) NULL,
    [RESP_CITY]             VARCHAR (255) NULL,
    [RESP_STATE]            VARCHAR (255) NULL,
    [RESP_ZIP]              VARCHAR (255) NULL,
    [RESP_PHONE]            VARCHAR (255) NULL,
    [BROKER_ID]             VARCHAR (255) NULL,
    [PCP_UHC_ID]            VARCHAR (255) NULL,
    [PCP_FIRST_NAME]        VARCHAR (255) NULL,
    [PCP_LAST_NAME]         VARCHAR (255) NULL,
    [PCP_MPIN]              VARCHAR (255) NULL,
    [PCP_NPI]               VARCHAR (255) NULL,
    [PCP_PROV_TYPE_ID]      VARCHAR (255) NULL,
    [PCP_PROV_TYPE]         VARCHAR (255) NULL,
    [ProvSpecCode]          VARCHAR (255) NULL,
    [ProvSpecialty]         VARCHAR (255) NULL,
    [PCP_INDICATOR]         VARCHAR (255) NULL,
    [CMG]                   VARCHAR (255) NULL,
    [PCP_PHONE]             VARCHAR (255) NULL,
    [PCP_FAX]               VARCHAR (255) NULL,
    [PCP_ADDRESS]           VARCHAR (255) NULL,
    [PCP_ADDRESS2]          VARCHAR (255) NULL,
    [PCP_CITY]              VARCHAR (255) NULL,
    [PCP_STATE]             VARCHAR (255) NULL,
    [PCP_ZIP]               VARCHAR (255) NULL,
    [PCP_COUNTY]            VARCHAR (255) NULL,
    [PCP_EFFECTIVE_DATE]    VARCHAR (255) NULL,
    [PCP_TERM_DATE]         VARCHAR (255) NULL,
    [PCP_PRACTICE_TIN]      VARCHAR (255) NULL,
    [PCP_GROUP_ID]          VARCHAR (255) NULL,
    [PCP_PRACTICE_NAME]     VARCHAR (255) NULL,
    [IND_PRACT_ID]          VARCHAR (255) NULL,
    [IND_PRACT_NAME]        VARCHAR (255) NULL,
    [RECERT_DATE]           VARCHAR (255) NULL,
    [RACE]                  VARCHAR (255) NULL,
    [RACE_DESC]             VARCHAR (255) NULL,
    [ETHNICITY]             VARCHAR (255) NULL,
    [ETHNICITY_DESC]        VARCHAR (255) NULL,
    [AUTO_ASSIGN]           VARCHAR (255) NULL,
    [ASAP_ID]               VARCHAR (255) NULL,
    [FEW_ID]                VARCHAR (255) NULL,
    [LST_HRA_DATE]          VARCHAR (255) NULL,
    [NXT_HRA_DATE]          VARCHAR (255) NULL,
    [HRA_ID]                VARCHAR (255) NULL,
    [MEMBER_EMAIL]          VARCHAR (250) NULL,
    [A_LAST_UPDATE_DATE]    DATE          DEFAULT (getdate()) NULL,
    [A_LAST_UPDATE_BY]      VARCHAR (255) DEFAULT ('PKG Import') NULL,
    [A_LAST_UPDATE_FLAG]    VARCHAR (1)   DEFAULT ('Y') NULL,
    [MEMBER_STATUS]         CHAR (1)      DEFAULT ('N') NOT NULL,
    [MEMBER_TERM_DATE]      DATE          NULL,
    [LoadType]              CHAR (1)      NULL,
    [PCP_Specialty_Code]    VARCHAR (50)  NULL,
    [PCP_Specialty]         VARCHAR (255) NULL,
    [SrcFileName]           VARCHAR (100) NULL,
    [LoadDate]              DATE          NOT NULL,
    [DataDate]              DATE          NOT NULL,
    [CreateDate]            DATETIME2 (7) CONSTRAINT [Df_astUhcHighRisk_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]              VARCHAR (50)  CONSTRAINT [Df_astUhcHighRisk_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    CONSTRAINT [PK_MbrUhcMbrHighRisk] PRIMARY KEY CLUSTERED ([MbrUhcMbrHighRisk_URN] ASC),
    CONSTRAINT [CK_MbrUhcMbrHighRisk_LoadType] CHECK ([loadType]='S' OR [loadType]='P'),
    CONSTRAINT [cV_UHCMemberByPCP_MStatus] CHECK ([MEMBER_STATUS]='T' OR [MEMBER_STATUS]='N' OR [MEMBER_STATUS]='E')
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Enforce field has a valid value', @level0type = N'SCHEMA', @level0name = N'ast', @level1type = N'TABLE', @level1name = N'MbrUhcMbrHighRisk', @level2type = N'CONSTRAINT', @level2name = N'CK_MbrUhcMbrHighRisk_LoadType';

