CREATE TABLE [ast].[MbrUhcMicroIncentives] (
    [MbrUhcMicroIncentive_URN] INT           IDENTITY (1, 1) NOT NULL,
    [GRGR_ID]                  VARCHAR (255) NULL,
    [GRGR_NAME]                VARCHAR (255) NULL,
    [SGSG_ID]                  VARCHAR (255) NULL,
    [SGSG_NAME]                VARCHAR (255) NULL,
    [MEDICAID_NUMBER]          VARCHAR (255) NULL,
    [MeasureAndLob]            VARCHAR (255) NULL,
    [MEMBER_LAST_NAME]         VARCHAR (255) NULL,
    [MEMBER_FIRST_NAME]        VARCHAR (255) NULL,
    [MEMBER_MIDDLE_INITIAL]    VARCHAR (255) NULL,
    [ADDRESS_LINE_1]           VARCHAR (255) NULL,
    [ADDRESS_LINE_2]           VARCHAR (255) NULL,
    [CITY]                     VARCHAR (255) NULL,
    [STATE]                    VARCHAR (255) NULL,
    [ZIP_CODE]                 VARCHAR (255) NULL,
    [HOME_PHONE_NUMBER]        VARCHAR (255) NULL,
    [COUNTY]                   VARCHAR (255) NULL,
    [SBAD_MAIL_ADDR1]          VARCHAR (255) NULL,
    [SBAD_MAIL_ADDR2]          VARCHAR (255) NULL,
    [SBAD_MAIL_CITY]           VARCHAR (255) NULL,
    [SBAD_MAIL_STATE]          VARCHAR (255) NULL,
    [SBAD_MAIL_ZIP]            VARCHAR (255) NULL,
    [MEDICARE_NUMBER]          VARCHAR (255) NULL,
    [SUBSCRIBER_ID]            VARCHAR (255) NOT NULL,
    [PROVIDER_ID]              VARCHAR (255) NULL,
    [PROVIDER_FIRST_NAME]      VARCHAR (255) NULL,
    [PROVIDER_MIDDLE_INITIAL]  VARCHAR (255) NULL,
    [PROVIDER_LAST_NAME]       VARCHAR (255) NULL,
    [MANUAL_ASSIGNMENT_REASON] VARCHAR (255) NULL,
    [NETWORK_ID]               VARCHAR (255) NULL,
    [NETWORK_NAME]             VARCHAR (255) NULL,
    [GENDER]                   VARCHAR (255) NULL,
    [EFFECTIVE_DATE]           DATE          NULL,
    [TERMINATION_DATE]         DATE          NULL,
    [PLAN_ID]                  VARCHAR (255) NULL,
    [PLAN_DESC]                VARCHAR (255) NULL,
    [PRODUCT_ID]               VARCHAR (255) NULL,
    [PRODUCT_DESC]             VARCHAR (255) NULL,
    [RELATIONSHIP_CODE]        VARCHAR (255) NULL,
    [DATE_OF_BIRTH]            DATE          NULL,
    [LANGUAGE_CODE]            VARCHAR (255) NULL,
    [RESP_PERSON_LAST_NAME]    VARCHAR (255) NULL,
    [RESP_PERSON_FIRST_NAME]   VARCHAR (255) NULL,
    [RESP_PERSON_ID]           VARCHAR (255) NULL,
    [RESP_PERSON_ADDRESS_1]    VARCHAR (255) NULL,
    [RESP_PERSON_ADDRESS_2]    VARCHAR (255) NULL,
    [RESP_PERSON_CITY]         VARCHAR (255) NULL,
    [RESP_PERSON_STATE]        VARCHAR (255) NULL,
    [RESP_PERSON_ZIP_CODE]     VARCHAR (255) NULL,
    [RESP_PERSON_PHONE_NUMBER] VARCHAR (255) NULL,
    [PLAN_CODE]                VARCHAR (255) NULL,
    [RECERTIFICATION_DATE]     DATE          NULL,
    [ETHNICITY]                VARCHAR (255) NULL,
    [ETHNICITY_DESC]           VARCHAR (255) NULL,
    [FAMILY_LINK]              VARCHAR (255) NULL,
    [TRANSACTION_TYPE]         VARCHAR (255) NULL,
    [CONTRACT]                 VARCHAR (255) NULL,
    [PBP]                      VARCHAR (255) NULL,
    [ORIGINAL_EFFECTIVE_DATE]  DATE          NULL,
    [loadDate]                 DATE          NOT NULL,
    [DataDate]                 DATE          NOT NULL,
    [SrcFileName]              VARCHAR (100) NOT NULL,
    [CreatedDate]              DATETIME2 (7) CONSTRAINT [DF_astMbrUhcMicroIncentive_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                VARCHAR (50)  CONSTRAINT [DF_astMbrUhcMicroIncentive_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    PRIMARY KEY CLUSTERED ([MbrUhcMicroIncentive_URN] ASC)
);

