CREATE TABLE [ast].[MbrUhcCP_Cpcpi] (
    [mbrUhcCP_Cpcpi_URN]                         INT           IDENTITY (1, 1) NOT NULL,
    [GroupName]                                  VARCHAR (255) NULL,
    [Physician]                                  VARCHAR (255) NULL,
    [PhysicianAddress]                           VARCHAR (255) NULL,
    [FirstName]                                  VARCHAR (255) NULL,
    [LastName]                                   VARCHAR (255) NULL,
    [MemberID]                                   VARCHAR (255) NULL,
    [DOB]                                        DATE          NULL,
    [Phone]                                      VARCHAR (255) NULL,
    [MemberAddress]                              VARCHAR (255) NULL,
    [MemberState]                                VARCHAR (255) NULL,
    [MemberZip]                                  VARCHAR (255) NULL,
    [DateOfLastService]                          DATE          NULL,
    [IncentiveProgram]                           VARCHAR (255) NULL,
    [CareScore]                                  VARCHAR (255) NULL,
    [FUH_FollowUpHospMentalIllness]              VARCHAR (10)  NULL,
    [PPC_PostPartumCare]                         VARCHAR (10)  NULL,
    [PPC_TimelinessPrenatalCare]                 VARCHAR (10)  NULL,
    [AAP_AdultAccessPreventiveHS]                VARCHAR (10)  NULL,
    [ADD_FollowUpCareChild_ADHD_ContMaintPhase]  VARCHAR (10)  NULL,
    [ADD_FollowUpCareChild_ADHD_InitiationPhase] VARCHAR (10)  NULL,
    [AWC_AdolescentWellCareVisits]               VARCHAR (10)  NULL,
    [BCS_BreastCancerScreening]                  VARCHAR (10)  NULL,
    [CBP_ControllingHighBloodPressure]           VARCHAR (10)  NULL,
    [CCS_CervicalCancerScreening]                VARCHAR (10)  NULL,
    [CDC_CompDiabetesCareBP]                     VARCHAR (10)  NULL,
    [CDC_CompDiabetesCareEyeE]                   VARCHAR (10)  NULL,
    [CDC_CompDiabetesCareHbA1cTesting]           VARCHAR (10)  NULL,
    [CDC_CompDiabetesCareHbA1cControl]           VARCHAR (10)  NULL,
    [CDC_CompDiabetesCareHbA1cPoorControl]       VARCHAR (10)  NULL,
    [CDC_CompDiabetesCareMedicalNephropathy]     VARCHAR (10)  NULL,
    [CIS_ChildImmunizationStatusComb10]          VARCHAR (10)  NULL,
    [SSD_DiabetesScreeningSchizophreniaBipolar]  VARCHAR (10)  NULL,
    [URI_ChildUpperRespInf]                      VARCHAR (10)  NULL,
    [W15_WellChildVisitsFirst_15_Months]         VARCHAR (10)  NULL,
    [W34_WellChildVisits_3_6_Years]              VARCHAR (10)  NULL,
    [WCC_WeightCounselingChildBMIPercentile]     VARCHAR (10)  NULL,
    [WCC_WeightCounselingChildNutrition]         VARCHAR (10)  NULL,
    [WCC_WeightCounselingChildPhysicalActivity]  VARCHAR (10)  NULL,
    [HealthPlanName]                             VARCHAR (255) NULL,
    [Product]                                    VARCHAR (255) NULL,
    [loadDate]                                   DATE          NOT NULL,
    [DataDate]                                   DATE          NOT NULL,
    [SrcFileName]                                VARCHAR (100) NOT NULL,
    [CreatedDate]                                DATETIME2 (7) CONSTRAINT [DF_astMbrUhcCPPCPi_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                                  VARCHAR (50)  CONSTRAINT [DF_astMbrUhcCPPCPi_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    PRIMARY KEY CLUSTERED ([mbrUhcCP_Cpcpi_URN] ASC)
);

