CREATE TABLE [ast].[NtfGhhActivity] (
    [ghhNftID]              INT            IDENTITY (1, 1) NOT NULL,
    [TRANSACTION]           VARCHAR (50)   NULL,
    [HospitalAccountNumber] VARCHAR (50)   NULL,
    [MedicalRecordNumber]   VARCHAR (50)   NULL,
    [PatientLastName]       VARCHAR (75)   NULL,
    [PatientFirstName]      VARCHAR (75)   NULL,
    [PatientMiddleInitial]  VARCHAR (75)   NULL,
    [PatientAddress1]       VARCHAR (125)  NULL,
    [PatientAddress2]       VARCHAR (125)  NULL,
    [PatientCity]           VARCHAR (75)   NULL,
    [PatientState]          VARCHAR (75)   NULL,
    [PatientZip]            VARCHAR (75)   NULL,
    [PatientPhone]          VARCHAR (75)   NULL,
    [PatientDob]            VARCHAR (50)   NULL,
    [PatientGender]         VARCHAR (75)   NULL,
    [AdmitDate]             VARCHAR (50)   NULL,
    [AdmitTime]             VARCHAR (50)   NULL,
    [AdmitHospital]         VARCHAR (75)   NULL,
    [ChiefComplaint]        VARCHAR (1000) NULL,
    [Carrier1Code]          VARCHAR (75)   NULL,
    [Carrier1Name]          VARCHAR (75)   NULL,
    [InsuredID1]            VARCHAR (75)   NULL,
    [Carrier2CODE]          VARCHAR (75)   NULL,
    [Carrier2NAME]          VARCHAR (75)   NULL,
    [InsuredID2]            VARCHAR (75)   NULL,
    [Carrier3CODE]          VARCHAR (75)   NULL,
    [Carrier3NAME]          VARCHAR (75)   NULL,
    [InsuredID3]            VARCHAR (75)   NULL,
    [AdmittingPhysician]    VARCHAR (75)   NULL,
    [AttendingPhysician]    VARCHAR (75)   NULL,
    [ReferringPhysician]    VARCHAR (75)   NULL,
    [ConsultingPhysician]   VARCHAR (75)   NULL,
    [Comments]              VARCHAR (250)  NULL,
    [NursingStation]        VARCHAR (75)   NULL,
    [PatientRoom]           VARCHAR (75)   NULL,
    [PatientBed]            VARCHAR (75)   NULL,
    [PatientServiceCode]    VARCHAR (75)   NULL,
    [PatientType]           VARCHAR (75)   NULL,
    [DischargeDate]         VARCHAR (50)   NULL,
    [DischargeTime]         VARCHAR (50)   NULL,
    [DischargeDisposition]  VARCHAR (250)  NULL,
    [FileDate]              DATETIME2 (7)  NULL,
    [loadDate]              DATETIME2 (7)  NULL,
    PRIMARY KEY CLUSTERED ([ghhNftID] ASC)
);

