CREATE TABLE [ast].[NtfNotification] (
    [CreatedDate]             DATETIME       DEFAULT (getdate()) NULL,
    [CreatedBy]               VARCHAR (20)   DEFAULT (suser_name()) NULL,
    [LastUpdatedDate]         DATETIME       DEFAULT (getdate()) NULL,
    [LastUpdatedBy]           VARCHAR (20)   DEFAULT (suser_name()) NULL,
    [LoadDate]                DATE           NULL,
    [DataDate]                DATE           NULL,
    [NtfSkey]                 INT            IDENTITY (1, 1) NOT NULL,
    [ClientKey]               INT            NULL,
    [NtfSource]               VARCHAR (50)   NULL,
    [ClientMemberKey]         VARCHAR (50)   NULL,
    [srcEventType]            VARCHAR (20)   NULL,
    [SrcAdmitDateTime]        DATETIME       NULL,
    [SrcActualDischargeDate]  DATE           CONSTRAINT [DF_srcNtfActualDischargeDate] DEFAULT ('1900-01-01') NULL,
    [SrcDischargeDisposition] VARCHAR (1000) NULL,
    [srcNtfPatientType]       VARCHAR (50)   NULL,
    [SrcChiefComplaint]       VARCHAR (1000) NULL,
    [SrcDiagnosisCode]        VARCHAR (100)  NULL,
    [SrcDiagnosisDesc]        VARCHAR (1000) NULL,
    [SrcAdmitHospital]        VARCHAR (100)  NULL,
    [AceFollowUpDueDate]      DATE           NULL,
    [AdiKey]                  INT            NULL,
    [SrcFileName]             VARCHAR (100)  NULL,
    [AceID]                   NUMERIC (15)   NULL,
    [RowStatus]               INT            DEFAULT ((0)) NULL,
    [DrgCode]                 VARCHAR (20)   NULL,
    [DschrgInferredInd]       BIT            DEFAULT ((0)) NULL,
    [DschrgInferredDate]      DATE           CONSTRAINT [DF_DschrgInferredDate] DEFAULT ('') NULL,
    [CaseType]                VARCHAR (50)   NULL,
    [Exported]                TINYINT        CONSTRAINT [DF_astExported] DEFAULT ((3)) NOT NULL,
    PRIMARY KEY CLUSTERED ([NtfSkey] ASC)
);

