CREATE TABLE [ast].[NtfUhcIpCensus] (
    [ntfUhcIPCensusKey]        INT            IDENTITY (1, 1) NOT NULL,
    [LOB]                      VARCHAR (50)   NULL,
    [PatientName]              VARCHAR (150)  NULL,
    [RosterSubgroup]           VARCHAR (50)   NULL,
    [PatientIdentifier]        VARCHAR (50)   NULL,
    [IndvID]                   VARCHAR (50)   NULL,
    [Alt_ID]                   VARCHAR (50)   NULL,
    [PatientBirthDate]         DATE           NULL,
    [PatientGender]            VARCHAR (20)   NULL,
    [PrimaryLanguage]          VARCHAR (50)   NULL,
    [Address]                  VARCHAR (255)  NULL,
    [City]                     VARCHAR (65)   NULL,
    [State]                    VARCHAR (50)   NULL,
    [Zip]                      VARCHAR (50)   NULL,
    [ContactPhoneNumber]       VARCHAR (50)   NULL,
    [AlternativePhoneNumber]   VARCHAR (50)   NULL,
    [HospitalState]            VARCHAR (50)   NULL,
    [ProviderIdentifiedMPIN]   VARCHAR (50)   NULL,
    [HospitalName]             VARCHAR (150)  NULL,
    [AttendingPhysicianIdMPIN] VARCHAR (50)   NULL,
    [AttendingPhysicianName]   VARCHAR (150)  NULL,
    [PrimaryCarePhysicianName] VARCHAR (150)  NULL,
    [AdmissionDate]            DATE           NULL,
    [DischargeDate]            DATE           NULL,
    [AdmissionDateReported]    DATE           NULL,
    [DateDcReported]           DATE           NULL,
    [PrimaryDiagnosisCode]     VARCHAR (50)   NULL,
    [PrimaryDiagnosisDesc]     VARCHAR (255)  NULL,
    [TypeOfFacility]           VARCHAR (50)   NULL,
    [DispositionDesc]          VARCHAR (255)  NULL,
    [CaseStatus]               VARCHAR (50)   NULL,
    [ReAdmissionDays]          VARCHAR (50)   NULL,
    [LengthOfStay]             INT            NULL,
    [RpmScore]                 NUMERIC (4, 3) NULL,
    [RstScore]                 VARCHAR (50)   NULL,
    [IdDate]                   DATE           NULL,
    [PrimaryCarePhysicianNPI]  VARCHAR (50)   NULL,
    [PatientCardID]            VARCHAR (50)   NULL,
    [DateFileRecieved]         DATE           NOT NULL,
    [LoadDate]                 DATE           NOT NULL,
    [DataDate]                 DATE           NOT NULL,
    [SrcFileName]              VARCHAR (100)  NOT NULL,
    [CreatedDate]              DATETIME       CONSTRAINT [DF_astNtfUchIpCensus_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                VARCHAR (50)   CONSTRAINT [DF_astNtfUchIpCensus_CreatedBY] DEFAULT (suser_sname()) NOT NULL,
    PRIMARY KEY CLUSTERED ([ntfUhcIPCensusKey] ASC)
);

