CREATE TABLE [ast].[PstMbrDemographic] (
    [PstMbrDemographicKey] INT           IDENTITY (1, 1) NOT NULL,
    [adiKey]               INT           NOT NULL,
    [AdiTableName]         VARCHAR (100) NOT NULL,
    [stgRowStatus]         VARCHAR (20)  NOT NULL,
    [LoadDate]             DATETIME      NOT NULL,
    [CreatedDate]          DATETIME      CONSTRAINT [DF_PstMbrDemographic_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            VARCHAR (50)  CONSTRAINT [DF_PstMbrDemographic_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [srcClientMemberKey]   VARCHAR (50)  NOT NULL,
    [srcLastName]          VARCHAR (100) NULL,
    [srcFirstName]         VARCHAR (100) NULL,
    [srcMiddleName]        VARCHAR (100) NULL,
    [srcSSN]               VARCHAR (15)  NULL,
    [srcGender]            CHAR (5)      NULL,
    [srcDOB]               DATE          NULL,
    [srcMedicaidID]        VARCHAR (15)  NULL,
    [srcHICN]              VARCHAR (11)  NULL,
    [srcMBI]               VARCHAR (11)  NULL,
    [srcMedicareID]        VARCHAR (15)  NULL,
    [srcEthnicity]         VARCHAR (20)  NULL,
    [srcRace]              VARCHAR (20)  NULL,
    [srcPrimaryLanguage]   VARCHAR (20)  NULL,
    [transEffectiveDate]   DATE          NULL,
    [transExpirationDate]  DATE          CONSTRAINT [DF_MbrDemographicExpirationDate] DEFAULT ('12/31/9999') NOT NULL,
    [MbrMemberKey]         INT           NULL,
    [MbrDemographicKey]    INT           NULL,
    [mbrLoadHistoryKey]    INT           NULL,
    PRIMARY KEY CLUSTERED ([PstMbrDemographicKey] ASC),
    CONSTRAINT [CK_pstMbrDemographic_stgRowStatus] CHECK ([stgRowStatus]='Exported' OR [stgRowStatus]='Valid' OR [stgRowStatus]='Loaded')
);

