CREATE TABLE [adw].[AhsExpMembership] (
    [AhsExpMembershipKey]                INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]                        DATETIME2 (7) CONSTRAINT [DF_AhsExpMembership_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                          VARCHAR (50)  CONSTRAINT [DF_AhsExpMembership_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                    DATETIME2 (7) CONSTRAINT [DF_AhsExpMembership_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                      VARCHAR (50)  CONSTRAINT [DF_AhsExpMembership_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [Exported]                           TINYINT       DEFAULT ((0)) NOT NULL,
    [ExportedDate]                       DATE          DEFAULT ('01/01/1900') NOT NULL,
    [ClientMemberKey]                    VARCHAR (50)  NOT NULL,
    [ClientKey]                          INT           NOT NULL,
    [fctMembershipKey]                   INT           NOT NULL,
    [Exp_MEMBER_ID]                      VARCHAR (50)  NOT NULL,
    [Exp_CLIENT_ID]                      VARCHAR (50)  NULL,
    [Exp_MEDICAID_ID]                    VARCHAR (15)  NULL,
    [Exp_MEMBER_FIRST_NAME]              VARCHAR (30)  NULL,
    [Exp_MEMBER_MI]                      VARCHAR (30)  NULL,
    [Exp_MEMBER_LAST_NAME]               VARCHAR (30)  NULL,
    [Exp_DATE_OF_BIRTH]                  DATE          NULL,
    [Exp_MEMBER_GENDER]                  VARCHAR (10)  NULL,
    [Exp_HOME_ADDRESS]                   VARCHAR (100) NULL,
    [Exp_HOME_CITY]                      VARCHAR (35)  NULL,
    [Exp_HOME_STATE]                     VARCHAR (25)  NULL,
    [Exp_HOME_ZIPCODE]                   VARCHAR (14)  NULL,
    [Exp_MAILING_ADDRESS]                VARCHAR (100) NULL,
    [Exp_MAILING_CITY]                   VARCHAR (35)  NULL,
    [Exp_MAILING_STATE]                  VARCHAR (25)  NULL,
    [Exp_MAILING_ZIP]                    VARCHAR (14)  NULL,
    [Exp_HOME_PHONE]                     VARCHAR (25)  NULL,
    [Exp_ADDITIONAL_PHONE]               VARCHAR (25)  NULL,
    [Exp_CELL_PHONE]                     VARCHAR (25)  NULL,
    [Exp_Language]                       VARCHAR (50)  NULL,
    [Exp_Ethnicity]                      VARCHAR (25)  NULL,
    [Exp_Race]                           VARCHAR (25)  NULL,
    [Exp_Email]                          VARCHAR (50)  NULL,
    [Exp_MEDICARE_ID]                    VARCHAR (25)  NULL,
    [Exp_MEMBER_ORG_EFF_DATE]            DATE          NULL,
    [Exp_MEMBER_CONT_EFF_DATE]           DATE          NULL,
    [Exp_MEMBER_CUR_EFF_DATE]            DATE          NULL,
    [Exp_MEMBER_CUR_TERM_DATE]           DATE          NULL,
    [Exp_RESP_FIRST_NAME]                VARCHAR (25)  NULL,
    [Exp_RESP_LAST_NAME]                 VARCHAR (25)  NULL,
    [Exp_RESP_RELATIONSHIP]              VARCHAR (25)  NULL,
    [Exp_RESP_ADDRESS]                   VARCHAR (65)  NULL,
    [Exp_RESP_ADDRESS2]                  VARCHAR (65)  NULL,
    [Exp_RESP_CITY]                      VARCHAR (35)  NULL,
    [Exp_RESP_STATE]                     VARCHAR (255) NULL,
    [Exp_RESP_ZIP]                       VARCHAR (14)  NULL,
    [Exp_RESP_PHONE]                     VARCHAR (25)  NULL,
    [Exp_PRIMARY_RISK_FACTOR]            VARCHAR (35)  NULL,
    [Exp_COUNT_OPEN_CARE_OPPS]           VARCHAR (10)  NULL,
    [Exp_INP_ADMITS_LAST_12_MOS]         VARCHAR (10)  NULL,
    [Exp_LAST_INP_DISCHARGE]             DATE          NULL,
    [Exp_POST_DISCHARGE_FUP_VISIT]       DATE          NULL,
    [Exp_INP_FUP_WITHIN_7_DAYS]          VARCHAR (10)  NULL,
    [Exp_ER_VISITS_LAST_12_MOS]          VARCHAR (10)  NULL,
    [Exp_LAST_ER_VISIT]                  DATE          NULL,
    [Exp_POST_ER_FUP_VISIT]              DATE          NULL,
    [Exp_ER_FUP_WITHIN_7_DAYS]           VARCHAR (10)  NULL,
    [Exp_LAST_PCP_VISIT]                 DATE          NULL,
    [Exp_LAST_PCP_PRACTICE_SEEN]         VARCHAR (50)  NULL,
    [Exp_LAST_BH_VISIT]                  DATE          NULL,
    [Exp_LAST_BH_PRACTICE_SEEN]          VARCHAR (50)  NULL,
    [Exp_TOTAL_COSTS_LAST_12_MOS]        VARCHAR (25)  NULL,
    [Exp_INP_COSTS_LAST_12_MOS]          VARCHAR (25)  NULL,
    [Exp_ER_COSTS_LAST_12_MOS]           VARCHAR (25)  NULL,
    [Exp_OUTP_COSTS_LAST_12_MOS]         VARCHAR (25)  NULL,
    [Exp_PHARMACY_COSTS_LAST_12_MOS]     VARCHAR (25)  NULL,
    [Exp_PRIMARY_CARE_COSTS_LAST_12_MOS] VARCHAR (25)  NULL,
    [Exp_BEHAVIORAL_COSTS_LAST_12_MOS]   VARCHAR (25)  NULL,
    [Exp_OTHER_OFFICE_COSTS_LAST_12_MOS] VARCHAR (25)  NULL,
    [Exp_NEXT_PREVENTATIVE_VISIT_DUE]    DATE          NULL,
    [Exp_ACE_ID]                         VARCHAR (25)  NULL,
    [Exp_carrier_Member_ID]              VARCHAR (50)  NULL,
    [LoadDate]                           DATE          NOT NULL,
    PRIMARY KEY CLUSTERED ([AhsExpMembershipKey] ASC)
);

