CREATE TABLE [adw].[z__FctMemberMonthByMonth_Consolidated] (
    [FctMemberMonthByMonth_ConsolidatedSKey]                         INT             IDENTITY (1, 1) NOT NULL,
    [mbrMemberKey]                                                   INT             NOT NULL,
    [mbrDemographicKey]                                              INT             NOT NULL,
    [mbrPlanKey]                                                     INT             NOT NULL,
    [mbrCsPlanKey]                                                   INT             NOT NULL,
    [MbrPhoneKeyType1]                                               INT             NULL,
    [MbrPHoneKeyType3]                                               INT             DEFAULT ((0)) NULL,
    [MbrPhoneKeyType4]                                               INT             DEFAULT ((0)) NULL,
    [MbrAddressKey1]                                                 INT             NULL,
    [MbrAddressKey2]                                                 INT             DEFAULT ((0)) NULL,
    [CreatedDate]                                                    DATETIME        DEFAULT (getdate()) NULL,
    [CreatedBy]                                                      VARCHAR (20)    DEFAULT (suser_name()) NULL,
    [LastUpdatedDate]                                                DATETIME        DEFAULT (getdate()) NULL,
    [LastUpdatedBy]                                                  VARCHAR (20)    DEFAULT (suser_name()) NULL,
    [SrcFileName]                                                    VARCHAR (100)   DEFAULT ('ACECAREDW.dbo.vw_ActiveMembers') NULL,
    [AdiTableName]                                                   VARCHAR (100)   DEFAULT ('ACECAREDW.dbo.vw_ActiveMembers') NULL,
    [LoadDate]                                                       DATE            NULL,
    [DataDate]                                                       DATE            NULL,
    [MbrYear]                                                        INT             NULL,
    [MbrMonth]                                                       INT             NULL,
    [CLIENT]                                                         VARCHAR (15)    NULL,
    [ClientKey]                                                      INT             NULL,
    [MEMBER_ID]                                                      VARCHAR (255)   NULL,
    [MEMBER_FIRST_NAME]                                              VARCHAR (255)   NULL,
    [MEMBER_MI]                                                      VARCHAR (255)   NULL,
    [MEMBER_LAST_NAME]                                               VARCHAR (255)   NULL,
    [CLIENT_SUBSCRIBER_ID]                                           VARCHAR (255)   NULL,
    [Ace_ID]                                                         NUMERIC (15)    NULL,
    [PLAN_ID]                                                        VARCHAR (255)   NULL,
    [PRODUCT_CODE]                                                   VARCHAR (255)   NULL,
    [SUBGRP_ID]                                                      VARCHAR (255)   NULL,
    [SUBGRP_NAME]                                                    VARCHAR (255)   NULL,
    [MEDICAID_ID]                                                    VARCHAR (255)   NULL,
    [AGE]                                                            INT             NULL,
    [DATE_OF_BIRTH]                                                  DATE            NULL,
    [GENDER]                                                         VARCHAR (255)   NULL,
    [LANG_CODE]                                                      VARCHAR (255)   NULL,
    [ETHNICITY]                                                      VARCHAR (255)   NULL,
    [RACE]                                                           VARCHAR (20)    NULL,
    [MEMBER_HOME_ADDRESS]                                            VARCHAR (255)   NULL,
    [MEMBER_HOME_ADDRESS2]                                           VARCHAR (255)   NULL,
    [MEMBER_HOME_CITY]                                               VARCHAR (255)   NULL,
    [MEMBER_HOME_STATE]                                              VARCHAR (255)   NULL,
    [MEMBER_HOME_ZIP_C]                                              VARCHAR (255)   NULL,
    [MEMBER_HOME_PHONE]                                              VARCHAR (255)   NULL,
    [MEMBER_MAIL_ADDRESS]                                            VARCHAR (255)   NULL,
    [MEMBER_MAIL_ADDRESS2]                                           VARCHAR (255)   NULL,
    [MEMBER_MAIL_CITY]                                               VARCHAR (255)   NULL,
    [MEMBER_MAIL_STATE]                                              VARCHAR (255)   NULL,
    [MEMBER_MAIL_ZIP_C]                                              VARCHAR (255)   NULL,
    [MEMBER_MAIL_PHONE]                                              VARCHAR (255)   NULL,
    [MEMBER_COUNTY]                                                  VARCHAR (255)   NULL,
    [MEMBER_BUS_PHONE]                                               VARCHAR (255)   NULL,
    [MEMBER_ORG_EFF_DATE]                                            VARCHAR (255)   NULL,
    [MEMBER_CONT_EFF_DATE]                                           VARCHAR (255)   NULL,
    [MEMBER_CUR_EFF_DATE]                                            DATE            NULL,
    [MEMBER_CUR_TERM_DATE]                                           DATE            NULL,
    [PCP_CLIENT_ID]                                                  VARCHAR (255)   NULL,
    [PCP_FIRST_NAME]                                                 VARCHAR (255)   NULL,
    [PCP_LAST_NAME]                                                  VARCHAR (255)   NULL,
    [NPI]                                                            VARCHAR (255)   NULL,
    [PCP_AccountType]                                                VARCHAR (50)    NULL,
    [PCP_PHONE]                                                      VARCHAR (255)   NULL,
    [PCP_FAX]                                                        VARCHAR (255)   NULL,
    [PCP_ADDRESS]                                                    VARCHAR (255)   NULL,
    [PCP_ADDRESS2]                                                   VARCHAR (255)   NULL,
    [PCP_CITY]                                                       VARCHAR (255)   NULL,
    [PCP_STATE]                                                      VARCHAR (255)   NULL,
    [PCP_ZIP_C]                                                      VARCHAR (20)    NULL,
    [PCP_EFFECTIVE_DATE]                                             DATE            NULL,
    [PCP_TERM_DATE]                                                  DATE            NULL,
    [PCP_PRACTICE_TIN]                                               VARCHAR (255)   NULL,
    [PCP_GROUP_ID]                                                   VARCHAR (255)   NULL,
    [PCP_PRACTICE_NAME]                                              VARCHAR (255)   NULL,
    [AUTO_ASSIGN]                                                    VARCHAR (255)   NULL,
    [MEMBER_STATUS]                                                  VARCHAR (1)     NULL,
    [MEMBER_TERM_DATE]                                               DATE            NULL,
    [IPRO_ADMIT_RISK_SCORE]                                          VARCHAR (255)   NULL,
    [RISK_CATEGORY_C]                                                VARCHAR (255)   NULL,
    [LINE_OF_BUSINESS]                                               VARCHAR (255)   NULL,
    [PLAN_CODE]                                                      VARCHAR (255)   NULL,
    [PLAN_DESC]                                                      VARCHAR (255)   NULL,
    [PRIMARY_RISK_FACTOR]                                            VARCHAR (255)   NULL,
    [TOTAL_COSTS_LAST_12_MOS]                                        VARCHAR (255)   NULL,
    [COUNT_OPEN_CARE_OPPS]                                           VARCHAR (255)   NULL,
    [INP_COSTS_LAST_12_MOS]                                          VARCHAR (255)   NULL,
    [ER_COSTS_LAST_12_MOS]                                           VARCHAR (255)   NULL,
    [OUTP_COSTS_LAST_12_MOS]                                         VARCHAR (255)   NULL,
    [PHARMACY_COSTS_LAST_12_MOS]                                     VARCHAR (255)   NULL,
    [PRIMARY_CARE_COSTS_LAST_12_MOS]                                 VARCHAR (255)   NULL,
    [BEHAVIORAL_COSTS_LAST_12_MOS]                                   VARCHAR (255)   NULL,
    [OTHER_OFFICE_COST_LAST_12_MOS]                                  VARCHAR (255)   NULL,
    [INP_ADMITS_LAST_12_MOS]                                         VARCHAR (255)   NULL,
    [LAST_INP_DISCHARGE]                                             VARCHAR (255)   NULL,
    [POST_DISCHARGE_FU		VARCHAR(255)
      ,[INP_FUP_WITHIN_7_DAYS] VARCHAR (255)   NULL,
    [ER_VISITS_LAST_12_MOS]                                          NUMERIC (12, 2) NULL,
    [LAST_ER_VISIT]                                                  VARCHAR (255)   NULL,
    [POST_ER_FUP_VISIT]                                              VARCHAR (255)   NULL,
    [ER_FUP_WITHIN_7_DAYS]                                           VARCHAR (255)   NULL,
    [LAST_PCP_VISIT]                                                 VARCHAR (255)   NULL,
    [LAST_PCP_PRACTICE_SEEN]                                         VARCHAR (255)   NULL,
    [LAST_BH_VISIT]                                                  VARCHAR (255)   NULL,
    [LAST_BH_PRACTICE_SEEN]                                          VARCHAR (255)   NULL,
    [MEMBER_MONTH_COUNT]                                             VARCHAR (255)   NULL,
    [MEMBER_POD_C]                                                   INT             NULL,
    [MEMBER_POD_DESC]                                                VARCHAR (50)    NULL,
    [PCP_POD_C]                                                      INT             NULL,
    [PCP_POD_DESC]                                                   VARCHAR (50)    NULL,
    [PCP_NAME]                                                       VARCHAR (512)   NULL,
    [CLIENT_UNIQUE_SYSTEM_ID	VARCHAR(255)
      ,[MEDICARE_ID]      VARCHAR (255)   NULL,
    [RESP_LAST_NAME]                                                 VARCHAR (255)   NULL,
    [RESP_FIRST_NAME]                                                VARCHAR (255)   NULL,
    [RESP_ADDRESS]                                                   VARCHAR (255)   NULL,
    [RESP_ADDRESS2]                                                  VARCHAR (255)   NULL,
    [RESP_CITY]                                                      VARCHAR (255)   NULL,
    [RESP_STATE]                                                     VARCHAR (255)   NULL,
    [RESP_ZIP]                                                       VARCHAR (255)   NULL,
    [RESP_PHONE]                                                     VARCHAR (255)   NULL,
    [AhsPlanCode]                                                    VARCHAR (50)    NULL,
    [AhsPlanName]                                                    VARCHAR (150)   NULL,
    [CurMonthsOld]                                                   INT             NULL,
    [CurYearsOld]                                                    INT             NULL
);

