







CREATE VIEW [dbo].[vw_AH_Membership_Secondary]
AS
SELECT M.UHC_SUBSCRIBER_ID AS MEMBER_ID,
       'UHC' AS CLIENT_ID,
       M.MEDICAID_ID,
       REPLACE(RTRIM(M.MEMBER_FIRST_NAME), ',', ' ') AS MEMBER_FIRST_NAME,
       REPLACE(RTRIM(M.MEMBER_MI), ',', ' ') AS MEMBER_MI,
       REPLACE(RTRIM(M.MEMBER_LAST_NAME), ',', ' ') AS MEMBER_LAST_NAME,
       M.DATE_OF_BIRTH,
       M.GENDER AS MEMBER_GENDER,
       REPLACE(RTRIM(M.MEMBER_HOME_ADDRESS), ',', ' ') + ' ' + REPLACE(RTRIM(M.MEMBER_HOME_ADDRESS2), ',', ' ') AS HOME_ADDRESS,
       M.MEMBER_HOME_CITY AS HOME_CITY,
       M.MEMBER_HOME_STATE AS HOME_STATE,
       M.MEMBER_HOME_ZIP AS HOME_ZIPCODE,
       /*GETTING PREFERRED ADDRESS TO MAILING ADDRESS*/
       CASE
           WHEN PREADD.MEMBER_ADDRESS IS NULL THEN
               REPLACE(RTRIM(M.MEMBER_HOME_ADDRESS), ',', ' ') + ' ' + REPLACE(RTRIM(M.MEMBER_HOME_ADDRESS2), ',', ' ')
           ELSE
               REPLACE(RTRIM(PREADD.MEMBER_ADDRESS), ',', ' ')
       END AS MAILING_ADDRESS,
       CASE
           WHEN PREADD.MEMBER_CITY IS NULL THEN
               M.MEMBER_HOME_CITY
           ELSE
               PREADD.MEMBER_CITY
       END AS MAILING_CITY,
       CASE
           WHEN PREADD.MEMBER_STATE IS NULL THEN
               M.MEMBER_HOME_STATE
           ELSE
               PREADD.MEMBER_STATE
       END AS MAILING_STATE,
       CASE
           WHEN PREADD.MEMEBR_ZIP IS NULL THEN
               M.MEMBER_HOME_ZIP
           ELSE
               PREADD.MEMEBR_ZIP
       END AS MAILING_ZIP,
        --  , REPLACE(RTRIM(M.MEMBER_HOME_ADDRESS), ',', ' ')+' '+REPLACE(RTRIM(M.MEMBER_HOME_ADDRESS2), ',', ' ') AS MAILING_ADDRESS
        -- , M.MEMBER_HOME_CITY AS MAILING_CITY
        -- , M.MEMBER_HOME_STATE AS MAILING_STATE
        --  , M.MEMBER_HOME_ZIP AS MAILING_ZIP
       M.MEMBER_HOME_PHONE AS HOME_PHONE,
       M.MEMBER_MAIL_PHONE AS ADDITIONAL_PHONE,
       M.MEMBER_HOME_PHONE AS CELL_PHONE,
		case when (ISNULL(M.lang_code, '') = '') then 'TEST LANGUAGE' else ltrim(rtrim(m.LANG_CODE)) end as LANGUAGE,
   --    ISNULL(NULL, 'TEST LANGUAGE') AS LANGUAGE,
		case when (ISNULL(M.ethnicity_desc, '') = '') then 'TEST ETHNICITY' else ltrim(rtrim(m.ethnicity_desc)) end as ETHNICITY,
--       ISNULL(NULL, 'Test ETHNICITY') AS Ethnicity,
       M.MEDICARE_ID,
       M.MEMBER_ORG_EFF_DATE,
       M.MEMBER_CONT_EFF_DATE,
       M.MEMBER_CUR_EFF_DATE,
       M.MEMBER_CUR_TERM_DATE,
       REPLACE(RTRIM(M.RESP_FIRST_NAME), ',', ' ') AS RESP_FIRST_NAME,
       REPLACE(RTRIM(M.RESP_LAST_NAME), ',', ' ') AS RESP_LAST_NAME,
       'Responsible Party' AS RESP_RELATIONSHIP, -- PlaceHolder for future data
       REPLACE(RTRIM(M.RESP_ADDRESS), ',', ' ') AS RESP_ADDRESS,
       REPLACE(RTRIM(M.RESP_ADDRESS2), ',', ' ') AS RESP_ADDRESS2,
       M.RESP_CITY,
       M.RESP_STATE,
       M.RESP_ZIP,
       M.RESP_PHONE,
       UPPER(REPLACE(RTRIM(mS.PRIMARY_RISK_FACTOR), ',', ' ')) AS PRIMARY_RISK_FACTOR,
       mS.COUNT_OPEN_CARE_OPPS,
       mS.INP_ADMITS_LAST_12_MOS,
       mS.LAST_INP_DISCHARGE,
       mS.POST_DISCHARGE_FUP_VISIT,
       mS.INP_FUP_WITHIN_7_DAYS,
       mS.ER_VISITS_LAST_12_MOS,
       mS.LAST_ER_VISIT,
       mS.POST_ER_FUP_VISIT,
       mS.ER_FUP_WITHIN_7_DAYS,
       mS.LAST_PCP_VISIT,
       REPLACE(RTRIM(mS.LAST_PCP_PRACTICE_SEEN), ',', ' ') AS LAST_PCP_PRACTICE_SEEN,
       mS.LAST_BH_VISIT,
       REPLACE(RTRIM(mS.LAST_BH_PRACTICE_SEEN), ',', ' ') AS LAST_BH_PRACTICE_SEEN,
       REPLACE(RTRIM(mS.TOTAL_COSTS_LAST_12_MOS), ',', '') AS TOTAL_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.INP_COSTS_LAST_12_MOS), ',', '') AS INP_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.ER_COSTS_LAST_12_MOS), ',', '') AS ER_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.OUTP_COSTS_LAST_12_MOS), ',', '') AS OUTP_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.PHARMACY_COSTS_LAST_12_MOS), ',', '') AS PHARMACY_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.PRIMARY_CARE_COSTS_LAST_12_MOS), ',', '') AS PRIMARY_CARE_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.BEHAVIORAL_COSTS_LAST_12_MOS), ',', '') AS BEHAVIORAL_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(mS.OTHER_OFFICE_COSTS_LAST_12_MOS), ',', '') AS OTHER_OFFICE_COSTS_LAST_12_MOS,
       '12/12/2099' AS NEXT_PREVENTATIVE_VISIT_DUE,
       REPLACE(RTRIM(M.MEMBER_EMAIL), ',', ' ') AS EMAIL,
       ISNULL(NULL, 'TEST RACE') AS RACE
FROM dbo.UHC_MembersByPCP AS M
    /* additional details from Mmr summary table */
    LEFT JOIN (SELECT um.URN,
               um.UHC_SUBSCRIBER_ID,
               um.IPRO_ADMIT_RISK_SCORE,
               um.LINE_OF_BUSINESS AS LOB,
               um.PRIMARY_RISK_FACTOR,
               um.COUNT_OPEN_CARE_OPPS,
               um.INP_ADMITS_LAST_12_MOS,
               um.LAST_INP_DISCHARGE,
               um.POST_DISCHARGE_FUP_VISIT,
               um.INP_FUP_WITHIN_7_DAYS,
               um.ER_VISITS_LAST_12_MOS,
               um.LAST_ER_VISIT,
               um.POST_ER_FUP_VISIT,
               um.ER_FUP_WITHIN_7_DAYS,
               um.LAST_PCP_VISIT,
               um.LAST_PCP_PRACTICE_SEEN,
               um.LAST_BH_VISIT,
               um.LAST_BH_PRACTICE_SEEN,
               um.TOTAL_COSTS_LAST_12_MOS,
               um.INP_COSTS_LAST_12_MOS,
               um.ER_COSTS_LAST_12_MOS,
               um.OUTP_COSTS_LAST_12_MOS,
               um.PHARMACY_COSTS_LAST_12_MOS,
               um.PRIMARY_CARE_COSTS_LAST_12_MOS,
               um.BEHAVIORAL_COSTS_LAST_12_MOS,
               um.OTHER_OFFICE_COSTS_LAST_12_MOS
        FROM dbo.UHC_Membership AS um
        WHERE (um.A_LAST_UPDATE_FLAG = 'Y')
    ) AS mS ON M.UHC_SUBSCRIBER_ID = mS.UHC_SUBSCRIBER_ID
    JOIN (SELECT mp.URN,
               ROW_NUMBER() OVER (PARTITION BY mp.UHC_SUBSCRIBER_ID
                                  ORDER BY mp.A_LAST_UPDATE_DATE ASC
                                 ) arn
        FROM dbo.UHC_MembersByPCP mp
        WHERE mp.A_LAST_UPDATE_FLAG IN ( 'Y', 'L' )
    ) urns ON M.URN = urns.URN
           AND urns.arn = 1
    LEFT JOIN (SELECT PD.CLIENT_PATIENT_ID AS MEMBER_ID,
              REPLACE(REPLACE(PDD.ADDRESS_TEXT, CHAR(13), ''), CHAR(10), '') AS MEMBER_ADDRESS
		  , REPLACE(REPLACE(PDD.CITY, CHAR(13), ''), CHAR(10), '') AS MEMBER_CITY
		  , REPLACE(REPLACE(PDD.STATE, CHAR(13), ''), CHAR(10), '') AS MEMBER_STATE
		  , REPLACE(REPLACE(PDD.ZIP , CHAR(13), ''), CHAR(10), '') AS MEMEBR_ZIP  ,
               PDD.CREATED_ON,
               PDD.UPDATED_ON
        FROM Ahs_Altus_Prod.dbo.PATIENT_DETAILS AS PD
            INNER JOIN Ahs_Altus_Prod.dbo.[PATIENT_PREFERRED_ADDRESS] AS PDD
                ON PDD.PATIENT_ID = PD.PATIENT_ID
                   AND PDD.DELETED_ON IS NULL
    ) AS PREADD
        ON PREADD.MEMBER_ID = M.UHC_SUBSCRIBER_ID
UNION
/* get latest termed member data */
SELECT UTM.MEMBER_ID,
       'UHC' AS CLIENT_ID,
       UTM.MEDICAID_ID,
       REPLACE(RTRIM(UTM.MEMBER_FIRST_NAME), ',', ' ') AS MEMBER_FIRST_NAME,
       REPLACE(RTRIM(UTM.MEMBER_MI), ',', ' ') AS MEMBER_MI,
       REPLACE(RTRIM(UTM.MEMBER_LAST_NAME), ',', ' ') AS MEMBER_LAST_NAME,
       UTM.DATE_OF_BIRTH,
       UTM.GENDER AS MEMBER_GENDER,
       REPLACE(RTRIM(UTM.MEMBER_HOME_ADDRESS), ',', ' ') + ' ' + REPLACE(RTRIM(UTM.MEMBER_HOME_ADDRESS2), ',', ' ') AS HOME_ADDRESS,
       UTM.MEMBER_HOME_CITY AS HOME_CITY,
       UTM.MEMBER_HOME_STATE AS HOME_STATE,
       UTM.MEMBER_HOME_ZIP_C AS HOME_ZIPCODE,
       REPLACE(RTRIM(UTM.MEMBER_HOME_ADDRESS), ',', ' ') + ' ' + REPLACE(RTRIM(UTM.MEMBER_HOME_ADDRESS2), ',', ' ') AS MAILING_ADDRESS,
       UTM.MEMBER_HOME_CITY AS MAILING_CITY,
       UTM.MEMBER_HOME_STATE AS MAILING_STATE,
       UTM.MEMBER_HOME_ZIP_C AS MAILING_ZIP,
       UTM.MEMBER_HOME_PHONE AS HOME_PHONE,
       UTM.MEMBER_BUS_PHONE AS ADDITIONAL_PHONE,
       UTM.MEMBER_HOME_PHONE AS CELL_PHONE,
       ISNULL(NULL, 'TEST LANGUAGE') AS LANGUAGE,
       ISNULL(NULL, 'Test ETHNICITY') AS Ethnicity,
       UTM.Medicare_id,
       UTM.MEMBER_ORG_EFF_DATE,
       UTM.MEMBER_CONT_EFF_DATE,
       UTM.MEMBER_CUR_EFF_DATE,
       UTM.MEMBER_CUR_TERM_DATE,
       REPLACE(RTRIM(UTM.RESP_FIRST_NAME), ',', ' ') AS RESP_FIRST_NAME,
       REPLACE(RTRIM(UTM.RESP_LAST_NAME), ',', ' ') AS RESP_LAST_NAME,
       'Responsible Party' AS RESP_RELATIONSHIP, -- PlaceHolder for future data
       REPLACE(RTRIM(UTM.RESP_ADDRESS), ',', ' ') AS RESP_ADDRESS,
       REPLACE(RTRIM(UTM.RESP_ADDRESS2), ',', ' ') AS RESP_ADDRESS2,
       UTM.RESP_CITY,
       UTM.RESP_STATE,
       UTM.RESP_ZIP,
       UTM.RESP_PHONE,
       UPPER(REPLACE(RTRIM(UTM.PRIMARY_RISK_FACTOR), ',', ' ')) AS PRIMARY_RISK_FACTOR,
       UTM.COUNT_OPEN_CARE_OPPS,
       UTM.INP_ADMITS_LAST_12_MOS,
       UTM.LAST_INP_DISCHARGE,
       UTM.POST_DISCHARGE_FUP_VISIT,
       UTM.INP_FUP_WITHIN_7_DAYS,
       UTM.ER_VISITS_LAST_12_MOS,
       UTM.LAST_ER_VISIT,
       UTM.POST_ER_FUP_VISIT,
       UTM.ER_FUP_WITHIN_7_DAYS,
       UTM.LAST_PCP_VISIT,
       REPLACE(RTRIM(UTM.LAST_PCP_PRACTICE_SEEN), ',', ' ') AS LAST_PCP_PRACTICE_SEEN,
       UTM.LAST_BH_VISIT,
       REPLACE(RTRIM(UTM.LAST_BH_PRACTICE_SEEN), ',', ' ') AS LAST_BH_PRACTICE_SEEN,
       REPLACE(RTRIM(UTM.TOTAL_COSTS_LAST_12_MOS), ',', '') AS TOTAL_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.INP_COSTS_LAST_12_MOS), ',', '') AS INP_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.ER_COSTS_LAST_12_MOS), ',', '') AS ER_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.OUTP_COSTS_LAST_12_MOS), ',', '') AS OUTP_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.PHARMACY_COSTS_LAST_12_MOS), ',', '') AS PHARMACY_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.PRIMARY_CARE_COSTS_LAST_12_MOS), ',', '') AS PRIMARY_CARE_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.BEHAVIORAL_COSTS_LAST_12_MOS), ',', '') AS BEHAVIORAL_COSTS_LAST_12_MOS,
       REPLACE(RTRIM(UTM.OTHER_OFFICE_COSTS_LAST_12_MOS), ',', '') AS OTHER_OFFICE_COSTS_LAST_12_MOS,
       '12/12/2099' AS NEXT_PREVENTATIVE_VISIT_DUE,
       REPLACE(RTRIM(UTM.MEMBER_EMAIL), ',', ' ') AS EMAIL,
       ISNULL(NULL, 'TEST RACE') AS RACE
FROM dbo.vw_UHC_TermedMembers AS UTM;



