CREATE View dbo.vw_AH_CareTeamAssignment
AS
SELECT
    CONVERT(NVARCHAR(255), RTRIM(CLIENT_ID)) AS CLIENT_ID
    ,CONVERT(NVARCHAR(255), RTRIM(MEMBER_ID)) AS MEMBER_ID
    ,CONVERT(NVARCHAR(255), RTRIM(USERNAME)) AS USERNAME
    ,CONVERT(NVARCHAR(255), RTRIM(CARE_STAFF_ID)) AS CARE_STAFF_ID
    ,CONVERT(NVARCHAR(255), RTRIM(START_DATE)) AS START_DATE
    ,CONVERT(NVARCHAR(255), RTRIM(END_DATE)) AS END_DATE
FROM [CC].[dbo].[vw_AH_Care_Team_Assignment]
