
CREATE VIEW [dbo].[vw_Dashboard_BHVisitsfromUHCSummary]
AS
SELECT *
FROM (
	SELECT DISTINCT a.[UHC_SUBSCRIBER_ID]
		,a.[MEMBER_FIRST_NAME]
		,[MEMBER_MI]
		,a.[MEMBER_LAST_NAME]
		,b.LAST_BH_PRACTICE_SEEN
		,b.LAST_BH_VISIT
		,[CLASS]
		,[PLAN_ID]
		,[PRODUCT_CODE]
		,[SUBGRP_ID]
		,[SUBGRP_NAME]
		,CASE 
			WHEN AMT.DESTINATION_VALUE IN (
					'MMP'
					,'MMP NF'
					,'MMP  NF'
					,'MMP Waiver'
					)
				THEN 'MMP'
			WHEN AMT.DESTINATION_VALUE IN (
					'STARKIDS'
					,'STARKIDS IDD'
					)
				THEN 'STARKIDS'
			WHEN AMT.DESTINATION_VALUE IN (
					'STARPLUS IDD'
					,'STARPLUS NHC'
					,'STARPLUS NHR'
					,'TX-STAR+PLUS'
					,'TX STAR+PLUS 111'
					,'TX STAR+PLUS 120'
					,'TX STAR+PLUS 123'
					,'TX STAR+PLUS 901'
					)
				THEN 'STARPLUS'
			WHEN AMT.DESTINATION_VALUE IN (
					'TX-CHIP'
					,'TX-CHIP Pregnant Women'
					)
				THEN 'TX-CHIP'
			WHEN AMT.DESTINATION_VALUE IN (
					'TX-STAR'
					,'TX-STAR Pregnant Women'
					)
				THEN 'TX-STAR'
			END AS PLAN_NAME
		--,[MEDICARE_ID]	
		--,a.[MEDICAID_ID]	
		,[AGE]
		,a.[DATE_OF_BIRTH]
		,[GENDER]
		,[RELATIONSHIP_CODE]
		,[LANG_CODE]
		,[MEMBER_HOME_ADDRESS]
		,[MEMBER_HOME_ADDRESS2]
		,[MEMBER_HOME_CITY]
		,[MEMBER_HOME_STATE]
		,[MEMBER_HOME_ZIP]
		,[MEMBER_HOME_PHONE]
		,[MEMBER_MAIL_ADDRESS]
		,[MEMBER_MAIL_ADDRESS2]
		,[MEMBER_MAIL_CITY]
		,[MEMBER_MAIL_STATE]
		,[MEMBER_MAIL_ZIP]
		,[MEMBER_MAIL_PHONE]
		,[MEMBER_COUNTY_CODE]
		,a.[MEMBER_COUNTY]
		,[MEMBER_BUS_PHONE]
		,[DUAL_COV_FLAG]
		,[MEMBER_ORG_EFF_DATE]
		,[MEMBER_CONT_EFF_DATE]
		,[MEMBER_CUR_EFF_DATE]
		,[MEMBER_CUR_TERM_DATE]
		,[CLASS_PLAN_ID]
		--,[RESP_LAST_NAME]	
		--,[RESP_FIRST_NAME]	
		--,[RESP_ADDRESS]	
		--,[RESP_ADDRESS2]	
		--,[RESP_CITY]	
		--,[RESP_STATE]	
		--,[RESP_ZIP]	
		--,[RESP_PHONE]	
		--,[BROKER_ID]	
		--,[PCP_UHC_ID]	
		,[PCP_FIRST_NAME]
		,[PCP_LAST_NAME]
		,[PCP_MPIN]
		,[PCP_NPI]
		,[PCP_PROV_TYPE_ID]
		,[PCP_PROV_TYPE]
		,[PCP_INDICATOR]
		,[CMG]
		,[PCP_PHONE]
		,[PCP_FAX]
		,a.[PCP_ADDRESS]
		,[PCP_ADDRESS2]
		,a.[PCP_CITY]
		,a.[PCP_STATE]
		,a.[PCP_ZIP]
		,a.[PCP_COUNTY]
		,[PCP_EFFECTIVE_DATE]
		,[PCP_TERM_DATE]
		,a.[PCP_PRACTICE_TIN]
		,[PCP_GROUP_ID]
		,a.[PCP_PRACTICE_NAME]
		,[IND_PRACT_ID]
		,[IND_PRACT_NAME]
		,[RECERT_DATE]
		,[ETHNICITY]
		,[ETHNICITY_DESC]
		,[AUTO_ASSIGN]
		,[ASAP_ID]
		,[FEW_ID]
		,[LST_HRA_DATE]
		,[NXT_HRA_DATE]
		,[HRA_ID]
		,[MEMBER_EMAIL]
		,a.[A_LAST_UPDATE_DATE]
		,a.[A_LAST_UPDATE_BY]
		,a.[A_LAST_UPDATE_FLAG]
		,[MEMBER_STATUS]
		,[MEMBER_TERM_DATE]
		,[LoadType]
		,[PCP_Specialty_Code]
		,[PCP_Specialty]
		,[SrcFileName]
		,row_number() OVER (
			PARTITION BY a.UHC_SUBSCRIBER_ID ORDER BY a.A_LAST_UPDATE_DATE DESC
			) AS arn
	FROM [ACECAREDW].[dbo].[Uhc_MembersByPcp] a
	LEFT JOIN [ACECAREDW].[dbo].[Uhc_Membership] b ON a.UHC_SUBSCRIBER_ID = b.UHC_SUBSCRIBER_ID
		AND YEAR(a.A_LAST_UPDATE_DATE) > 2017
	LEFT JOIN ACECAREDW.DBO.ALT_MAPPING_TABLES AMT ON AMT.SOURCE_VALUE = a.SUBGRP_ID
	WHERE b.LAST_BH_VISIT <> ''
		AND b.LAST_BH_VISIT IS NOT NULL
		AND year(b.LAST_BH_VISIT) > 2017
		-- and a.UHC_SUBSCRIBER_ID ='100538882'	
		AND a.LoadType = 'P'
	) r
WHERE r.arn = 1
