



CREATE view [dbo].[vw_Exp_AH_Membership_DEV]
AS    
     select CONVERT(NVARCHAR(255), RTRIM(m.ClientMemberKey)) AS Member_ID											
     , m.Exp_CLIENT_ID as CLIENT_ID																	
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEDICAID_ID )) AS MEDICAID_ID											
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_FIRST_NAME)) AS MEMBER_FIRST_NAME									 
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_MI)) AS MEMBER_MI												 
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_LAST_NAME)) AS MEMBER_LAST_NAME									 
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_DATE_OF_BIRTH)) AS DATE_OF_BIRTH										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_GENDER)) AS MEMBER_GENDER										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_ADDRESS)) AS HOME_ADDRESS										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_CITY)) AS HOME_CITY											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_STATE)) AS HOME_STATE											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_ZIPCODE)) AS HOME_ZIPCODE										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_ADDRESS)) AS MAILING_ADDRESS									
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_CITY)) AS MAILING_CITY										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_STATE)) AS MAILING_STATE										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_ZIP)) AS MAILING_ZIP										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_PHONE)) AS HOME_PHONE											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_ADDITIONAL_PHONE)) AS ADDITIONAL_PHONE								 
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_CELL_PHONE)) AS CELL_PHONE											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_Language)) AS Language												
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_Ethnicity)) AS Ethnicity											
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.EXP_Race))) AS Race													
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.EXP_Email))) AS Email												
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEDICARE_ID)) AS MEDICARE_ID											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_ORG_EFF_DATE)) AS MEMBER_ORG_EFF_DATE								
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_CONT_EFF_DATE)) AS MEMBER_CONT_EFF_DATE								 
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_CUR_EFF_DATE)) AS MEMBER_CUR_EFF_DATE								
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_CUR_TERM_DATE)) AS MEMBER_CUR_TERM_DATE								 
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_FIRST_NAME)) AS RESP_FIRST_NAME										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_LAST_NAME)) AS RESP_LAST_NAME										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_RELATIONSHIP)) AS RESP_RELATIONSHIP									
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_ADDRESS)) AS RESP_ADDRESS											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_ADDRESS2)) AS RESP_ADDRESS2										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_CITY)) AS RESP_CITY											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_STATE)) AS RESP_STATE											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_ZIP)) AS RESP_ZIP												
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_RESP_PHONE)) AS RESP_PHONE											
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_PRIMARY_RISK_FACTOR)) AS PRIMARY_RISK_FACTOR							
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_COUNT_OPEN_CARE_OPPS)) AS COUNT_OPEN_CARE_OPPS							
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_INP_ADMITS_LAST_12_MOS)) AS INP_ADMITS_LAST_12_MOS						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_LAST_INP_DISCHARGE)) AS LAST_INP_DISCHARGE								
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_POST_DISCHARGE_FUP_VISIT)) AS POST_DISCHARGE_FUP_VISIT					
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_INP_FUP_WITHIN_7_DAYS)) AS INP_FUP_WITHIN_7_DAYS						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_ER_VISITS_LAST_12_MOS)) AS ER_VISITS_LAST_12_MOS						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_LAST_ER_VISIT)) AS LAST_ER_VISIT										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_POST_ER_FUP_VISIT)) AS POST_ER_FUP_VISIT								
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_ER_FUP_WITHIN_7_DAYS)) AS ER_FUP_WITHIN_7_DAYS							
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_LAST_PCP_VISIT)) AS LAST_PCP_VISIT									
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_LAST_PCP_PRACTICE_SEEN)) AS LAST_PCP_PRACTICE_SEEN						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_LAST_BH_VISIT)) AS LAST_BH_VISIT										
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_LAST_BH_PRACTICE_SEEN)) AS LAST_BH_PRACTICE_SEEN						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_TOTAL_COSTS_LAST_12_MOS)) AS TOTAL_COSTS_LAST_12_MOS						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_INP_COSTS_LAST_12_MOS)) AS INP_COSTS_LAST_12_MOS						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_ER_COSTS_LAST_12_MOS)) AS ER_COSTS_LAST_12_MOS							
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_OUTP_COSTS_LAST_12_MOS)) AS OUTP_COSTS_LAST_12_MOS						
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_PHARMACY_COSTS_LAST_12_MOS)) AS PHARMACY_COSTS_LAST_12_MOS				
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_PRIMARY_CARE_COSTS_LAST_12_MOS)) AS PRIMARY_CARE_COSTS_LAST_12_MOS			
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_BEHAVIORAL_COSTS_LAST_12_MOS)) AS BEHAVIORAL_COSTS_LAST_12_MOS				
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_OTHER_OFFICE_COSTS_LAST_12_MOS)) AS OTHER_OFFICE_COSTS_LAST_12_MOS			
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_NEXT_PREVENTATIVE_VISIT_DUE)) AS NEXT_PREVENTATIVE_VISIT_DUE				
    , m.exp_ACE_ID  AS Ace_id																				
    , m.exp_carrier_Member_ID As carrier_Member_ID     																
    , m.ClientKey																					
FROM ACDW_CLMS_SHCN_MSSP.dbo.vw_EXP_AH_Membership m   
UNION 
SELECT  -- BCBS
       CONVERT(NVARCHAR(255), RTRIM(m.ClientMemberKey)) AS Member_ID
     , m.Exp_CLIENT_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEDICAID_ID)) AS MEDICAID_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_FIRST_NAME)) AS MEMBER_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_MI)) AS MEMBER_MI
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_LAST_NAME)) AS MEMBER_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_DATE_OF_BIRTH)) AS DATE_OF_BIRTH
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_GENDER)) AS MEMBER_GENDER
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_HOME_ADDRESS)) AS HOME_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_HOME_CITY)) AS HOME_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_HOME_STATE)) AS HOME_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_HOME_ZIPCODE)) AS HOME_ZIPCODE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MAILING_ADDRESS)) AS MAILING_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MAILING_CITY)) AS MAILING_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MAILING_STATE)) AS MAILING_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MAILING_ZIP)) AS MAILING_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_HOME_PHONE)) AS HOME_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ADDITIONAL_PHONE)) AS ADDITIONAL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_CELL_PHONE)) AS CELL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_Language)) AS Language
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_Ethnicity)) AS Ethnicity
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.EXP_Race))) AS Race
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.EXP_Email))) AS Email
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEDICARE_ID)) AS MEDICARE_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_ORG_EFF_DATE)) AS MEMBER_ORG_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_CONT_EFF_DATE)) AS MEMBER_CONT_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_CUR_EFF_DATE)) AS MEMBER_CUR_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_CUR_TERM_DATE)) AS MEMBER_CUR_TERM_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_FIRST_NAME)) AS RESP_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_LAST_NAME)) AS RESP_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_RELATIONSHIP)) AS RESP_RELATIONSHIP
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_ADDRESS)) AS RESP_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_ADDRESS2)) AS RESP_ADDRESS2
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_CITY)) AS RESP_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_STATE)) AS RESP_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_ZIP)) AS RESP_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_PHONE)) AS RESP_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_PRIMARY_RISK_FACTOR)) AS PRIMARY_RISK_FACTOR
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_COUNT_OPEN_CARE_OPPS)) AS COUNT_OPEN_CARE_OPPS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_INP_ADMITS_LAST_12_MOS)) AS INP_ADMITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_INP_DISCHARGE)) AS LAST_INP_DISCHARGE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_POST_DISCHARGE_FUP_VISIT)) AS POST_DISCHARGE_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_INP_FUP_WITHIN_7_DAYS)) AS INP_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ER_VISITS_LAST_12_MOS)) AS ER_VISITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_ER_VISIT)) AS LAST_ER_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_POST_ER_FUP_VISIT)) AS POST_ER_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ER_FUP_WITHIN_7_DAYS)) AS ER_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_PCP_VISIT)) AS LAST_PCP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_PCP_PRACTICE_SEEN)) AS LAST_PCP_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_BH_VISIT)) AS LAST_BH_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_BH_PRACTICE_SEEN)) AS LAST_BH_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_TOTAL_COSTS_LAST_12_MOS)) AS TOTAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_INP_COSTS_LAST_12_MOS)) AS INP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ER_COSTS_LAST_12_MOS)) AS ER_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_OUTP_COSTS_LAST_12_MOS)) AS OUTP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_PHARMACY_COSTS_LAST_12_MOS)) AS PHARMACY_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_PRIMARY_CARE_COSTS_LAST_12_MOS)) AS PRIMARY_CARE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_BEHAVIORAL_COSTS_LAST_12_MOS)) AS BEHAVIORAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_OTHER_OFFICE_COSTS_LAST_12_MOS)) AS OTHER_OFFICE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_NEXT_PREVENTATIVE_VISIT_DUE)) AS NEXT_PREVENTATIVE_VISIT_DUE
    , m.EXP_ACE_ID  
    , m.EXP_carrier_Member_ID 
    , m.ClientKey
FROM ACDW_CLMS_SHCN_BCBS.dbo.vw_EXP_AH_Membership m
UNION 
SELECT  -- ACDW_CLMS_AMGTX_MA
       CONVERT(NVARCHAR(255), RTRIM(m.ClientMemberKey)) AS Member_ID
     , m.EXP_CLIENT_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEDICAID_ID)) AS MEDICAID_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_FIRST_NAME)) AS MEMBER_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_MI)) AS MEMBER_MI
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_LAST_NAME)) AS MEMBER_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_DATE_OF_BIRTH)) AS DATE_OF_BIRTH
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_GENDER)) AS MEMBER_GENDER
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_ADDRESS)) AS HOME_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_CITY)) AS HOME_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_STATE)) AS HOME_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_ZIPCODE)) AS HOME_ZIPCODE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_ADDRESS)) AS MAILING_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_CITY)) AS MAILING_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_STATE)) AS MAILING_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_ZIP)) AS MAILING_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_PHONE)) AS HOME_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ADDITIONAL_PHONE)) AS ADDITIONAL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_CELL_PHONE)) AS CELL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_Language)) AS Language
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_Ethnicity)) AS Ethnicity
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.Exp_Race))) AS Race
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.Exp_Email))) AS Email
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEDICARE_ID)) AS MEDICARE_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_ORG_EFF_DATE)) AS MEMBER_ORG_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_CONT_EFF_DATE)) AS MEMBER_CONT_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_CUR_EFF_DATE)) AS MEMBER_CUR_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_CUR_TERM_DATE)) AS MEMBER_CUR_TERM_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_FIRST_NAME)) AS RESP_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_LAST_NAME)) AS RESP_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_RELATIONSHIP)) AS RESP_RELATIONSHIP
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_ADDRESS)) AS RESP_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_ADDRESS2)) AS RESP_ADDRESS2
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_CITY)) AS RESP_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_STATE)) AS RESP_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_ZIP)) AS RESP_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_PHONE)) AS RESP_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_PRIMARY_RISK_FACTOR)) AS PRIMARY_RISK_FACTOR
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_COUNT_OPEN_CARE_OPPS)) AS COUNT_OPEN_CARE_OPPS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_INP_ADMITS_LAST_12_MOS)) AS INP_ADMITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_INP_DISCHARGE)) AS LAST_INP_DISCHARGE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_POST_DISCHARGE_FUP_VISIT)) AS POST_DISCHARGE_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_INP_FUP_WITHIN_7_DAYS)) AS INP_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ER_VISITS_LAST_12_MOS)) AS ER_VISITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_ER_VISIT)) AS LAST_ER_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_POST_ER_FUP_VISIT)) AS POST_ER_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ER_FUP_WITHIN_7_DAYS)) AS ER_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_PCP_VISIT)) AS LAST_PCP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_PCP_PRACTICE_SEEN)) AS LAST_PCP_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_BH_VISIT)) AS LAST_BH_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_BH_PRACTICE_SEEN)) AS LAST_BH_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_TOTAL_COSTS_LAST_12_MOS)) AS TOTAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_INP_COSTS_LAST_12_MOS)) AS INP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ER_COSTS_LAST_12_MOS)) AS ER_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_OUTP_COSTS_LAST_12_MOS)) AS OUTP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_PHARMACY_COSTS_LAST_12_MOS)) AS PHARMACY_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_PRIMARY_CARE_COSTS_LAST_12_MOS)) AS PRIMARY_CARE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_BEHAVIORAL_COSTS_LAST_12_MOS)) AS BEHAVIORAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_OTHER_OFFICE_COSTS_LAST_12_MOS)) AS OTHER_OFFICE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_NEXT_PREVENTATIVE_VISIT_DUE)) AS NEXT_PREVENTATIVE_VISIT_DUE
    , m.Exp_ACE_ID  
    , m.Exp_carrier_Member_ID 
    , m.ClientKey
--select top 10 *
FROM ACDW_CLMS_AMGTX_MA.dbo.vw_EXP_AH_Membership m
UNION 
SELECT  -- ACDW_CLMS_AMGTX_MCD
       CONVERT(NVARCHAR(255), RTRIM(m.ClientMemberKey)) AS Member_ID
     , m.Exp_CLIENT_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEDICAID_ID)) AS MEDICAID_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_FIRST_NAME)) AS MEMBER_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_MI)) AS MEMBER_MI
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_LAST_NAME)) AS MEMBER_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_DATE_OF_BIRTH)) AS DATE_OF_BIRTH
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_GENDER)) AS MEMBER_GENDER
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_ADDRESS)) AS HOME_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_CITY)) AS HOME_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_STATE)) AS HOME_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_ZIPCODE)) AS HOME_ZIPCODE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_ADDRESS)) AS MAILING_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_CITY)) AS MAILING_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_STATE)) AS MAILING_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MAILING_ZIP)) AS MAILING_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_HOME_PHONE)) AS HOME_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ADDITIONAL_PHONE)) AS ADDITIONAL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_CELL_PHONE)) AS CELL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_Language)) AS Language
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_Ethnicity)) AS Ethnicity
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.Exp_Race))) AS Race
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.Exp_Email))) AS Email
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEDICARE_ID)) AS MEDICARE_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_ORG_EFF_DATE)) AS MEMBER_ORG_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_CONT_EFF_DATE)) AS MEMBER_CONT_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_CUR_EFF_DATE)) AS MEMBER_CUR_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_MEMBER_CUR_TERM_DATE)) AS MEMBER_CUR_TERM_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_FIRST_NAME)) AS RESP_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_LAST_NAME)) AS RESP_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_RELATIONSHIP)) AS RESP_RELATIONSHIP
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_ADDRESS)) AS RESP_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_ADDRESS2)) AS RESP_ADDRESS2
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_CITY)) AS RESP_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_STATE)) AS RESP_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_ZIP)) AS RESP_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_RESP_PHONE)) AS RESP_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_PRIMARY_RISK_FACTOR)) AS PRIMARY_RISK_FACTOR
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_COUNT_OPEN_CARE_OPPS)) AS COUNT_OPEN_CARE_OPPS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_INP_ADMITS_LAST_12_MOS)) AS INP_ADMITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_INP_DISCHARGE)) AS LAST_INP_DISCHARGE
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_POST_DISCHARGE_FUP_VISIT)) AS POST_DISCHARGE_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_INP_FUP_WITHIN_7_DAYS)) AS INP_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ER_VISITS_LAST_12_MOS)) AS ER_VISITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_ER_VISIT)) AS LAST_ER_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_POST_ER_FUP_VISIT)) AS POST_ER_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ER_FUP_WITHIN_7_DAYS)) AS ER_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_PCP_VISIT)) AS LAST_PCP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_PCP_PRACTICE_SEEN)) AS LAST_PCP_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_BH_VISIT)) AS LAST_BH_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_LAST_BH_PRACTICE_SEEN)) AS LAST_BH_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_TOTAL_COSTS_LAST_12_MOS)) AS TOTAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_INP_COSTS_LAST_12_MOS)) AS INP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_ER_COSTS_LAST_12_MOS)) AS ER_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_OUTP_COSTS_LAST_12_MOS)) AS OUTP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_PHARMACY_COSTS_LAST_12_MOS)) AS PHARMACY_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_PRIMARY_CARE_COSTS_LAST_12_MOS)) AS PRIMARY_CARE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_BEHAVIORAL_COSTS_LAST_12_MOS)) AS BEHAVIORAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_OTHER_OFFICE_COSTS_LAST_12_MOS)) AS OTHER_OFFICE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.Exp_NEXT_PREVENTATIVE_VISIT_DUE)) AS NEXT_PREVENTATIVE_VISIT_DUE
    , m.Exp_ACE_ID  
    , m.Exp_carrier_Member_ID 
    , m.ClientKey
FROM ACDW_CLMS_AMGTX_MCD.dbo.vw_EXP_AH_Membership m   
UNION
SELECT top 1  -- ACECAREDW  members
       CONVERT(NVARCHAR(255), RTRIM(m.ClientMemberKey)) AS Member_ID
     , m.Exp_CLIENT_ID as CLIENT_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEDICAID_ID)) AS MEDICAID_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_FIRST_NAME)) AS MEMBER_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_MI)) AS MEMBER_MI
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_LAST_NAME)) AS MEMBER_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_DATE_OF_BIRTH)) AS DATE_OF_BIRTH
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MEMBER_GENDER)) AS MEMBER_GENDER
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_ADDRESS)) AS HOME_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_CITY)) AS HOME_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_STATE)) AS HOME_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_ZIPCODE)) AS HOME_ZIPCODE
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_ADDRESS)) AS MAILING_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_CITY)) AS MAILING_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_STATE)) AS MAILING_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_MAILING_ZIP)) AS MAILING_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_HOME_PHONE)) AS HOME_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_ADDITIONAL_PHONE)) AS ADDITIONAL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_CELL_PHONE)) AS CELL_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_Language)) AS Language
     , CONVERT(NVARCHAR(255), RTRIM(m.exp_Ethnicity)) AS Ethnicity
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.exp_Race))) AS Race
	, CONVERT(NVARCHAR(255), RTRIM(LTRIM(m.exp_Email))) AS Email
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEDICARE_ID)) AS MEDICARE_ID
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_ORG_EFF_DATE)) AS MEMBER_ORG_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_CONT_EFF_DATE)) AS MEMBER_CONT_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_CUR_EFF_DATE)) AS MEMBER_CUR_EFF_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_MEMBER_CUR_TERM_DATE)) AS MEMBER_CUR_TERM_DATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_FIRST_NAME)) AS RESP_FIRST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_LAST_NAME)) AS RESP_LAST_NAME
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_RELATIONSHIP)) AS RESP_RELATIONSHIP
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_ADDRESS)) AS RESP_ADDRESS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_ADDRESS2)) AS RESP_ADDRESS2
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_CITY)) AS RESP_CITY
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_STATE)) AS RESP_STATE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_ZIP)) AS RESP_ZIP
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_RESP_PHONE)) AS RESP_PHONE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_PRIMARY_RISK_FACTOR)) AS PRIMARY_RISK_FACTOR
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_COUNT_OPEN_CARE_OPPS)) AS COUNT_OPEN_CARE_OPPS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_INP_ADMITS_LAST_12_MOS)) AS INP_ADMITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_INP_DISCHARGE)) AS LAST_INP_DISCHARGE
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_POST_DISCHARGE_FUP_VISIT)) AS POST_DISCHARGE_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_INP_FUP_WITHIN_7_DAYS)) AS INP_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ER_VISITS_LAST_12_MOS)) AS ER_VISITS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_ER_VISIT)) AS LAST_ER_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_POST_ER_FUP_VISIT)) AS POST_ER_FUP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ER_FUP_WITHIN_7_DAYS)) AS ER_FUP_WITHIN_7_DAYS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_PCP_VISIT)) AS LAST_PCP_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_PCP_PRACTICE_SEEN)) AS LAST_PCP_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_BH_VISIT)) AS LAST_BH_VISIT
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_LAST_BH_PRACTICE_SEEN)) AS LAST_BH_PRACTICE_SEEN
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_TOTAL_COSTS_LAST_12_MOS)) AS TOTAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_INP_COSTS_LAST_12_MOS)) AS INP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_ER_COSTS_LAST_12_MOS)) AS ER_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_OUTP_COSTS_LAST_12_MOS)) AS OUTP_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_PHARMACY_COSTS_LAST_12_MOS)) AS PHARMACY_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_PRIMARY_CARE_COSTS_LAST_12_MOS)) AS PRIMARY_CARE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_BEHAVIORAL_COSTS_LAST_12_MOS)) AS BEHAVIORAL_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_OTHER_OFFICE_COSTS_LAST_12_MOS)) AS OTHER_OFFICE_COSTS_LAST_12_MOS
     , CONVERT(NVARCHAR(255), RTRIM(m.EXP_NEXT_PREVENTATIVE_VISIT_DUE)) AS NEXT_PREVENTATIVE_VISIT_DUE
    , m.Exp_ACE_ID  
    , m.exp_carrier_Member_ID 
    , m.ClientKey
FROM ACECAREDW.adw.AhsExpMembership m
WHERE m.Exported = 0


