CREATE VIEW vw_MbrLstNPI AS
SELECT src.UHC_SUBSCRIBER_ID,
       src.PCP_NPI,
       src.A_LAST_UPDATE_DATE       
FROM (SELECT m.UHC_SUBSCRIBER_ID, m.PCP_NPI, m.A_LAST_UPDATE_DATE
          , ROW_NUMBER() OVER(PARTITION BY m.UHC_SUBSCRIBER_ID ORDER BY m.A_LAST_UPDATE_DATE DESC) arn
          FROM dbo.UHC_MembersByPCP m 
    ) src
WHERE src.arn = 1
