create view vw_member_trend
as
SELECT DISTINCT [UHC_SUBSCRIBER_ID] ,MONTH([A_LAST_UPDATE_DATE]) AS MBR_MTH ,YEAR([A_LAST_UPDATE_DATE]) AS MBR_YEAR--, PCP_NPI, PCP_LAST_NAME, PCP_PRACTICE_TIN, PCP_PRACTICE_NAME 
      --,[MEMBER_STATUS]
  FROM [ACECAREDW].[dbo].[UHC_MembersByPCP]
