

-----------------------------
/****ACTIVE MEMBERS FOR AET AND WELLCARE from VW_ACTIVEMEMBERS*****/
CREATE VIEW [dbo].[vw_RP_AET+WLC_ACTIVE_MBRS]
AS
SELECT distinct
      [MEMBER_ID]
	  ,case when [CLIENT] = 'AET' then 'AET-MA' else 'WellCare' end as Client
     -- ,[MEMBER_FIRST_NAME]
      --,[MEMBER_MI]
      --,[MEMBER_LAST_NAME]
      --,[CLIENT_SUBSCRIBER_ID]
      --,[PLAN_ID]
      --,[PRODUCT_CODE]
      --,[SUBGRP_ID]
      --,[SUBGRP_NAME]
      --,[MEDICAID_ID]
      --,[AGE]
      --,[DATE_OF_BIRTH]
      --,[GENDER]
      --,[LANG_CODE]
      --,[ETHNICITY]
      --,[RACE]
      --,[MEMBER_HOME_ADDRESS]
      --,[MEMBER_HOME_ADDRESS2]
      --,[MEMBER_HOME_CITY]
      --,[MEMBER_HOME_STATE]
      --,[MEMBER_HOME_ZIP_C]
      --,[MEMBER_HOME_PHONE]
      --,[MEMBER_MAIL_ADDRESS]
      --,[MEMBER_MAIL_ADDRESS2]
      --,[MEMBER_MAIL_CITY]
      --,[MEMBER_MAIL_STATE]
      --,[MEMBER_MAIL_ZIP_C]
      --,[MEMBER_MAIL_PHONE]
      --,[MEMBER_COUNTY]
      --,[MEMBER_BUS_PHONE]
      --,[MEMBER_ORG_EFF_DATE]
      --,[MEMBER_CONT_EFF_DATE]
      --,[MEMBER_CUR_EFF_DATE]
      --,[MEMBER_CUR_TERM_DATE]
      --,[PCP_CLIENT_ID]
      --,[PCP_FIRST_NAME]
      --,[PCP_LAST_NAME]
      --,[NPI]
      --,[PCP_PHONE]
      --,[PCP_FAX]
      --,[PCP_ADDRESS]
      --,[PCP_ADDRESS2]
      --,[PCP_CITY]
      --,[PCP_STATE]
      --,[PCP_ZIP_C]
      --,[PCP_EFFECTIVE_DATE]
      --,[PCP_TERM_DATE]
      --,[PCP_PRACTICE_TIN]
      --,[PCP_GROUP_ID]
      --,[PCP_PRACTICE_NAME]
      --,[AUTO_ASSIGN]
      --,[MEMBER_STATUS]
      --,[MEMBER_TERM_DATE]
      --,[IPRO_ADMIT_RISK_SCORE]
      --,[RISK_CATEGORY_C]
      --,[LINE_OF_BUSINESS]
      --,[PLAN_CODE]
      --,[PLAN_DESC]
      --,[PRIMARY_RISK_FACTOR]
      --,[TOTAL_COSTS_LAST_12_MOS]
      --,[COUNT_OPEN_CARE_OPPS]
      --,[INP_COSTS_LAST_12_MOS]
      --,[ER_COSTS_LAST_12_MOS]
      --,[OUTP_COSTS_LAST_12_MOS]
      --,[PHARMACY_COSTS_LAST_12_MOS]
      --,[PRIMARY_CARE_COSTS_LAST_12_MOS]
      --,[BEHAVIORAL_COSTS_LAST_12_MOS]
      --,[OTHER_OFFICE_COSTS_LAST_12_MOS]
      --,[INP_ADMITS_LAST_12_MOS]
      --,[LAST_INP_DISCHARGE]
      --,[POST_DISCHARGE_FUP_VISIT]
      --,[INP_FUP_WITHIN_7_DAYS]
      --,[ER_VISITS_LAST_12_MOS]
      --,[LAST_ER_VISIT]
      --,[POST_ER_FUP_VISIT]
      --,[ER_FUP_WITHIN_7_DAYS]
      --,[LAST_PCP_VISIT]
      --,[LAST_PCP_PRACTICE_SEEN]
      --,[LAST_BH_VISIT]
      --,[LAST_BH_PRACTICE_SEEN]
      --,[MEMBER_MONTH_COUNT]
      --,[MEMBER_POD_C]
      --,[MEMBER_POD_DESC]
      --,[PCP_POD_C]
      --,[PCP_POD_DESC]
      --,[PCP_NAME]
      --,[CLIENT_UNIQUE_SYSTEM_ID]
      --,[MEDICARE_ID]
      --,[RESP_LAST_NAME]
      --,[RESP_FIRST_NAME]
      --,[RESP_ADDRESS]
      --,[RESP_ADDRESS2]
      --,[RESP_CITY]
      --,[RESP_STATE]
      --,[RESP_ZIP]
      --,[RESP_PHONE]
  FROM [ACECAREDW].[dbo].[vw_ActiveMembers]
  where client in ('AET', 'WLC')

