

/****** Script for SelectTopNRows command from SSMS  ******/

CREATE VIEW [dbo].[vw_RP_NewMemberPodAddress]
As
SELECT DISTINCT P.[CLIENT_PATIENT_ID]--,PD.PATIENT_ID
,CONCAT(PD.FIRST_NAME,' ', PD.LAST_NAME) as MEMBER_NAME
      ,P.[PROGRAM_NAME]
      ,P.[START_DATE]
      ,P.END_DATE
      ,P.[PROGRAM_STATUS_NAME]
	 , UPPER(PPC.FIRST_NAME)+' '+UPPER(PPC.LAST_NAME) AS RESP_PARTY
	 ,PDD.ADDRESS_TEXT AS HOME_ADDRESS
	 ,PDD.CITY AS HOME_CITY
	 ,PDD.STATE AS HOME_STATE
	 ,PDD.ZIP AS HOME_ZIP
	 ,CASE WHEN POD.Quadrant__c IS NULL THEN 6 ELSE POD.Quadrant__c END AS HOME_POD
	  ,CASE WHEN PPA.PATIENT_ID IS NULL THEN PDD1.ADDRESS_TEXT ELSE PPA.ADDRESS_TEXT END  AS MAIL_ADDRESS
	 ,CASE WHEN PPA.PATIENT_ID IS NULL THEN PDD1.CITY ELSE PPA.CITY END AS MAIL_CITY
	 ,CASE WHEN PPA.PATIENT_ID IS NULL THEN PDD1.STATE ELSE PPA.STATE END AS MAIL_STATE
	 ,CASE WHEN PPA.PATIENT_ID IS NULL THEN PDD1.ZIP ELSE  PPA.ZIP END AS MAIL_ZIP
	 ,CASE WHEN PPA.PATIENT_ID IS NULL THEN POD1.Quadrant__c ELSE POD2.Quadrant__c END AS MAIL_POD
	 ,UPPER(CONCAT(CSD.FIRST_NAME ,' ',csd.LAST_NAME)) AS PREFERRED_ADDRESS_CREATED_BY
  FROM [Ahs_Altus_Prod].[dbo].[vw_ACE_ALT_PE] P
  INNER JOIN [Ahs_Altus_Prod].[dbo].PATIENT_DETAILS PD ON PD.CLIENT_PATIENT_ID=P.CLIENT_PATIENT_ID
          LEFT JOIN [Ahs_Altus_Prod].dbo.PATIENT_PRIMARY_CAREGIVER AS PPC ON PPC.PATIENT_ID = PD.PATIENT_ID --AND PPC.PATIENT_ID IS NOT NULL
                                                            AND DATEDIFF(DD, PD.BIRTH_YEAR, GETDATE()) / 365 < 18 AND  PPC.PATIENT_RELATION_ID=14
         LEFT JOIN [Ahs_Altus_Prod].dbo.PATIENT_RELATION AS PR ON PR.PATIENT_RELATION_ID = PPC.PATIENT_RELATION_ID --AND PPC.PATIENT_RELATION_ID=14
		--LEFT join Ahs_Altus_Prod.dbo.CARE_STAFF_DETAILS csd on csd.member_id=ppc.CREATED_BY
		 LEFT JOIN [Ahs_Altus_Prod].dbo.PATIENT_ADDITIONAL_ADDRESS AS PDD ON PDD.PATIENT_ID = PD.PATIENT_ID
                                                              AND PDD.ADDRESS_TYPE_ID=33
		   LEFT JOIN [Ahs_Altus_Prod].dbo.PATIENT_ADDITIONAL_ADDRESS AS PDD1 ON PDD1.PATIENT_ID = PD.PATIENT_ID
                                                              AND PDD1.ADDRESS_TYPE_ID=34
	  LEFT JOIN [Ahs_Altus_Prod].dbo.PATIENT_PREFERRED_ADDRESS AS PPA ON PPA.PATIENT_ID = PD.PATIENT_ID
                                                              AND PPA.DELETED_BY IS NULL
		LEFT JOIN [Ahs_Altus_Prod].dbo.CARE_STAFF_DETAILS CSD ON CSD.MEMBER_ID=PPA.CREATED_BY
		 LEFT JOIN ACECAREDW.DBO.tmpSalesforce_Zip_Code__c POD ON CONVERT(INT,ltrim(rtrim(POD.name)))=CONVERT(INT,left(PD.ZIP,5)) and POD.Name not in ('3911?','Zip')
		  LEFT JOIN ACECAREDW.DBO.tmpSalesforce_Zip_Code__c POD1 ON CONVERT(INT,ltrim(rtrim(POD1.name)))=CONVERT(INT,left(PDD1.ZIP,5)) and POD1.Name not in ('3911?','Zip')
		  LEFT JOIN ACECAREDW.DBO.tmpSalesforce_Zip_Code__c POD2 ON CONVERT(INT,ltrim(rtrim(POD2.name)))=CONVERT(INT,left(ppa.ZIP,5))and POD2.Name not in ('3911?','Zip')
 WHERE P.PROGRAM_NAME='Newly Enrolled' AND P.CLIENT_PATIENT_ID NOT LIKE 'ALT%' AND P.[plan_end_date]='12/31/2099' --AND P.CLIENT_PATIENT_ID='114382987'



