
create VIEW [dbo].[vw_RP_ActiveMembershipByTIN] AS 
sELECT UPPER(ACCOUNTNAME) AS PRACTICE_NAME
      ,[PCP_PRACTICE_TIN] AS PRACTICE_TIN
	 ,PCP_ADDRESS
	,COUNT(UHC_SUBSCRIBER_ID) AS TOTAL_MEMBERS FROM (
SELECT DISTINCT AC.UHC_SUBSCRIBER_ID
      ,AC.[PCP_PRACTICE_TIN]
      ,AC.[PCP_PRACTICE_NAME]
	 ,TA.NAME AS ACCOUNTNAME
	 ,AC.PCP_ADDRESS
	 ,AC.PCP_CITY
	 ,AC.PCP_STATE
	 ,AC.PCP_ZIP_c
	 ,AC.[PCP_POD_C]
      ,AC.[PCP_POD_DESC]
    
  FROM [ACECAREDW].[dbo].[vw_UHC_ActiveMembers] AC
  INNER JOIN tmpSalesforce_Account TA ON CONVERT(INT,TA.Tax_ID_Number__c)=CONVERT(INT,AC.[PCP_PRACTICE_TIN])) AS S
  GROUP BY
  ACCOUNTNAME,
  [PCP_PRACTICE_TIN]
      ,[PCP_PRACTICE_NAME]
	 ,PCP_ADDRESS
