
CREATE VIEW [dbo].[vw_RP_TOC4_PCP_POD]
AS
select MEMBER_ID, 
MEMBER_FIRST_NAME,
MEMBER_MI,
MEMBER_LAST_NAME,
PRIMARY_RISK_FACTOR,
RISK_CATEGORY_C,
IPRO_ADMIT_RISK_SCORE,
TOTAL_COSTS_LAST_12_MOS,
COUNT_OPEN_CARE_OPPS AS OPEN_CARE_GAPS,
INP_COSTS_LAST_12_MOS,
ER_COSTS_LAST_12_MOS,
OUTP_COSTS_LAST_12_MOS,
PHARMACY_COSTS_LAST_12_MOS,
PRIMARY_CARE_COSTS_LAST_12_MOS,
BEHAVIORAL_COSTS_LAST_12_MOS,
OTHER_OFFICE_COSTS_LAST_12_MOS,
INP_ADMITS_LAST_12_MOS,
LAST_INP_DISCHARGE,
ER_VISITS_LAST_12_MOS,
LAST_ER_VISIT,
LAST_PCP_VISIT,
PCP_PRACTICE_NAME,
PCP_NAME,
PCP_POD_C,
PCP_POD_DESC,
PCP_PRACTICE_TIN
 from acecaredw.dbo.vw_UHC_Activemembers where 
member_id  in (SELECT distinct MEMBER_ID
 FROM CC.[dbo].[P14]
where create_date='2017-08-07')

