CREATE view [dbo].[vw_test_memb_sum]
as 
SELECT  PCP_PRACTICE_TIN,PCP_GROUP_ID,PCP_PRACTICE_NAME,DENSE_RANK ( )OVER( ORDER BY A_LAST_UPDATE_DATE ASC)  as date_order , PRODUCT_CODE, UHC_SUBSCRIBER_ID, A_LAST_UPDATE_DATE, MONTH(A_LAST_UPDATE_DATE) AS MBR_MTH
FROM            dbo.UHC_MembersByPCP
