CREATE VIEW vw_UHC_Dashboard_MbrPCPMap
AS
SELECT 
      A.[UHC_SUBSCRIBER_ID]
	  ,A.[MEMBER_HOME_ZIP]
      ,LEFT(A.[MEMBER_HOME_ZIP],5) AS MEMBER_ZIP
      ,LEFT(A.[PCP_ZIP],5) AS [PCP_ZIP]
	  ,A.PCP_NPI
	  ,B.[SERVICE ZIPCODE] AS ACE_PROVIDER_ZIP
  --,COUNT(DISTINCT [UHC_SUBSCRIBER_ID]) AS CNT
 FROM [ACECAREDW].[dbo].[UHC_MembersByPCP] A
 FULL JOIN [ACECAREDW].[dbo].[vw_UHC_ProviderRoster] B ON A.PCP_NPI = B.NPI
 WHERE  YEAR([A_LAST_UPDATE_DATE]) = 2018 
 --AND UHC_SUBSCRIBER_ID = '115359166'

