-- =============================================
-- Author:		Bing Yu
-- Create date: 04/04/2019
-- Description:	Insert UHC Claim file to DB
-- =============================================
CREATE PROCEDURE [adi].[ImportUHCClaims]
	@DataDate VARCHAR(10), 
	@OriginalFileName varchar(100)  ,
	@SrcFileName varchar(100)  ,
	@CreatedBy varchar(50)  ,
	@LastUpdatedBy varchar(50)  ,
	@COMPANY_CODE varchar(50) ,
	@LINE_OF_BUSINESS_DESC varchar(50) ,
	@CATEGORY_OF_SVC varchar(50) ,
	@SEQ_CLAIM_ID varchar(50) ,
	@CLAIM_NUMBER varchar(50) ,
	@LINE_NUMBER varchar(50) ,
	@SUB_LINE_CODE varchar(50) ,
	@PRIMARY_SVC_DATE VARCHAR(100),
	@CLAIM_THRU_DATE varchar(100), 
	@POST_DATE varchar(100), 
	@CHECK_DATE varchar(100),
	@CHECK_NUMBER varchar(20) ,
	@PROCEDURE_CODE varchar(20) ,
	@MODIFIER_CODE_1 varchar(20) ,
	@MODIFIER_CODE_2 varchar(20) ,
	@MODIFIER_CODE_3 varchar(20) ,
	@MODIFIER_CODE_4 varchar(20) ,
	@REVENUE_CODE varchar(20) ,
	@DATE_RECEIVED varchar(20), 
	@ADJUD_DATE varchar(20), 
	@DETAIL_SVC_DATE varchar(20),
	@SVC_TO_DATE varchar(20),
	@SVC_PROV_ID varchar(50) ,
	@SVC_PROV_FULL_NAME varchar(200) ,
	@SVC_PROV_NPI varchar(20) ,
	@PROV_SPEC varchar(50) ,
	@PROV_TYPE varchar(50) ,
	@PROVIDER_PAR_STAT varchar(50) ,
	@ATT_PROV_ID varchar(20) ,
	@ATT_PROV_FULL_NAME varchar(200) ,
	@ATT_PROV_NPI varchar(20) ,
	@REF_PROV_ID varchar(50) ,
	@REF_PROV_FULL_NAME [varchar](200) ,
	@VENDOR_ID varchar(20) ,
    @VEND_FULL_NAME varchar(200) ,
	@IRS_TAX_ID varchar(20) ,
	@SUBSCRIBER_ID varchar(50) ,
	@PAT_CONTROL_NO varchar(50) ,
	@DOB varchar(10), 
	@MEMB_LAST_NAME varchar(50) ,
	@MEMB_MIDDLE_INITIAL varchar(50) ,
	@MEMB_FIRST_NAME varchar(50) ,
	@MEDICAID_NO varchar(20) ,
	@MEDICARE_NO varchar(20) ,
	@GENDER varchar(20) ,
	@MEMB_ZIP varchar(20) ,
	@PLACE_OF_SVC_CODE1 varchar(20) ,
	@PLACE_OF_SVC_CODE2 varchar (20) ,
	@PLACE_OF_SVC_CODE3 varchar(20) ,
	@ICD_PRIM_DIAG varchar(20) ,
	@ICD_FLAG varchar(20) ,
	@DIAG1 varchar(20) ,
	@DIAG2 varchar(20) ,
	@DIAG3 varchar(20) ,
	@DIAG4 varchar(20) ,
	@DIAG5 varchar(20) ,
	@DIAG6 varchar(20) ,
	@DIAG7 varchar(20) ,
	@DIAG8 varchar(20) ,
	@DIAG9 varchar(20) ,
	@DIAG10 varchar(20) ,
	@DIAG11 varchar(20) ,
	@DIAG12 varchar(20) ,
	@DIAG13 varchar(20) ,
	@DIAG14 varchar(20) ,
	@DIAG15 varchar(20) ,
	@DIAG16 varchar(20) ,
	@DIAG17 varchar(20) ,
	@DIAG18 varchar(20) ,
	@DIAG19 varchar(20) ,
	@DIAG20 varchar(20) ,
	@DIAG21 varchar(20) ,
	@DIAG22 varchar(20) ,
	@DIAG23 varchar(20) ,
	@DIAG24 varchar(20) ,
	@DIAG25 varchar(20) ,
	@DIAGNOSIS_1_POA varchar(20) ,
	@DIAGNOSIS_2_POA varchar(20) ,
	@DIAGNOSIS_3_POA varchar(20) ,
	@DIAGNOSIS_4_POA varchar(20) ,
	@DIAGNOSIS_5_POA varchar(20) ,
	@DIAGNOSIS_6_POA varchar(20) ,
	@DIAGNOSIS_7_POA varchar(20) ,
	@DIAGNOSIS_8_POA varchar(20) ,
	@DIAGNOSIS_9_POA varchar(20) ,
	@DIAGNOSIS_10_POA varchar(20) ,
	@DIAGNOSIS_11_POA varchar(20) ,
	@DIAGNOSIS_12_POA varchar(20) ,
	@DIAGNOSIS_13_POA varchar(20) ,
	@DIAGNOSIS_14_POA varchar(20) ,
	@DIAGNOSIS_15_POA varchar(20) ,
	@DIAGNOSIS_16_POA varchar(20) ,
    @DIAGNOSIS_17_POA varchar(20) ,
	@DIAGNOSIS_18_POA varchar(20) ,
	@DIAGNOSIS_19_POA varchar(20) ,
	@DIAGNOSIS_20_POA varchar(20) ,
	@DIAGNOSIS_21_POA varchar(20) ,
	@DIAGNOSIS_22_POA varchar(20) ,
	@DIAGNOSIS_23_POA varchar(20) ,
	@DIAGNOSIS_24_POA varchar(20) ,
	@DIAGNOSIS_25_POA varchar(20) ,
	@DRG_CODE varchar(20) ,
	@BILL_TYPE varchar(50) ,
	@ICD_PROC_1 varchar(20) ,
	@ICD_PROC_2 varchar(20) ,
	@ICD_PROC_3 varchar(20) ,
	@ICD_PROC_4 varchar(20) ,
	@ICD_PROC_5 varchar(20) ,
	@ICD_PROC_6 varchar(20) ,
	@ICD_PROC_7 varchar(20) ,
	@ICD_PROC_8 varchar(20) ,
	@ICD_PROC_9 varchar(20) ,
	@ICD_PROC_10 varchar(20) ,
	@ICD_PROC_11 varchar(20) ,
	@ICD_PROC_12 varchar(20) ,
	@ICD_PROC_13 varchar(20) ,
	@ICD_PROC_14 varchar(20) ,
	@ICD_PROC_15 varchar(20) ,
	@ICD_PROC_16 varchar(20) ,
	@ICD_PROC_17 varchar(20) ,
	@ICD_PROC_18 varchar(20) ,
	@ICD_PROC_19 varchar(20) ,
	@ICD_PROC_20 varchar(20) ,
	@ICD_PROC_21 varchar(20) ,
	@ICD_PROC_22 varchar(20) ,
	@ICD_PROC_23 varchar(20) ,
	@ICD_PROC_24 varchar(20) ,
	@ICD_PROC_25 varchar(20) ,
	@ICD_PROC_1_DATE varchar(20),
	@ICD_PROC_2_DATE varchar(20),
	@ICD_PROC_3_DATE varchar(20),
	@ICD_PROC_4_DATE varchar(20),
	@ICD_PROC_5_DATE varchar(20),
	@ICD_PROC_6_DATE varchar(20), 
	@ICD_PROC_7_DATE varchar(20),
	@ICD_PROC_8_DATE varchar(20), 
	@ICD_PROC_9_DATE varchar(20),
	@ICD_PROC_10_DATE varchar(20), 
	@ICD_PROC_11_DATE varchar(20), 
	@ICD_PROC_12_DATE varchar(20), 
	@ICD_PROC_13_DATE varchar(20), 
	@ICD_PROC_14_DATE varchar(20), 
	@ICD_PROC_15_DATE varchar(20), 
	@ICD_PROC_16_DATE varchar(20),
	@ICD_PROC_17_DATE varchar(20),
	@ICD_PROC_18_DATE varchar(20),
	@ICD_PROC_19_DATE varchar(20),
	@ICD_PROC_20_DATE varchar(20),
	@ICD_PROC_21_DATE varchar(20),
	@ICD_PROC_22_DATE varchar(20), 
	@ICD_PROC_23_DATE varchar(20), 
	@ICD_PROC_24_DATE varchar(20), 
	@ICD_PROC_25_DATE varchar(20), 
	@CONDITION_CODE_1 varchar(20) ,
	@CONDITION_CODE_2 varchar(20) ,
	@CONDITION_CODE_3 varchar(20) ,
	@CONDITION_CODE_4 varchar(20) ,
	@CONDITION_CODE_5 varchar(20) ,
	@CONDITION_CODE_6 varchar(20) ,
	@CONDITION_CODE_7 varchar(20) ,
	@CONDITION_CODE_8 varchar(20) ,
	@CONDITION_CODE_9 varchar(20) ,
	@CONDITION_CODE_10 varchar(20) ,
	@CONDITION_CODE_11 varchar(20) ,
	@ADMISSION_DATE varchar(20),
	@AUTH_NUMBER varchar(20) ,
	@ADMIT_SOURCE_CODE varchar(20) ,
	@ADMIT_HOUR varchar(20) ,
	@DISCHARGE_HOUR varchar(20) ,
	@PATIENT_STATUS varchar(20) ,
	@CLAIM_STATUS varchar(20) ,
	@PROCESSING_STATUS varchar(20) ,
	@CLAIM_TYPE varchar(20) ,
	@QUANTITY varchar(20) ,
	@TOTAL_BILLED_AMT varchar(50) ,
	@BILLED_AMT varchar(50) ,
	@NDC_CODE varchar(20) ,
	@RX_GENERIC_BRAND_IND varchar(50) ,
	@RX_SUPPLY_DAYS varchar(50) ,
	@RX_DISPENSING_FEE_AMT varchar(50) ,
	@RX_INGREDIENT_AMT varchar(50) ,
	@RX_FORMULARY_IND varchar(50) ,
	@RX_DATE_PRESCRIPTION_WRITTEN varchar(50) ,
	@BRAND_NAME varchar(50) ,
	@DRUG_STRENGTH_DESC varchar(50) ,
	@GPI varchar(50) ,
	@GPI_DESC varchar(50) ,
	@CONTROLLED_DRUG_IND varchar(50) ,
	@COMPOUND_CODE varchar(50) ,
	@PAID_NET_AMT varchar(50)    
          
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	--UPDATE adi.[stg_claims] 
	--SET FirstName = @FirstName,
	--    LastName = @LastName

 --   WHERE SUBSCRIBER_ID = @SUBSCRIBER_ID
--	and 
	 
	--IF @@ROWCOUNT = 0
	
    EXEC [ACDW_CLMS_UHC].[adi].[ImportUHCClaims] 
	        @DataDate , 
	@OriginalFileName   ,
	@SrcFileName   ,
	@CreatedBy   ,
	@LastUpdatedBy   ,
	@COMPANY_CODE  ,
	@LINE_OF_BUSINESS_DESC  ,
	@CATEGORY_OF_SVC  ,
	@SEQ_CLAIM_ID  ,
	@CLAIM_NUMBER  ,
	@LINE_NUMBER  ,
	@SUB_LINE_CODE  ,
	@PRIMARY_SVC_DATE,
	@CLAIM_THRU_DATE , 
	@POST_DATE , 
	@CHECK_DATE ,
	@CHECK_NUMBER  ,
	@PROCEDURE_CODE  ,
	@MODIFIER_CODE_1  ,
	@MODIFIER_CODE_2  ,
	@MODIFIER_CODE_3  ,
	@MODIFIER_CODE_4  ,
	@REVENUE_CODE  ,
	@DATE_RECEIVED , 
	@ADJUD_DATE , 
	@DETAIL_SVC_DATE ,
	@SVC_TO_DATE ,
	@SVC_PROV_ID  ,
	@SVC_PROV_FULL_NAME  ,
	@SVC_PROV_NPI  ,
	@PROV_SPEC  ,
	@PROV_TYPE  ,
	@PROVIDER_PAR_STAT  ,
	@ATT_PROV_ID  ,
	@ATT_PROV_FULL_NAME  ,
	@ATT_PROV_NPI  ,
	@REF_PROV_ID  ,
	@REF_PROV_FULL_NAME  ,
	@VENDOR_ID  ,
        @VEND_FULL_NAME  ,
	@IRS_TAX_ID  ,
	@SUBSCRIBER_ID  ,
	@PAT_CONTROL_NO  ,
	@DOB , 
	@MEMB_LAST_NAME  ,
	@MEMB_MIDDLE_INITIAL  ,
	@MEMB_FIRST_NAME  ,
	@MEDICAID_NO  ,
	@MEDICARE_NO  ,
	@GENDER  ,
	@MEMB_ZIP  ,
	@PLACE_OF_SVC_CODE1  ,
	@PLACE_OF_SVC_CODE2 ,
	@PLACE_OF_SVC_CODE3  ,
	@ICD_PRIM_DIAG  ,
	@ICD_FLAG  ,
	@DIAG1  ,
	@DIAG2  ,
	@DIAG3  ,
	@DIAG4  ,
	@DIAG5  ,
	@DIAG6  ,
	@DIAG7  ,
	@DIAG8  ,
	@DIAG9  ,
	@DIAG10  ,
	@DIAG11  ,
	@DIAG12  ,
	@DIAG13  ,
	@DIAG14  ,
	@DIAG15  ,
	@DIAG16  ,
	@DIAG17  ,
	@DIAG18  ,
	@DIAG19  ,
	@DIAG20  ,
	@DIAG21  ,
	@DIAG22  ,
	@DIAG23  ,
	@DIAG24  ,
	@DIAG25  ,
	@DIAGNOSIS_1_POA  ,
	@DIAGNOSIS_2_POA  ,
	@DIAGNOSIS_3_POA  ,
	@DIAGNOSIS_4_POA  ,
	@DIAGNOSIS_5_POA  ,
	@DIAGNOSIS_6_POA  ,
	@DIAGNOSIS_7_POA  ,
	@DIAGNOSIS_8_POA  ,
	@DIAGNOSIS_9_POA  ,
	@DIAGNOSIS_10_POA  ,
	@DIAGNOSIS_11_POA  ,
	@DIAGNOSIS_12_POA  ,
	@DIAGNOSIS_13_POA  ,
	@DIAGNOSIS_14_POA  ,
	@DIAGNOSIS_15_POA  ,
	@DIAGNOSIS_16_POA  ,
        @DIAGNOSIS_17_POA  ,
	@DIAGNOSIS_18_POA  ,
	@DIAGNOSIS_19_POA  ,
	@DIAGNOSIS_20_POA  ,
	@DIAGNOSIS_21_POA  ,
	@DIAGNOSIS_22_POA  ,
	@DIAGNOSIS_23_POA  ,
	@DIAGNOSIS_24_POA  ,
	@DIAGNOSIS_25_POA  ,
	@DRG_CODE  ,
	@BILL_TYPE  ,
	@ICD_PROC_1  ,
	@ICD_PROC_2  ,
	@ICD_PROC_3  ,
	@ICD_PROC_4  ,
	@ICD_PROC_5  ,
	@ICD_PROC_6  ,
	@ICD_PROC_7  ,
	@ICD_PROC_8  ,
	@ICD_PROC_9  ,
	@ICD_PROC_10  ,
	@ICD_PROC_11  ,
	@ICD_PROC_12  ,
	@ICD_PROC_13  ,
	@ICD_PROC_14  ,
	@ICD_PROC_15  ,
	@ICD_PROC_16  ,
	@ICD_PROC_17  ,
	@ICD_PROC_18  ,
	@ICD_PROC_19  ,
	@ICD_PROC_20  ,
	@ICD_PROC_21  ,
	@ICD_PROC_22  ,
	@ICD_PROC_23  ,
	@ICD_PROC_24  ,
	@ICD_PROC_25  ,
	@ICD_PROC_1_DATE ,
	@ICD_PROC_2_DATE ,
	@ICD_PROC_3_DATE ,
	@ICD_PROC_4_DATE ,
	@ICD_PROC_5_DATE ,
	@ICD_PROC_6_DATE , 
	@ICD_PROC_7_DATE ,
	@ICD_PROC_8_DATE , 
	@ICD_PROC_9_DATE ,
	@ICD_PROC_10_DATE , 
	@ICD_PROC_11_DATE , 
	@ICD_PROC_12_DATE , 
	@ICD_PROC_13_DATE , 
	@ICD_PROC_14_DATE , 
	@ICD_PROC_15_DATE , 
	@ICD_PROC_16_DATE ,
	@ICD_PROC_17_DATE ,
	@ICD_PROC_18_DATE ,
	@ICD_PROC_19_DATE ,
	@ICD_PROC_20_DATE ,
	@ICD_PROC_21_DATE ,
	@ICD_PROC_22_DATE , 
	@ICD_PROC_23_DATE , 
	@ICD_PROC_24_DATE , 
	@ICD_PROC_25_DATE , 
	@CONDITION_CODE_1  ,
	@CONDITION_CODE_2  ,
	@CONDITION_CODE_3  ,
	@CONDITION_CODE_4  ,
	@CONDITION_CODE_5  ,
	@CONDITION_CODE_6  ,
	@CONDITION_CODE_7  ,
	@CONDITION_CODE_8  ,
	@CONDITION_CODE_9  ,
	@CONDITION_CODE_10  ,
	@CONDITION_CODE_11  ,
	@ADMISSION_DATE ,
	@AUTH_NUMBER  ,
	@ADMIT_SOURCE_CODE  ,
	@ADMIT_HOUR  ,
	@DISCHARGE_HOUR  ,
	@PATIENT_STATUS  ,
	@CLAIM_STATUS  ,
	@PROCESSING_STATUS  ,
	@CLAIM_TYPE  ,
	@QUANTITY  ,
	@TOTAL_BILLED_AMT  ,
	@BILLED_AMT  ,
	@NDC_CODE  ,
	@RX_GENERIC_BRAND_IND  ,
	@RX_SUPPLY_DAYS  ,
	@RX_DISPENSING_FEE_AMT  ,
	@RX_INGREDIENT_AMT  ,
	@RX_FORMULARY_IND  ,
	@RX_DATE_PRESCRIPTION_WRITTEN  ,
	@BRAND_NAME  ,
	@DRUG_STRENGTH_DESC  ,
	@GPI  ,
	@GPI_DESC  ,
	@CONTROLLED_DRUG_IND  ,
	@COMPOUND_CODE  ,
	@PAID_NET_AMT     
	
END

