-- =============================================
-- Author:		Bing Yu
-- Create date: 04/04/2019
-- Description:	Insert CareGaps Claim file to DB
-- ============================================
CREATE PROCEDURE [adi].[ImportMSSPPartBPhysicianClaimLineItem]
    @SrcFileName [varchar](100) NULL,
	--[CreateDate] [datetime] NULL,
	@CreateBy [varchar](100) NULL,
	@OriginalFileName [varchar](100) NULL,
	@LastUpdatedBy [varchar](100) NULL,
	--[LastUpdatedDate] [datetime] NULL,
	@DataDate varchar(10),
	@ClaimID [varchar](50) NULL,
	@LineNBR [varchar](50) NULL,
	@MedicareBeneficiaryID [varchar](50) NULL,
	@HealthInsuranceClaimNBR [varchar](50) NULL,
	@ClaimTypeCD [varchar](10) NULL,
	@ClaimTypeDSC [varchar](500) NULL,
	@ClaimStartDTS varchar(10),
	@ClaimEndDTS varchar(10),
	@RenderingProviderTypeCD [varchar](10) NULL,
	@RenderingProviderTypeDSC [varchar](500) NULL,
	@RenderingProviderFIPSStateCD [varchar](10) NULL,
	@ProviderSpecialtyCD [varchar](10) NULL,
	@ServiceTypeCD [varchar](10) NULL,
	@ServiceTypeDSC [varchar](500) NULL,
	@PlaceOfServiceCD [varchar](10) NULL,
	@PlaceOfServiceNM [varchar](50) NULL,
	@StartDTS varchar(10),
	@EndDTS varchar(10),
	@HCPCS [varchar](50) NULL,
	@PaymentAMT varchar(10),
	@PrimaryPayerCD [varchar](10) NULL,
	@PrimaryPayerDSC [varchar](500) NULL,
	@PrincipalICDDiagnosisCD [varchar](10) NULL,
	@ClaimTaxID [varchar](50) NULL,
	@RenderingProviderNPI [varchar](50) NULL,
	@CarrierPaymentDispositionCD [varchar](10) NULL,
	@CarrierPaymentDispositionDSC [varchar](500) NULL,
	@LineProcessingIndicatorCD [varchar](10) NULL,
	@LineProcessingIndicatorDSC [varchar](500) NULL,
	@AdjustmentTypeCD [varchar](10) NULL,
	@AdjustmentTypeDSC [varchar](500) NULL,
	@ProcessingDTS varchar(10),
	@RepositoryLoadDTS varchar(10),
	@ControlNBR [varchar](50) NULL,
	@UmbrellaHealthInsuranceClaimNBR [varchar](50) NULL,
	@AllowedAMT varchar(10),
	@AllowedUnitCNT varchar(5),
	@HCPCSModifier01CD [varchar](50) NULL,
	@HCPCSModifier02CD [varchar](50) NULL,
	@HCPCSModifier03CD [varchar](50) NULL,
	@HCPCSModifier04CD [varchar](50) NULL,
	@HCPCSModifier05CD [varchar](50) NULL,
	@ClaimDispositionCD [varchar](50) NULL,
	@ClaimDispositionDSC [varchar](500) NULL,
	@ClaimICDDiagnosis01CD [varchar](50) NULL,
	@ClaimICDDiagnosis02CD [varchar](50) NULL,
	@ClaimICDDiagnosis03CD [varchar](50) NULL,
	@ClaimICDDiagnosis04CD [varchar](50) NULL,
	@ClaimICDDiagnosis05CD [varchar](50) NULL,
	@ClaimICDDiagnosis06CD [varchar](50) NULL,
	@ClaimICDDiagnosis07CD [varchar](50) NULL,
	@ClaimICDDiagnosis08CD [varchar](50) NULL,
	@ICDRevisionCD varchar (50) NULL,
	@ClaimICDDiagnosis09CD [varchar](50) NULL,
	@ClaimICDDiagnosis10CD [varchar](50) NULL,
	@ClaimICDDiagnosis11CD [varchar](50) NULL,
	@ClaimICDDiagnosis12CD [varchar](50) NULL,
	@HCPCSBerensonEggersTypeOfServiceCD [varchar](50) NULL,
	@FileNM [varchar](50)
            
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	EXEC [ACDW_CLMS_SHCN_MSSP].[adi].[ImportMSSPPartBPhysicianClaimLineItem]
	   @SrcFileName ,
	--[CreateDate] [datetime] NULL,
	@CreateBy ,
	@OriginalFileName ,
	@LastUpdatedBy ,
	--[LastUpdatedDate] [datetime] NULL,
	@DataDate ,
	@ClaimID ,
	@LineNBR ,
	@MedicareBeneficiaryID ,
	@HealthInsuranceClaimNBR ,
	@ClaimTypeCD ,
	@ClaimTypeDSC ,
	@ClaimStartDTS ,
	@ClaimEndDTS ,
	@RenderingProviderTypeCD ,
	@RenderingProviderTypeDSC ,
	@RenderingProviderFIPSStateCD ,
	@ProviderSpecialtyCD ,
	@ServiceTypeCD ,
	@ServiceTypeDSC ,
	@PlaceOfServiceCD ,
	@PlaceOfServiceNM ,
	@StartDTS ,
	@EndDTS ,
	@HCPCS ,
	@PaymentAMT ,
	@PrimaryPayerCD ,
	@PrimaryPayerDSC ,
	@PrincipalICDDiagnosisCD ,
	@ClaimTaxID ,
	@RenderingProviderNPI ,
	@CarrierPaymentDispositionCD ,
	@CarrierPaymentDispositionDSC ,
	@LineProcessingIndicatorCD ,
	@LineProcessingIndicatorDSC ,
	@AdjustmentTypeCD ,
	@AdjustmentTypeDSC ,
	@ProcessingDTS ,
	@RepositoryLoadDTS ,
	@ControlNBR ,
	@UmbrellaHealthInsuranceClaimNBR ,
	@AllowedAMT ,
	@AllowedUnitCNT ,
	@HCPCSModifier01CD ,
	@HCPCSModifier02CD ,
	@HCPCSModifier03CD ,
	@HCPCSModifier04CD ,
	@HCPCSModifier05CD ,
	@ClaimDispositionCD ,
	@ClaimDispositionDSC ,
	@ClaimICDDiagnosis01CD ,
	@ClaimICDDiagnosis02CD ,
	@ClaimICDDiagnosis03CD ,
	@ClaimICDDiagnosis04CD ,
	@ClaimICDDiagnosis05CD ,
	@ClaimICDDiagnosis06CD ,
	@ClaimICDDiagnosis07CD ,
	@ClaimICDDiagnosis08CD ,
	@ICDRevisionCD ,
	@ClaimICDDiagnosis09CD ,
	@ClaimICDDiagnosis10CD ,
	@ClaimICDDiagnosis11CD ,
	@ClaimICDDiagnosis12CD ,
	@HCPCSBerensonEggersTypeOfServiceCD ,
	@FileNM 

    
END
