

-- =============================================
-- Author:		Bing Yu
-- Create date: 11/21/2019
-- Description:	Insert UHC Member file to DB
-- =============================================
CREATE PROCEDURE [adi].[ImportUHCMemberbyProvider]
    @DataDate varchar(10),
	@OriginalFileName varchar(100),
	@SrcFileName varchar(100),
	--[CreatedDate datetime2(7),
	@CreatedBy varchar(50),
	--[LastUpdatedDate] [datetime2](7) NOT NULL,
	@LastUpdatedBy varchar(50),
	@RptGrp  varchar(50) ,
	@Practice_Name  varchar(100) ,
	@plan  varchar(50) ,
	@REGION  varchar(50) ,
	@COMPANY_DESC  varchar(100) ,
	@LINE_OF_BUSINESS  varchar(100) ,
	@LINE_OF_BUSINESS_DESC  varchar(100) ,
	@PLAN_CODE  varchar(50) ,
	@PLAN_DESC  varchar(100) ,
	@PLAN_PROGRAM  varchar(50) ,
	@PLAN_PROGRAM_DESC  varchar(100) ,
	@MEMB_FIRST_NAME  varchar(50) ,
	@MEMB_LAST_NAME  varchar(50) ,
	@SUBSCRIBER_ID  varchar(50) ,
	@MEDICAID_NO  varchar(50) ,
	@MEDICARE_NO  varchar(50) ,
	@AGE  varchar(10) ,
	@DATE_OF_BIRTH  varchar(20) ,
	@MEMB_GENDER  varchar(10) ,
	@MEMB_ADDRESS_LINE_1  varchar(50) ,
	@MEMB_ADDRESS_LINE_2  varchar(100) ,
	@MEMB_CITY  varchar(50) ,
	@MEMB_STATE  varchar(50) ,
	@MEMB_ZIP  varchar(10) ,
	@HOME_PHONE_NUMBER  varchar(20) ,
	@BUS_PHONE_NUMBER  varchar(20) ,
	@MBR_EFFECTIVE_DATE  varchar(50) ,
	@MBR_TERM_DATE  varchar(50) ,
	@PROVIDER_ID  varchar(20) ,
	@PROVIDER_NPI  varchar(20) ,
	@PROV_FNAME  varchar(50) ,
	@PROV_LNAME  varchar(50) ,
	@PROV_PHONE  varchar(20) ,
	@PROV_ADDRESS_LINE_1  varchar(50) ,
	@PROV_ADDRESS_LINE_2  varchar(50) ,
	@PROV_CITY  varchar(50) ,
	@PROV_STATE  varchar(50) ,
	@PROV_ZIP  varchar(10) ,
	@PROV_TERM_DATE  varchar(10) ,
	@IRS_TAX_ID  varchar(20) ,
	@PAYEE_NAME  varchar(50) ,
	@VENDOR_ID  varchar(50) ,
	@MEMB_ETHNICITY  varchar(10) ,
	@PANEL_ID  varchar(50) ,
	@COSMOS_CUST_SEG  varchar(20) ,
	@COSMOS_CUST_SEG_DESC  varchar(50) ,
	@PROV_LANG_1  varchar(20) ,
	@PROV_LANG_2  varchar(20) ,
	@PROV_LANG_3  varchar(20) ,
	@LAST_OFFICE_VISIT_DATE  varchar(20) ,
	@LAST_OFFICE_VISIT_DAYS_BACK  varchar(50) ,
	@LAST_OFFICE_VISIT_NPI  varchar(20) ,
	@LAST_OFFICE_VISIT_TIN  varchar(20) ,
	@LAST_OFFICE_VISIT_FLAG  varchar(50) ,
	@LAST_VISIT_PROV_TYPE  varchar(50) ,
	@LAST_OFFICE_VISIT_PAR  varchar(50) ,
	@CONT_EFFECTIVE_DATE  varchar(20) ,
	@ORIGINAL_EFFECTIVE_DATE  varchar(20) ,
	@IPRO_RISK_SCORE  decimal(10, 2) ,
	@AUTO_ASSIGNED  varchar(50) 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	exec [ACDW_CLMS_UHC].[adi].[ImportUHCMemberbyProvider]
	@DataDate ,
	@OriginalFileName ,
	@SrcFileName ,
	--[CreatedDate datetime2(7),
	@CreatedBy ,
	--[LastUpdatedDate] [datetime2](7) NOT NULL,
	@LastUpdatedBy ,
	@RptGrp   ,
	@Practice_Name   ,
	@plan   ,
	@REGION   ,
	@COMPANY_DESC   ,
	@LINE_OF_BUSINESS   ,
	@LINE_OF_BUSINESS_DESC   ,
	@PLAN_CODE   ,
	@PLAN_DESC   ,
	@PLAN_PROGRAM   ,
	@PLAN_PROGRAM_DESC   ,
	@MEMB_FIRST_NAME   ,
	@MEMB_LAST_NAME   ,
	@SUBSCRIBER_ID   ,
	@MEDICAID_NO   ,
	@MEDICARE_NO   ,
	@AGE   ,
	@DATE_OF_BIRTH   ,
	@MEMB_GENDER   ,
	@MEMB_ADDRESS_LINE_1   ,
	@MEMB_ADDRESS_LINE_2   ,
	@MEMB_CITY   ,
	@MEMB_STATE   ,
	@MEMB_ZIP   ,
	@HOME_PHONE_NUMBER   ,
	@BUS_PHONE_NUMBER   ,
	@MBR_EFFECTIVE_DATE   ,
	@MBR_TERM_DATE   ,
	@PROVIDER_ID   ,
	@PROVIDER_NPI   ,
	@PROV_FNAME   ,
	@PROV_LNAME   ,
	@PROV_PHONE   ,
	@PROV_ADDRESS_LINE_1   ,
	@PROV_ADDRESS_LINE_2   ,
	@PROV_CITY   ,
	@PROV_STATE   ,
	@PROV_ZIP   ,
	@PROV_TERM_DATE   ,
	@IRS_TAX_ID   ,
	@PAYEE_NAME   ,
	@VENDOR_ID   ,
	@MEMB_ETHNICITY   ,
	@PANEL_ID   ,
	@COSMOS_CUST_SEG   ,
	@COSMOS_CUST_SEG_DESC   ,
	@PROV_LANG_1   ,
	@PROV_LANG_2   ,
	@PROV_LANG_3   ,
	@LAST_OFFICE_VISIT_DATE   ,
	@LAST_OFFICE_VISIT_DAYS_BACK   ,
	@LAST_OFFICE_VISIT_NPI   ,
	@LAST_OFFICE_VISIT_TIN   ,
	@LAST_OFFICE_VISIT_FLAG   ,
	@LAST_VISIT_PROV_TYPE   ,
	@LAST_OFFICE_VISIT_PAR   ,
	@CONT_EFFECTIVE_DATE   ,
	@ORIGINAL_EFFECTIVE_DATE   ,
	@IPRO_RISK_SCORE   ,
	@AUTO_ASSIGNED   



END
