-- =============================================
-- Author:		Bing Yu
-- Create date: 04/04/2019
-- Description:	Insert CareGaps Claim file to DB
-- =============================================
CREATE PROCEDURE [adi].[ImportMSSPPartAClaim]
    @SrcFileName [varchar](100) NULL,
	-- [CreateDate] [datetime] NULL,
	@CreateBy [varchar](100) NULL,
	@OriginalFileName [varchar](100) NULL,
	@LastUpdatedBy [varchar](100) NULL,
	--@LastUpdatedDate [datetime] NULL,
	@DataDate [date] NULL,
	@ClaimID [varchar](20) NULL,
	@CMSCertificationNBR [varchar](20) NULL,
	@MedicareBeneficiaryID [varchar](20) NULL,
	@HealthInsuranceClaimNBR [varchar](20) NULL,
	@ClaimTypeCD [varchar](20) NULL,
	@ClaimTypeDSC [varchar](500) NULL,
	@ClaimStartDTS varchar(10),
	@ClaimEndDTS VARCHAR(10),
	@BillFacilityTypeCD [varchar](20) NULL,
	@BillFacilityTypeDSC [varchar](500) NULL,
	@BillClassificationCD [varchar](20) NULL,
	@BillClassificationDSC [varchar](500) NULL,
	@PrincipalICDDiagnosisCD [varchar](20) NULL,
	@AdmitICDDiagnosisCD [varchar](20) NULL,
	@PaymentDenialReasonCD [varchar](20) NULL,
	@PaymentDenialReasonDSC [varchar](500) NULL,
	@PaymentAMT VARCHAR(10) ,
	@primaryPayerCD [varchar](20) NULL,
	@PrimaryPayerDSC [varchar](500) NULL,
	@FacilityFIPSStateCD [varchar](20) NULL,
	@DischargeStatusCD [varchar](20) NULL,
	@DischargeStatusDSC [varchar](500) NULL,
	@MSDRG [varchar](10) NULL,
	@OutpatientServiceTypeCD [varchar](20) NULL,
	@OutpatientServiceTypeDSC [varchar](500) NULL,
	@FacilityNPI [varchar](20) NULL,
	@OperatingProviderNPI [varchar](20) NULL,
	@AttendingProviderNPI [varchar](20) NULL,
	@OtherProviderNPI [varchar](20) NULL,
	@AdjustmentTypeCD [varchar](20) NULL,
	@AdjustmentTypeDSC [varchar](500) NULL,
	@ProcessingDTS varchar(10),
	@RepositoryLoadDTS varchar(10),
	@UmbrellaHealthInsuranceClaimNBR [varchar](20) NULL,
	@AdmitTypeCD [varchar](20) NULL,
	@AdmitTypeDSC [varchar](500) NULL,
	@AdmitSourceCD [varchar](20) NULL,
	@AdmitSourceDSC [varchar](500) NULL,
	@BillFrequencyCD [varchar](20) NULL,
	@BillFrequencyDSC [varchar](500) NULL,
	@PaymentQueryCD [varchar](20) NULL,
	@PaymentQueryDSC [varchar](20) NULL,
	@ICDRevisionCD [varchar](20) NULL,
	@PopulationBasedPaymentInclusionAMT varchar(10),
	@PopulationBasedPaymentReductionAMT varchar(10),
	@TotalChargeAMT varchar(10),
	@CapitalIndirectMedicalEducationAMT varchar(10),
	@OperationalIndirectMedicalEducationAMT varchar(10),
	@CapitalDisproportionateAMT varchar(10),
	@HIPPSUncompensatedAMT varchar(10),
	@OperationalDisproportionateAMT varchar(10),
	@FileNM varchar(100) 
            
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	EXEC [ACDW_CLMS_SHCN_MSSP].[adi].[ImportMSSPPartAClaim]
     @SrcFileName ,
	-- [CreateDate] [datetime] NULL,
	@CreateBy ,
	@OriginalFileName ,
	@LastUpdatedBy ,
	--@LastUpdatedDate [datetime] NULL,
	@DataDate ,
	@ClaimID ,
	@CMSCertificationNBR ,
	@MedicareBeneficiaryID ,
	@HealthInsuranceClaimNBR ,
	@ClaimTypeCD ,
	@ClaimTypeDSC ,
	@ClaimStartDTS ,
	@ClaimEndDTS ,
	@BillFacilityTypeCD ,
	@BillFacilityTypeDSC ,
	@BillClassificationCD ,
	@BillClassificationDSC ,
	@PrincipalICDDiagnosisCD ,
	@AdmitICDDiagnosisCD ,
	@PaymentDenialReasonCD ,
	@PaymentDenialReasonDSC ,
	@PaymentAMT ,
	@primaryPayerCD ,
	@PrimaryPayerDSC ,
	@FacilityFIPSStateCD ,
	@DischargeStatusCD ,
	@DischargeStatusDSC ,
	@MSDRG ,
	@OutpatientServiceTypeCD ,
	@OutpatientServiceTypeDSC ,
	@FacilityNPI ,
	@OperatingProviderNPI ,
	@AttendingProviderNPI ,
	@OtherProviderNPI ,
	@AdjustmentTypeCD ,
	@AdjustmentTypeDSC ,
	@ProcessingDTS ,
	@RepositoryLoadDTS ,
	@UmbrellaHealthInsuranceClaimNBR ,
	@AdmitTypeCD ,
	@AdmitTypeDSC ,
	@AdmitSourceCD ,
	@AdmitSourceDSC ,
	@BillFrequencyCD ,
	@BillFrequencyDSC ,
	@PaymentQueryCD ,
	@PaymentQueryDSC ,
	@ICDRevisionCD ,
	@PopulationBasedPaymentInclusionAMT ,
	@PopulationBasedPaymentReductionAMT ,
	@TotalChargeAMT ,
	@CapitalIndirectMedicalEducationAMT ,
	@OperationalIndirectMedicalEducationAMT ,
	@CapitalDisproportionateAMT ,
	@HIPPSUncompensatedAMT ,
	@OperationalDisproportionateAMT ,
	@FileNM 
END
