-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [adi].[ImportNtfAetTxMaDlyCensus](

    @OriginalFileName varchar(100),
	@SourceFileName varchar(100) ,
	@DataDate varchar(10), 
	@LoadDate varchar(10),
	@CreatedDate varchar(10),
	@CreatedBy varchar(50),
	@CarrierName varchar(100),
	@ACOName varchar(50),
	@ACOAttributedProviderName varchar(150),
	@NPINumber varchar(12),
	@ACOAttributedProviderAddress1 varchar(75),
	@ACOAttributedProviderAddress2 varchar(75),
	@ACOAttributedProviderCity varchar(40),
	@ACOAttributedProviderState varchar(20),
	@ACOAttributedProviderZipcode varchar(12),
	@ACOAttributedProviderPhone varchar(25),
	@MemberLastName varchar(65),
	@MemberFirstName varchar(65),
	@DwMemberID varchar(50),
	@CumbID varchar(50),
	@CardID varchar(50),
	@CardIdSeqNo varchar(50),
	@DateOfBirth varchar(10),
	@PulseScore varchar(50),
	@Status varchar(50),
	@MemberPhone varchar(25),
	@AcoAttributionEffectiveDate varchar(10),
	@AcoAttributionEndDate varchar(10),
	@MemberTerminationDate varchar(10),
	@LineOfBusiness varchar(50),
	@Product varchar(50) NULL,
	@PlanSponsorName varchar(50),
	@PlanSponsorControl varchar(50),
	@AdmitPotentiallyAvoidable varchar(50),
	@EventType varchar(50),
	@EventStageStatus varchar(50) ,
	@StayType varchar(50),
	@AdmissionType varchar(50),
	@NotificationDate varchar(10),
	@ExpectedAdmitDate varchar(10),
	@ActualAdmitDate varchar(10),
	@ExpectedDischargeDate varchar(10),
	@ActualDischargeDate varchar(10),
	@DischargeDisposition varchar(255),
	@DiagnosisCode varchar(15),
	@DiagnosisDescription varchar(255),
	@OtherComorbidDiagnosis1 varchar(15),
	@OtherComorbidDiagnosis2 varchar(15),
	@ProcedureCode varchar(15),
	@ProcedureDescription varchar(255),
	@ProcedureStartDate varchar(10),
	@ProviderNameRole varchar(255),
	@FacilityNameRole varchar(255),
	@FacilityAddress varchar(100),
	@filler1 varchar(50),
	@filler2 varchar(50) ,
	@filler3 varchar(50) ,
	@filler4 varchar(50),
	@filler5 varchar(50),
	@AttrProviderGroup VARCHAR(50),
	@PMENumber VARCHAR(50),
	@IsReadmit VARCHAR(50),
	@HasReadmit VARCHAR(50),
	@LenghthofStay VARCHAR(50),
    @ReadmissionPredictor VARCHAR(50),
	@CMSContract VARCHAR(50)
  
)
	-- Add the parameters for the stored procedure here
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	--UPDATE adi.MbrAetCom
--	SET MEMBER_ID  =  @MEMBER_ID 

--    WHERE  MEMBER_ID = @MEMBER_ID

	 
--	IF @@ROWCOUNT = 0

    -- Insert statements for procedure here
 INSERT INTO [adi].[NtfAetMaTxDlyCensus]
   (
    [OriginalFileName],
	[SourceFileName],
	[LoadDate],
    [DataDate],
	[CreatedDate] ,
	[CreatedBy] ,
	[CarrierName] ,
	[ACOName],
	[ACOAttributed Provider Name] ,
	[NPINumber] ,
	[ACOAttributed Provider Address1] ,
	[ACOAttributed Provider Address2] ,
	[ACOAttributed Provider City] ,
	[ACOAttributed Provider State] ,
	[ACOAttributed Provider Zipcode],
	[ACOAttributed Provider Phone] ,
	[MemberLastName] ,
	[MemberFirstName] ,
	[DwMemberID] ,
	[CumbID] ,
	[CardID] ,
	[CardIdSeqNo] ,
	[DateOfBirth] ,
	[PulseScore] ,
	[Status] ,
	[MemberPhone] ,
	[AcoAttributionEffectiveDate] ,
	[AcoAttributionEndDate] ,
	[MemberTerminationDate] ,
	[LineOfBusiness] ,
	[Product] ,
	[PlanSponsorName] ,
	[PlanSponsorControl],
	[AdmitPotentiallyAvoidable] ,
	[EventType] ,
	[EventStageStatus] ,
	[StayType] ,
	[AdmissionType],
	[NotificationDate] ,
	[ExpectedAdmitDate],
	[ActualAdmitDate],
	[ExpectedDischargeDate],
	[ActualDischargeDate],
	[DischargeDisposition],
	[DiagnosisCode] ,
	[DiagnosisDescription] ,
	[OtherComorbidDiagnosis1] ,
	[OtherComorbidDiagnosis2] ,
	[ProcedureCode] ,
	[ProcedureDescription] ,
	[ProcedureStart Date],
	[ProviderName/Role] ,
	[FacilityName/Role] ,
	[FacilityAddress] ,
	[filler1] ,
	[filler2] ,
	[filler3] ,
	[filler4] ,
	[filler5] ,
[Attr Provider Group],
[PME Number],
[Is Readmit],
[Has Readmit],
[Lenghth of Stay],
[Readmission Predictor],
[CMS Contract#]

            )
     VALUES
   ( 
    @OriginalFileName,
	@SourceFileName ,
	GETDATE(),
	CONVERT(DATE,GETDATE()),
	--CONVERT(date, RIGHT(Substring(@SourceFileName,1, (PATINDEX('%.xlsx%', @SourceFileName)-1)), 8)),
	--CONVERT(date, @DataDate), 
	--@LoadDate,
	GETDATE(),
	--@CreatedDate,
	@CreatedBy,
	@CarrierName,
	@ACOName ,
	@ACOAttributedProviderName,
	@NPINumber ,
	@ACOAttributedProviderAddress1,
	@ACOAttributedProviderAddress2 ,
	@ACOAttributedProviderCity ,
	@ACOAttributedProviderState ,
	@ACOAttributedProviderZipcode ,
	@ACOAttributedProviderPhone,
	@MemberLastName ,
	@MemberFirstName ,
	@DwMemberID ,
	@CumbID ,
	@CardID ,
	@CardIdSeqNo ,
	@DateOfBirth ,
	@PulseScore ,
	@Status ,
	@MemberPhone ,
	@AcoAttributionEffectiveDate ,
	@AcoAttributionEndDate ,
	@MemberTerminationDate ,
	@LineOfBusiness ,
	@Product ,
	@PlanSponsorName ,
	@PlanSponsorControl ,
	@AdmitPotentiallyAvoidable ,
	@EventType ,
	@EventStageStatus ,
	@StayType ,
	@AdmissionType ,
	@NotificationDate ,
	@ExpectedAdmitDate,
	@ActualAdmitDate ,
	@ExpectedDischargeDate,
	@ActualDischargeDate,
	@DischargeDisposition ,
	@DiagnosisCode ,
	@DiagnosisDescription,
	@OtherComorbidDiagnosis1 ,
	@OtherComorbidDiagnosis2 ,
	@ProcedureCode ,
	@ProcedureDescription ,
	CASE WHEN @ProcedureStartDate = ''
	THEN null
	ELSE CONVERT(DATE, @ProcedureStartDate)
	END,
	@ProviderNameRole ,
	@FacilityNameRole ,
	@FacilityAddress ,
	@filler1 ,
	@filler2 ,
	@filler3  ,
	@filler4 ,
	@filler5,   
  	@AttrProviderGroup ,
	@PMENumber ,
	@IsReadmit,
	@HasReadmit ,
	@LenghthofStay ,
    @ReadmissionPredictor ,
	@CMSContract 
   );

 
END