
-- =============================================
-- Author:		Bing Yu
-- Create date: 09/08/2020
-- Description:	Insert Cigna MA AWV to DB
-- ============================================
CREATE PROCEDURE [adi].[ImporCignaMA_MedicationAdherenceDiabetes]
    @SrcFileName [varchar](100),
	@FileDate varchar(10),
  --[CreateDate] [datetime] NULL,
	@CreateBy [varchar] (100),
	@OriginalFileName [varchar],
	@LastUpdatedBy [varchar](100),
	--[LastUpdatedDate] [datetime] ,
	@DataDate varchar(10),
    @ContractID varchar(50) ,
    @PBP varchar(50) ,
    @Region varchar(50) ,
    @Market varchar(50) ,
@Current_YR_Fills varchar(50) ,
@PCP_NPI varchar(50) ,
@PCPLastName varchar(50) ,
@PCPFirstName varchar(50) ,
@PCP varchar(50) ,
@QNXT_PCPID varchar(50) ,
@PODName varchar(50) ,
@MemberID varchar(50) ,
@LastName varchar(50) ,
@FirstName varchar(50) ,
@TermDate varchar(12) ,
@LISCopayCategory varchar(50) ,
@DenominatorDaysYTD varchar(50) ,
@DaysCoveredYTD varchar(50) ,
@CURRENT_YEAR_PDC_YTD varchar(50) ,
@PDCR12 varchar(50) ,
@YR_prior_PDC_1 varchar(50) ,
@YR_prior_PDC_2 varchar(50) ,
@YR_prior_PDC_3 varchar(50) ,
@NonAdherentDaysRemaining varchar(50) ,
@NonAdherentDate varchar(12)  ,
@PossibleToMeet varchar(50) ,
@DrugClass varchar(50) ,
@MedicationName varchar(50) ,
@DaysSupply varchar(50) ,
@MedicationTier varchar(50) ,
@FirstFillDate varchar(12) ,
@LastFillDate varchar(12) ,
@NextFillDueDate varchar(12) ,
@PharmacyType varchar(50) ,
@PharmacyTypeDesc varchar(50) ,
@PatResdDescr varchar(50) ,
@PrimaryCareProvider varchar(50) ,
@Patient varchar(50) ,
@MedicationAdherenceData varchar(50) ,
@RecommendedActions varchar(50) ,
@OutreachOutcome varchar(50) ,
@DiscontinueReason varchar(50) ,
@FillsOutsideCignaPlan varchar(50) ,
@Barriers varchar(50) ,
@MedicationChanges varchar(50) ,
@AdditionalComments varchar(500) 
	
            
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	EXEC [ACDW_CLMS_CIGNA_MA].[adi].[ImporCignaMA_MedicationAdherenceDiabetes]
	 @SrcFileName ,
	@FileDate ,
  --[CreateDate] [datetime] NULL,
	@CreateBy ,
	@OriginalFileName ,
	@LastUpdatedBy ,
	--[LastUpdatedDate] [datetime] ,
	@DataDate ,
    @ContractID  ,
    @PBP  ,
    @Region  ,
    @Market  ,
@Current_YR_Fills  ,
@PCP_NPI  ,
@PCPLastName  ,
@PCPFirstName  ,
@PCP  ,
@QNXT_PCPID  ,
@PODName  ,
@MemberID  ,
@LastName  ,
@FirstName  ,
@TermDate  ,
@LISCopayCategory  ,
@DenominatorDaysYTD  ,
@DaysCoveredYTD  ,
@CURRENT_YEAR_PDC_YTD  ,
@PDCR12  ,
@YR_prior_PDC_1  ,
@YR_prior_PDC_2  ,
@YR_prior_PDC_3  ,
@NonAdherentDaysRemaining  ,
@NonAdherentDate   ,
@PossibleToMeet  ,
@DrugClass  ,
@MedicationName  ,
@DaysSupply  ,
@MedicationTier  ,
@FirstFillDate  ,
@LastFillDate  ,
@NextFillDueDate  ,
@PharmacyType  ,
@PharmacyTypeDesc  ,
@PatResdDescr  ,
@PrimaryCareProvider  ,
@Patient  ,
@MedicationAdherenceData  ,
@RecommendedActions  ,
@OutreachOutcome  ,
@DiscontinueReason  ,
@FillsOutsideCignaPlan  ,
@Barriers  ,
@MedicationChanges  ,
@AdditionalComments  


END




