-- =============================================
-- Author:		Bing Yu
-- Create date: 12/29/2020
-- Description:	Insert HL7 ORU to DB
-- =============================================
CREATE PROCEDURE [adi].[ImportIB_API_Patient]  
   -- @LoadDate date NOT ,
	@DataDate varchar(10) ,
	@SrcFileName varchar(100) ,
	--@CreatedDate datetime NOT ,
	@CreatedBy varchar(50)  ,
	--@LastUpdatedDate datetime NOT ,
	@LastUpdatedBy varchar(50) ,
	@Email varchar(50) ,
	@Departmentid varchar(10) ,
	@Portalaccessgiven varchar(10) ,
	@Driverslicense varchar(10) ,
	@Contactpreference_Appointment_Email varchar(10) ,
	@Contactpreference_Appointment_Sms varchar(10) ,
	@Contactpreference_billing_phone varchar(10) ,
	@Contactpreference_Announcement_Phone varchar(10) ,
	@Contactpreference_Lab_Sms varchar(10) ,
	@Guarantordob varchar(10) ,
	@Zip varchar(10) ,
	@Guarantoraddresssameaspatient varchar(10) ,
	@Portaltermsonfile varchar(10) ,
	@Status varchar(10) ,
	@LastName varchar(50) ,
	@Guarantorfirstname varchar(50) ,
	@City varchar(50) ,
	@Guarantoremail varchar(50) ,
	@Middlename varchar(50) ,
	@Sex varchar(10) ,
	@Privacyinformationverified varchar(10) ,
	@Primarydepartmentid int ,
	@Contactpreference_lab_email varchar(10) ,
	@Contactpreference_announcement_sms varchar(10) ,
	@Emailexists varchar(10) ,
	@Primaryproviderid int ,
	@Patientphoto varchar(10) ,
	@Contactpreference_billing_email varchar(10) ,
	@Contactpreference_announcement_email varchar(10) ,
	@Registrationdate varchar(10),
	@Caresummarydeliverypreference varchar(50) ,
	@Guarantorlastname varchar(50) ,
	@FirstName varchar(50) ,
	@Guarantorcountrycode varchar(10) ,
	@Contactpreference_appointment_phone varchar(10) ,
	@Patientid varchar(10) ,
	@DOB varchar(10) ,
	@Guarantorrelationshiptopatient int ,
	@Address1 varchar(100) ,
	@Contactpreference_billing_sms varchar(10) ,
	@CountryCode varchar(10) ,
	@GuarantorMiddleName varchar(10) ,
	@ConsentToText varchar(10) ,
	@Countrycode3166 varchar(50) ,
	@Contactpreference_Lab_Phone varchar(10) ,
	@Assignedsexatbirth varchar(10) ,
	@Guarantorcountrycode3166 varchar(10) ,
	@EMR_ID varchar(25) ,
	@EMR_VERSION varchar(25) ,
	@ACEMbrKey varchar(50) 
          
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	EXEC DEV_ACECAREDW.[adi].[ImportIB_API_Patient]
	 -- @LoadDate date NOT ,
	@DataDate  ,
	@SrcFileName  ,
	--@CreatedDate datetime NOT ,
	@CreatedBy   ,
	--@LastUpdatedDate datetime NOT ,
	@LastUpdatedBy  ,
	@Email  ,
	@Departmentid  ,
	@Portalaccessgiven  ,
	@Driverslicense  ,
	@Contactpreference_Appointment_Email  ,
	@Contactpreference_Appointment_Sms  ,
	@Contactpreference_billing_phone  ,
	@Contactpreference_Announcement_Phone  ,
	@Contactpreference_Lab_Sms  ,
	@Guarantordob  ,
	@Zip  ,
	@Guarantoraddresssameaspatient  ,
	@Portaltermsonfile  ,
	@Status  ,
	@LastName  ,
	@Guarantorfirstname  ,
	@City  ,
	@Guarantoremail  ,
	@Middlename  ,
	@Sex  ,
	@Privacyinformationverified  ,
	@Primarydepartmentid ,
	@Contactpreference_lab_email  ,
	@Contactpreference_announcement_sms  ,
	@Emailexists  ,
	@Primaryproviderid  ,
	@Patientphoto  ,
	@Contactpreference_billing_email  ,
	@Contactpreference_announcement_email  ,
	@Registrationdate ,
	@Caresummarydeliverypreference  ,
	@Guarantorlastname  ,
	@FirstName  ,
	@Guarantorcountrycode  ,
	@Contactpreference_appointment_phone  ,
	@Patientid  ,
	@DOB  ,
	@Guarantorrelationshiptopatient ,
	@Address1  ,
	@Contactpreference_billing_sms  ,
	@CountryCode  ,
	@GuarantorMiddleName  ,
	@ConsentToText  ,
	@Countrycode3166  ,
	@Contactpreference_Lab_Phone  ,
	@Assignedsexatbirth  ,
	@Guarantorcountrycode3166  ,
	@EMR_ID  ,
	@EMR_VERSION  ,
	@ACEMbrKey 
	
END

