
-- =============================================
-- Author:		Bing Yu
-- Create date: 04/04/2019
-- Description:	Insert ECP Claim file to DB
-- =============================================
CREATE PROCEDURE [adi].[ImportAssignedMarketGapReport]
    --loadDate] [date]  ,
	@DataDate VARCHAR(10), 
	--[date] ,
	@OriginalFileName varchar(100)  ,
	@SrcFileName varchar(100)  ,
	--@CreatedDate [datetime2](7)  ,
	@CreatedBy varchar(50)  ,
	--[LastUpdatedDate] [datetime2](7)  ,
	@LastUpdatedBy varchar(50)  ,
	@ACCOUNT_ID varchar(50) ,
	@GROUP_NAME varchar(50) ,
	@PRACTICE_NAME varchar(50) ,
	@Member_Id varchar(50) ,
	@MEDICAID_NO varchar(50) ,
	@Lastname varchar(50) ,
	@Firstname varchar(50) ,
	@MEMB_GENDER varchar(50) ,
	@DOB varchar(12) ,
	@Telephone varchar(50) ,
	@Measure_Id varchar(50) ,
	@Measure_Description varchar(500) ,
	@Submeasure_Id varchar(200) ,
	@Submeasure_Description varchar(500) ,
	@Compliance_Date varchar(12) ,
	@COMPLIANCE varchar(50) ,
	@MBR_HIST_LOB varchar(50) ,
	@MBR_HIST_LOB_DESC varchar(50) ,
	@PLAN_CODE varchar(50) ,
	@PLAN_DESC varchar(50) ,
	@Assigned_Provider_TIN_Name varchar(50) ,
	@Assigned_Provider_Medicaid_Id varchar(50) ,
	@Assigned_Provider_Lastname varchar(50) ,
	@Assigned_Provider_Firstname varchar(50) ,
	@Assigned_Provider_Address1 varchar(50) ,
	@Assigned_Provider_Address2 varchar(50) ,
	@Assigned_Provider_City varchar(50) ,
	@Assigned_Provider_County varchar(50) ,
	@Assigned_Provider_State varchar(50) ,
	@Assigned_Provider_Zipcode varchar(50) ,
	@Assigned_Provider_Telephone varchar(50) ,
	@Assigned_Provider_Last_Visit varchar(50) ,
	@Assigned_Provider_TIN varchar(50) ,
	@Assigned_Provider_NPI varchar(50) ,
	@Assigned_Provider_MPIN varchar(50) ,
	@Assigned_Provider_Id varchar(50) ,
	@Extract_Timestamp varchar(50) ,
	@SMART_Load_Timestamp varchar(50) ,
	@ReviewSet varchar(50) ,
	@REPORTDATE varchar(50) ,
	@Meas_Num varchar(50) ,
	@RowNum varchar(50) ,
    @STATE varchar(50) ,
	@LineBusiness varchar(50),
	@MEMBER_ADDRESS_1 varchar(100),
    @MEMBER_ADDRESS_2 varchar(100),
	@MEMBER_CITY varchar(100),
	@MEMBER_STATE varchar(20),
	@member_zip varchar(10),
	@MEMBER_PHONE varchar(15),
	@MEMBER_ALT_PHONE varchar(15)

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	EXEC [ACDW_CLMS_UHC].[adi].[ImportAssignedMarketGapReport]
	  --loadDate] [date]  ,
	@DataDate , 
	--[date] ,
	@OriginalFileName   ,
	@SrcFileName   ,
	--@CreatedDate [datetime2](7)  ,
	@CreatedBy   ,
	--[LastUpdatedDate] [datetime2](7)  ,
	@LastUpdatedBy   ,
	@ACCOUNT_ID  ,
	@GROUP_NAME  ,
	@PRACTICE_NAME  ,
	@Member_Id  ,
	@MEDICAID_NO  ,
	@Lastname  ,
	@Firstname  ,
	@MEMB_GENDER  ,
	@DOB  ,
	@Telephone  ,
	@Measure_Id  ,
	@Measure_Description  ,
	@Submeasure_Id  ,
	@Submeasure_Description  ,
	@Compliance_Date  ,
	@COMPLIANCE  ,
	@MBR_HIST_LOB  ,
	@MBR_HIST_LOB_DESC  ,
	@PLAN_CODE  ,
	@PLAN_DESC  ,
	@Assigned_Provider_TIN_Name  ,
	@Assigned_Provider_Medicaid_Id  ,
	@Assigned_Provider_Lastname  ,
	@Assigned_Provider_Firstname  ,
	@Assigned_Provider_Address1  ,
	@Assigned_Provider_Address2  ,
	@Assigned_Provider_City  ,
	@Assigned_Provider_County  ,
	@Assigned_Provider_State  ,
	@Assigned_Provider_Zipcode  ,
	@Assigned_Provider_Telephone  ,
	@Assigned_Provider_Last_Visit  ,
	@Assigned_Provider_TIN  ,
	@Assigned_Provider_NPI  ,
	@Assigned_Provider_MPIN  ,
	@Assigned_Provider_Id  ,
	@Extract_Timestamp  ,
	@SMART_Load_Timestamp  ,
	@ReviewSet  ,
	@REPORTDATE  ,
	@Meas_Num  ,
	@RowNum  ,
    @STATE  ,
	@LineBusiness ,
	@MEMBER_ADDRESS_1 ,
    @MEMBER_ADDRESS_2 ,
	@MEMBER_CITY,
	@MEMBER_STATE ,
	@member_zip ,
	@MEMBER_PHONE ,
	@MEMBER_ALT_PHONE 

end
