-- =============================================
-- Author:		Bing Yu
-- Create date: 12/29/2020
-- Description:	Insert HL7 ORU to DB
-- =============================================
CREATE PROCEDURE [adi].[ImportHL7_ORU_OBR]  
    @OBR0_SegmentType varchar(3)  ,
	@OBR1_SequenceNum varchar(4)  ,
	--@LoadDate date NOT  ,
	@DataDate varchar(10) ,
	@SrcFileName varchar(100) ,
	--@CreatedDate datetime   ,
	@CreatedBy varchar(50)  ,
	--@LastUpdatedDate datetime N ,
	@LastUpdatedBy varchar(50)  ,
	@OBR2_PlacerOrderNumber varchar(75)  ,
	@OBR3_FillerOrderNumber varchar(75)  ,
	@OBR4_UniversalServiceID varchar(200)  ,
	@OBR5_Priority varchar(2)  ,
	@OBR6_RequestedDateTime varchar(75)  ,
	@OBR7_ObservationDateTime varchar(75)  ,
	@OBR8_ObservationEndDateTime varchar(75)  ,
	@OBR9_CollectionVolume varchar(20)  ,
	@OBR10_CollectorIdentifier varchar(60)  ,
	@OBR11_ActionCode char(1)  ,
	@OBR12_DangerCode varchar(3)  ,
	@OBR13_RelevantClinicalInformation varchar(3)  ,
	@OBR14_SpecimenRcvdDateTime varchar(3)  ,
	@OBR15_SpecimenSource varchar(3)  ,
	@OBR17_OrderCallbackPhoneNum varchar(3)  ,
	@OBR18_PlacerField1 varchar(60)  ,
	@OBR19_PlacerField2 varchar(3)  ,
	@OBR20_Filler1 varchar(100)  ,
	@OBR21_Filler2 varchar(3)  ,
	@OBR22_ResultReportedDatetime varchar(26)  ,
	@OBR23_ChargeToPractice varchar(40)  ,
	@OBR24_DiagnosticServSectID varchar(10)  ,
	@OBR25_TestStatus char(1)  ,
	@MSH10_MessageControlID varchar(200)  ,
	@OBR20_Filler1_1 varchar(50)  ,
	@OBR20_Filler1_2 varchar(50)  ,
	@OBR20_Filler1_3 varchar(10)  ,
	@OBR16_OrderingProvider_1 varchar(50)  ,
	@OBR16_OrderingProvider_2 varchar(50)  ,
	@OBR16_OrderingProvider_3 varchar(50)  ,
	@OBR16_OrderingProvider_13 varchar(50)  ,
	@OBR4_UniversalServiceID_1 varchar(10)  ,
	@OBR4_UniversalServiceID_2 varchar(50)  ,
	@OBR4_UniversalServiceID_3 varchar(10)  
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    EXEC [DEV_ACECAREDW].[adi].[ImportHL7_ORU_OBR]
	 @OBR0_SegmentType  ,
	@OBR1_SequenceNum   ,
	--@LoadDate date NOT  ,
	@DataDate  ,
	@SrcFileName  ,
	--@CreatedDate datetime   ,
	@CreatedBy   ,
	--@LastUpdatedDate datetime N ,
	@LastUpdatedBy   ,
	@OBR2_PlacerOrderNumber ,
	@OBR3_FillerOrderNumber  ,
	@OBR4_UniversalServiceID   ,
	@OBR5_Priority  ,
	@OBR6_RequestedDateTime   ,
	@OBR7_ObservationDateTime   ,
	@OBR8_ObservationEndDateTime ,
	@OBR9_CollectionVolume  ,
	@OBR10_CollectorIdentifier   ,
	@OBR11_ActionCode   ,
	@OBR12_DangerCode   ,
	@OBR13_RelevantClinicalInformation  ,
	@OBR14_SpecimenRcvdDateTime  ,
	@OBR15_SpecimenSource   ,
	@OBR17_OrderCallbackPhoneNum  ,
	@OBR18_PlacerField1   ,
	@OBR19_PlacerField2  ,
	@OBR20_Filler1   ,
	@OBR21_Filler2  ,
	@OBR22_ResultReportedDatetime  ,
	@OBR23_ChargeToPractice   ,
	@OBR24_DiagnosticServSectID ,
	@OBR25_TestStatus  ,
	@MSH10_MessageControlID  ,
	@OBR20_Filler1_1  ,
	@OBR20_Filler1_2 ,
	@OBR20_Filler1_3   ,
	@OBR16_OrderingProvider_1  ,
	@OBR16_OrderingProvider_2 ,
	@OBR16_OrderingProvider_3   ,
	@OBR16_OrderingProvider_13 ,
	@OBR4_UniversalServiceID_1   ,
	@OBR4_UniversalServiceID_2 ,
	@OBR4_UniversalServiceID_3 
	
END

