CREATE TABLE [adi].[ACE8x8Allinteractions] (
    [SrcFileName]               VARCHAR (100) NULL,
    [CreateDate]                DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                  VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]          VARCHAR (100) NULL,
    [LastUpdatedBy]             VARCHAR (100) NULL,
    [LastUpdatedDate]           DATETIME      NULL,
    [media-type]                VARCHAR (50)  NULL,
    [channel-obj-id]            VARCHAR (50)  NULL,
    [queue-name]                VARCHAR (50)  NULL,
    [interaction-id]            VARCHAR (50)  NULL,
    [orig-interaction-id]       VARCHAR (50)  NULL,
    [origination]               VARCHAR (50)  NULL,
    [destination-original]      VARCHAR (50)  NULL,
    [destination-translated]    VARCHAR (50)  NULL,
    [customer-name]             VARCHAR (50)  NULL,
    [case-id]                   VARCHAR (50)  NULL,
    [interaction-direction]     VARCHAR (50)  NULL,
    [interaction-type]          VARCHAR (50)  NULL,
    [dial-code]                 VARCHAR (50)  NULL,
    [dial-text]                 VARCHAR (50)  NULL,
    [create-timestamp]          DATETIME      NULL,
    [agent-id]                  VARCHAR (50)  NULL,
    [agent-name]                VARCHAR (50)  NULL,
    [accept-timestamp]          DATETIME      NULL,
    [process-time]              INT           NULL,
    [post-process-time]         INT           NULL,
    [total-time]                INT           NULL,
    [abandon-timestamp]         VARCHAR (50)  NULL,
    [voice-message-left]        VARCHAR (50)  NULL,
    [recording-filename]        VARCHAR (50)  NULL,
    [ivr-treatment-time]        VARCHAR (50)  NULL,
    [transfer-from]             VARCHAR (50)  NULL,
    [conference-from]           VARCHAR (50)  NULL,
    [max-hold-time]             VARCHAR (50)  NULL,
    [hold-count]                VARCHAR (50)  NULL,
    [total-hold-time]           VARCHAR (50)  NULL,
    [call-leg1-post-dial-delay] VARCHAR (50)  NULL,
    [call-leg2-post-dial-delay] VARCHAR (50)  NULL,
    [call-leg1-answer-time]     VARCHAR (50)  NULL,
    [call-leg2-answer-time]     VARCHAR (50)  NULL,
    [call-leg1-sip-id]          VARCHAR (50)  NULL,
    [call-leg2-sip-id]          VARCHAR (50)  NULL,
    [inbound-sip-id]            VARCHAR (50)  NULL,
    [notes]                     VARCHAR (50)  NULL,
    [campaign-name]             VARCHAR (50)  NULL,
    [record-id]                 VARCHAR (50)  NULL,
    [record-status]             VARCHAR (50)  NULL,
    [disposition-code]          VARCHAR (50)  NULL,
    [ext-trans-data]            VARCHAR (50)  NULL,
    [wrap-up-code]              VARCHAR (50)  NULL,
    [wrap-up-text]              VARCHAR (100) NULL,
    [agent-accept-timestamp]    DATETIME      NULL,
    [agent-abandon-timestamp]   DATETIME      NULL,
    [trans-rec-num]             VARCHAR (50)  NULL,
    [is-interaction-completed]  VARCHAR (10)  NULL,
    [Status]                    CHAR (1)      CONSTRAINT [df_ReportStatus] DEFAULT ((0)) NULL,
    [ACE8x8ReportLogKey]        INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_ACE8x8ReportLogs] PRIMARY KEY CLUSTERED ([ACE8x8ReportLogKey] ASC)
);

