CREATE TABLE [adi].[ACE_8x8ReportLogs] (
    [SrcFileName]               VARCHAR (100) NULL,
    [CreateDate]                DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                  VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]          VARCHAR (100) NULL,
    [LastUpdatedBy]             VARCHAR (100) NULL,
    [LastUpdatedDate]           DATETIME      NULL,
    [media-type]                VARCHAR (20)  NULL,
    [channel-obj-id]            VARCHAR (50)  NULL,
    [queue-name]                VARCHAR (50)  NULL,
    [interaction-id]            VARCHAR (50)  NULL,
    [orig-interaction-id]       VARCHAR (50)  NULL,
    [origination-phone]         VARCHAR (50)  NULL,
    [destination-original]      VARCHAR (50)  NULL,
    [destination-translated]    VARCHAR (50)  NULL,
    [customer-name]             VARCHAR (50)  NULL,
    [case-id]                   VARCHAR (50)  NULL,
    [interaction-direction]     VARCHAR (50)  NULL,
    [interaction-type]          VARCHAR (50)  NULL,
    [dial-code]                 VARCHAR (50)  NULL,
    [dial-text]                 VARCHAR (500) NULL,
    [create-timestamp]          DATETIME      NULL,
    [agent-id]                  VARCHAR (50)  NULL,
    [agent-name]                VARCHAR (50)  NULL,
    [accept-timestamp]          DATETIME      NULL,
    [agent-accept-timestamp]    DATETIME      NULL,
    [process-time]              INT           NULL,
    [post-process-time]         INT           NULL,
    [total-time]                INT           NULL,
    [abandon-timestamp]         DATETIME      NULL,
    [agent-abandon-timestamp]   DATETIME      NULL,
    [voice-message-left]        BIT           NULL,
    [recording-filename]        VARCHAR (50)  NULL,
    [ivr-treatment-time]        INT           NULL,
    [transfer-from]             VARCHAR (50)  NULL,
    [conference-from]           VARCHAR (50)  NULL,
    [max-hold-time]             INT           NULL,
    [hold-count]                INT           NULL,
    [total-hold-time]           INT           NULL,
    [call-leg1-post-dial-delay] INT           NULL,
    [call-leg2-post-dial-delay] INT           NULL,
    [call-leg1-answer-time]     DECIMAL (18)  NULL,
    [call-leg2-answer-time]     DECIMAL (18)  NULL,
    [call-leg1-sip-id]          VARCHAR (10)  NULL,
    [call-leg2-sip-id]          VARCHAR (10)  NULL,
    [inbound-sip-id]            VARCHAR (50)  NULL,
    [notes]                     VARCHAR (500) NULL,
    [campaign-name]             VARCHAR (100) NULL,
    [record-id]                 VARCHAR (50)  NULL,
    [record-status]             VARCHAR (50)  NULL,
    [disposition-code]          VARCHAR (50)  NULL,
    [ext-trans-data]            VARCHAR (100) NULL,
    [wrap-up-code]              VARCHAR (50)  NULL,
    [wrap-up-text]              VARCHAR (100) NULL,
    [trans-rec-num]             VARCHAR (50)  NULL,
    [is-interaction-completed]  VARCHAR (10)  NULL,
    [Status]                    CHAR (1)      CONSTRAINT [df_Status] DEFAULT ((0)) NULL,
    [ACE_8x8ReportLogKey]       INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_ACE_8x8ReportLogs] PRIMARY KEY CLUSTERED ([ACE_8x8ReportLogKey] ASC)
);

