CREATE TABLE [adi].[AETCOM_CostbyMCC_AllMCC] (
    [AETCOM_CostbyMCC_AllMCC_Key]              INT             IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                              VARCHAR (100)   NOT NULL,
    [LoadDate]                                 DATE            NOT NULL,
    [DataDate]                                 DATE            NOT NULL,
    [CreatedDate]                              DATETIME        CONSTRAINT [DF_adiAETCOM_CostbyMCC_AllMCC_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                                VARCHAR (50)    CONSTRAINT [DF_adiAETCOM_CostbyMCC_AllMCC_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                          DATETIME        CONSTRAINT [DF_adiAETCOM_CostbyMCC_AllMCC_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                            VARCHAR (50)    CONSTRAINT [DF_adiAETCOM_CostbyMCC_AllMCC_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [AttributedProviderID]                     VARCHAR (20)    NULL,
    [AttributedProviderName]                   VARCHAR (50)    NULL,
    [Paid]                                     MONEY           NULL,
    [Paid_ACOProvider]                         MONEY           NULL,
    [Paid_Non_ACOProviderInNetwork]            MONEY           NULL,
    [Paid_ParProviderNotInNetwork]             MONEY           NULL,
    [Paid_AetnaNon_Par_Provider]               MONEY           NULL,
    [PercentPaid_ACOProvider]                  DECIMAL (10, 2) NULL,
    [PercentPaid_NonACOProviderInNetwork]      DECIMAL (10, 2) NULL,
    [PercentPaid_ParProviderNotInNetwork]      DECIMAL (10, 2) NULL,
    [PercentPaid_AetnaNonParProvider]          DECIMAL (10, 2) NULL,
    [DistintMembersWithClaims]                 VARCHAR (50)    NULL,
    [Members_ACO_Provider]                     VARCHAR (50)    NULL,
    [Members_Non_ACOProviderInNetwork]         VARCHAR (50)    NULL,
    [Members_ParProviderNotInNetwork]          VARCHAR (50)    NULL,
    [Members_AetnaNon_ParProvider]             VARCHAR (50)    NULL,
    [PercentMembers_ACOProvider]               DECIMAL (10, 2) NULL,
    [PercentMembers_NonACO_ProviderInNetwork]  DECIMAL (10, 2) NULL,
    [PercentMembers_ParProviderNot_In_Network] DECIMAL (10, 2) NULL,
    [PercentMembers_Aetna_Non_ParProvider]     DECIMAL (10, 2) NULL,
    [DOS]                                      VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([AETCOM_CostbyMCC_AllMCC_Key] ASC)
);

