CREATE TABLE [adi].[LabCorp_MemberSend] (
    [First_Name]              VARCHAR (50) NOT NULL,
    [Middle_Name]             VARCHAR (50) NULL,
    [Last_Name]               VARCHAR (50) NOT NULL,
    [DOB]                     DATE         NOT NULL,
    [Gender]                  VARCHAR (10) NULL,
    [Race_code]               VARCHAR (5)  NULL,
    [DriversLicenseNumber]    VARCHAR (50) NULL,
    [DriversLicenseState]     VARCHAR (50) NULL,
    [SSN9]                    VARCHAR (10) NULL,
    [SSN4]                    VARCHAR (5)  NULL,
    [MRN]                     VARCHAR (50) NULL,
    [Ordering_Account_Number] VARCHAR (50) NULL,
    [Address_Line1]           VARCHAR (50) NULL,
    [Address_Line2]           VARCHAR (50) NULL,
    [city]                    VARCHAR (50) NULL,
    [state]                   VARCHAR (50) NULL,
    [zip5]                    VARCHAR (10) NULL,
    [zip4]                    VARCHAR (10) NULL,
    [country]                 VARCHAR (50) NULL,
    [Primary_phone]           VARCHAR (50) NULL,
    [CellPhone]               VARCHAR (50) NULL,
    [Home_Phone]              VARCHAR (50) NULL,
    [Email_Address]           VARCHAR (50) NULL,
    [Payer_name]              VARCHAR (50) NOT NULL,
    [Payor_group_Number]      VARCHAR (50) NULL,
    [Member_ID]               VARCHAR (50) NOT NULL,
    [Subscriber_ID]           VARCHAR (50) NOT NULL,
    [Unique_Request_ID]       VARCHAR (50) NOT NULL,
    [Record_Indicator]        VARCHAR (5)  NOT NULL,
    [SendDate]                DATE         NULL
);

