CREATE TABLE [adi].[MbrAetCom] (
    [mbrAetComMbr]                                INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                                 VARCHAR (100) NOT NULL,
    [LoadDate]                                    DATE          NOT NULL,
    [DataDate]                                    DATE          NOT NULL,
    [CreatedDate]                                 DATETIME      CONSTRAINT [DF_adiMbrAetCom_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                                   VARCHAR (50)  CONSTRAINT [DF_adiMbrAetCom_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                             DATETIME      CONSTRAINT [DF_adiMbrAetCom_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                               VARCHAR (50)  CONSTRAINT [DF_adiMbrAetCom_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [MEMBER_ID]                                   VARCHAR (20)  NULL,
    [EffectiveMonth]                              VARCHAR (10)  NULL,
    [Prefix_Name]                                 VARCHAR (5)   NULL,
    [LastName]                                    VARCHAR (30)  NULL,
    [Member_First_Name]                           VARCHAR (30)  NULL,
    [Member_Suffix_Name]                          VARCHAR (5)   NULL,
    [Member_Gender]                               CHAR (1)      NULL,
    [Member_Date_of_Birth]                        DATE          NULL,
    [Member_Address_Line1]                        VARCHAR (35)  NULL,
    [Member_Address_Line2]                        VARCHAR (35)  NULL,
    [Member_City]                                 VARCHAR (30)  NULL,
    [Member_State]                                CHAR (2)      NULL,
    [Member_County_Code]                          VARCHAR (5)   NULL,
    [Member_Zipcode]                              VARCHAR (5)   NULL,
    [Member_PhoneNum]                             VARCHAR (10)  NULL,
    [Member_Source_Member_ID]                     VARCHAR (22)  NULL,
    [Member_Relationship_to_Employee]             CHAR (1)      NULL,
    [Members_SSN]                                 VARCHAR (11)  NULL,
    [ps_unique_id]                                VARCHAR (16)  NULL,
    [customer_nbr]                                VARCHAR (8)   NULL,
    [group_nbr]                                   VARCHAR (8)   NULL,
    [subgroup_nbr]                                VARCHAR (8)   NULL,
    [account_nbr]                                 VARCHAR (5)   NULL,
    [Employee_Last_Name]                          VARCHAR (30)  NULL,
    [Employee_First_Name_or_Initial]              VARCHAR (30)  NULL,
    [Employee_Gender]                             CHAR (1)      NULL,
    [Employee_Date_of_Birth]                      VARCHAR (10)  NULL,
    [Employee_Zip_Code]                           VARCHAR (5)   NULL,
    [Employee_State]                              CHAR (2)      NULL,
    [Employee_County_Code]                        VARCHAR (5)   NULL,
    [Employee_SSN]                                VARCHAR (11)  NULL,
    [Source_System_Platform]                      CHAR (2)      NULL,
    [General_Category_of_Health_Plan]             CHAR (2)      NULL,
    [Line_of_Business]                            CHAR (2)      NULL,
    [Funding_Arrangement]                         CHAR (1)      NULL,
    [Coverage_Type_Code]                          CHAR (1)      NULL,
    [Network_Identifier]                          VARCHAR (5)   NULL,
    [Customer_Segment]                            CHAR (3)      NULL,
    [Medical_Indicator]                           CHAR (1)      NULL,
    [Drug_Indicator]                              CHAR (1)      NULL,
    [Substance_Abuse_Indicator]                   CHAR (1)      NULL,
    [Mental_Health_Indicator]                     CHAR (1)      NULL,
    [Individual_Original_Effective_date_at_Aetna] VARCHAR (10)  NULL,
    [PCP_Provider_Tax_ID_Number_TIN]              VARCHAR (9)   NULL,
    [PCP_Provider_PIN]                            VARCHAR (7)   NULL,
    [PCP_Provider_Name_Last_or_Full]              VARCHAR (40)  NULL,
    [PCP_Provider_Street_Address_1]               VARCHAR (35)  NULL,
    [PCP_Provider_Street_Address_2]               VARCHAR (35)  NULL,
    [PCP_Provider_City]                           VARCHAR (30)  NULL,
    [PCP_Provider_State]                          VARCHAR (2)   NULL,
    [PCP_Provider_Zip_Code]                       VARCHAR (5)   NULL,
    [PCP_Provider_NPI_Number]                     VARCHAR (22)  NULL,
    [PCP_Provider_Specialty_Code]                 VARCHAR (5)   NULL,
    [Organization_ID]                             VARCHAR (10)  NULL,
    [From_attribution_date_of_first_visit]        DATE          NULL,
    [From_attribution_date_of_last_visit]         DATE          NULL,
    [From_attribution_number_of_visits]           INT           NULL,
    [Attributed_Provider_Tax_ID_Number_TIN]       VARCHAR (9)   NULL,
    [Attributed_Provider_PIN]                     VARCHAR (7)   NULL,
    [Attributed_Provider_Name_Last_or_Full]       VARCHAR (40)  NULL,
    [Attributed_Provider_Street_Address_1]        VARCHAR (35)  NULL,
    [Attributed_Provider_Street_Address_2]        VARCHAR (35)  NULL,
    [Attributed_Provider_City]                    VARCHAR (30)  NULL,
    [Attributed_Provider_State]                   CHAR (2)      NULL,
    [Attributed_Provider_Zip_Code]                VARCHAR (5)   NULL,
    [Attributed_Provider_NPI_Number]              VARCHAR (22)  NULL,
    [Attributed_Provider_Specialty_Code]          VARCHAR (5)   NULL,
    [Attribution_Record_status]                   CHAR (1)      NULL,
    [Attribution_Original_Effective_Date]         DATE          NULL,
    [Attribution_Cancel_Date]                     DATE          NULL,
    [Member_Cumb_ID]                              VARCHAR (22)  NULL,
    [Employe_Cumb_ID]                             VARCHAR (22)  NULL,
    [Middle_Name]                                 VARCHAR (11)  NULL,
    [Individual_ID]                               VARCHAR (20)  NULL,
    [Pulse_score_Point_in_time]                   VARCHAR (5)   NULL,
    [ERGProspective_score_point_in_time]          VARCHAR (5)   NULL,
    [ERG_Retrospective_score_point_in_time]       VARCHAR (5)   NULL,
    [Aetna_Line_of_Business]                      CHAR (2)      NULL,
    [Aetna_Card_ID]                               VARCHAR (20)  NULL,
    [Employer_Name]                               VARCHAR (40)  NULL,
    [Current_Record_Indicator]                    CHAR (1)      NULL,
    [Sequence_Number]                             VARCHAR (11)  NULL,
    [Duplicate_Indicator]                         CHAR (1)      NULL,
    [Attribution_Type]                            CHAR (3)      NULL,
    [Risk]                                        CHAR (3)      NULL,
    [Organization_Code]                           VARCHAR (10)  NULL,
    [End_of_record_marker]                        CHAR (1)      NULL,
    [OriginalFileName]                            VARCHAR (100) NULL,
    [MbrLoadStatus]                               TINYINT       CONSTRAINT [DF_adiMbrAetComMbrloadStatus] DEFAULT ((0)) NOT NULL,
    [PLAN_ID]                                     VARCHAR (5)   NULL,
    [Hcontract_PBP_ID]                            VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([mbrAetComMbr] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ndx_MbrAetCom_MbrLoadStatus]
    ON [adi].[MbrAetCom]([MbrLoadStatus] ASC);


GO
CREATE NONCLUSTERED INDEX [ndx_adiMbrAetCom_EffMonth]
    ON [adi].[MbrAetCom]([EffectiveMonth] ASC)
    INCLUDE([MEMBER_ID], [Pulse_score_Point_in_time]);

