CREATE TABLE [adi].[MbrUhcNewMembers] (
    [MbrUhcNewMembersKey]    INT           IDENTITY (1, 1) NOT NULL,
    [mbrFName]               VARCHAR (75)  NULL,
    [mbrMName]               VARCHAR (75)  NULL,
    [mbrLName]               VARCHAR (75)  NULL,
    [UHC_SUBSCRIBER_ID]      VARCHAR (50)  NOT NULL,
    [CLASS]                  VARCHAR (20)  NULL,
    [PLAN_ID]                VARCHAR (20)  NULL,
    [PRODUCT_CODE]           VARCHAR (20)  NULL,
    [SUBGRP_ID]              VARCHAR (20)  NULL,
    [SUBGRP_NAME]            VARCHAR (100) NULL,
    [MEDICARE_ID]            VARCHAR (12)  NULL,
    [MEDICAID_ID]            VARCHAR (9)   NULL,
    [AGE]                    INT           NULL,
    [DATE_OF_BIRTH]          DATE          NULL,
    [GENDER]                 VARCHAR (20)  NULL,
    [RELATIONSHIP_CODE]      VARCHAR (20)  NULL,
    [LANG_CODE]              VARCHAR (20)  NULL,
    [MEMBER_HOME_ADDRESS]    VARCHAR (100) NULL,
    [MEMBER_HOME_ADDRESS2]   VARCHAR (100) NULL,
    [MEMBER_HOME_CITY]       VARCHAR (40)  NULL,
    [MEMBER_HOME_STATE]      VARCHAR (20)  NULL,
    [MEMBER_HOME_ZIP]        VARCHAR (15)  NULL,
    [MEMBER_HOME_PHONE]      VARCHAR (25)  NULL,
    [MEMBER_MAIL_ADDRESS]    VARCHAR (100) NULL,
    [MEMBER_MAIL_ADDRESS2]   VARCHAR (100) NULL,
    [MEMBER_MAIL_CITY]       VARCHAR (40)  NULL,
    [MEMBER_MAIL_STATE]      VARCHAR (20)  NULL,
    [MEMBER_MAIL_ZIP]        VARCHAR (15)  NULL,
    [MEMBER_MAIL_PHONE]      VARCHAR (25)  NULL,
    [MEMBER_COUNTY_CODE]     VARCHAR (10)  NULL,
    [MEMBER_COUNTY]          VARCHAR (50)  NULL,
    [MEMBER_BUS_PHONE]       VARCHAR (25)  NULL,
    [DUAL_COV_FLAG]          VARCHAR (20)  NULL,
    [MEMBER_ORG_EFF_DATE]    DATE          NULL,
    [MEMBER_CONT_EFF_DATE]   DATE          NULL,
    [MEMBER_CUR_EFF_DATE]    DATE          NULL,
    [MEMBER_CUR_TERM_DATE]   DATE          NULL,
    [CLASS_PLAN_ID]          VARCHAR (20)  NULL,
    [RESP_LAST_NAME]         VARCHAR (75)  NULL,
    [RESP_FIRST_NAME]        VARCHAR (75)  NULL,
    [RESP_ADDRESS]           VARCHAR (100) NULL,
    [RESP_ADDRESS2]          VARCHAR (100) NULL,
    [RESP_CITY]              VARCHAR (40)  NULL,
    [RESP_STATE]             VARCHAR (20)  NULL,
    [RESP_ZIP]               VARCHAR (15)  NULL,
    [RESP_PHONE]             VARCHAR (25)  NULL,
    [BROKER_ID]              VARCHAR (50)  NULL,
    [PCP_UHC_ID]             VARCHAR (50)  NULL,
    [PCP_FIRST_NAME]         VARCHAR (75)  NULL,
    [PCP_LAST_NAME]          VARCHAR (75)  NULL,
    [PCP_MPIN]               VARCHAR (50)  NULL,
    [PCP_NPI]                VARCHAR (10)  NULL,
    [PCP_PROV_TYPE_ID]       VARCHAR (20)  NULL,
    [PCP_PROV_TYPE]          VARCHAR (50)  NULL,
    [PCP_INDICATOR]          VARCHAR (20)  NULL,
    [CMG]                    VARCHAR (20)  NULL,
    [PCP_PHONE]              VARCHAR (25)  NULL,
    [PCP_FAX]                VARCHAR (25)  NULL,
    [PCP_ADDRESS]            VARCHAR (100) NULL,
    [PCP_ADDRESS2]           VARCHAR (100) NULL,
    [PCP_CITY]               VARCHAR (40)  NULL,
    [PCP_STATE]              VARCHAR (20)  NULL,
    [PCP_ZIP]                VARCHAR (15)  NULL,
    [PCP_COUNTY]             VARCHAR (50)  NULL,
    [PCP_EFFECTIVE_DATE]     DATE          NULL,
    [PCP_TERM_DATE]          DATE          NULL,
    [PCP_PRACTICE_TIN]       VARCHAR (15)  NULL,
    [PCP_GROUP_ID]           VARCHAR (50)  NULL,
    [PCP_PRACTICE_NAME]      VARCHAR (100) NULL,
    [IND_PRACT_ID]           VARCHAR (50)  NULL,
    [IND_PRACT_NAME]         VARCHAR (100) NULL,
    [RECERT_DATE]            DATE          NULL,
    [ETHNICITY]              VARCHAR (10)  NULL,
    [ETHNICITY_DESC]         VARCHAR (50)  NULL,
    [AUTO_ASSIGN]            VARCHAR (50)  NULL,
    [ASAP_ID]                VARCHAR (50)  NULL,
    [FEW_ID]                 VARCHAR (50)  NULL,
    [LST_HRA_DATE]           DATE          NULL,
    [NXT_HRA_DATE]           DATE          NULL,
    [HRA_ID]                 VARCHAR (50)  NULL,
    [MEMBER_EMail]           VARCHAR (125) NULL,
    [PCP_Specialty_Code]     VARCHAR (50)  NULL,
    [PCP_Specialty]          VARCHAR (255) NULL,
    [SourceFileName]         VARCHAR (100) NOT NULL,
    [LoadType]               CHAR (2)      NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [DataDate]               DATE          NOT NULL,
    [CreateDate]             DATETIME2 (7) NOT NULL,
    [CreateBy]               VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]        DATETIME2 (7) NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  NOT NULL,
    [NewMbrProgramRowStatus] TINYINT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_MbrUhcNewMembers] PRIMARY KEY CLUSTERED ([MbrUhcNewMembersKey] ASC)
);


GO

CREATE TRIGGER adi.AU_MbrUhcNewMembers
ON adi.MbrUhcNewMembers
AFTER UPDATE 
AS
   UPDATE adi.MbrUhcNewMembers
   SET [LastUpdatedDate] = SYSDATETIME()
    , [LastUpdatedBy] = SYSTEM_USER
   FROM Inserted i
   WHERE adi.MbrUhcNewMembers.MbrUhcNewMembersKey= i.MbrUhcNewMembersKey;
