CREATE TABLE [adi].[MPulseDailyERCensus] (
    [MPulseDailyERCensusKey]      INT           IDENTITY (1, 1) NOT NULL,
    [LoadDate]                    DATE          NOT NULL,
    [DataDate]                    DATE          NOT NULL,
    [SrcFileName]                 VARCHAR (100) NOT NULL,
    [CreatedDate]                 DATE          CONSTRAINT [DF_adiMPulseDailyERCensus_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                   VARCHAR (50)  CONSTRAINT [DF_adiMPulseDailyERCensus_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]             DATE          CONSTRAINT [DF_adiMPulseDailyERCensus_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]               VARCHAR (50)  CONSTRAINT [DF_adiMPulseDailyERCensus_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [PcpID]                       VARCHAR (20)  NULL,
    [PcpFirstName]                VARCHAR (50)  NULL,
    [PcpLastName]                 VARCHAR (50)  NULL,
    [PatientFirstName]            VARCHAR (50)  NULL,
    [PatientLastName]             VARCHAR (50)  NULL,
    [PatientId]                   VARCHAR (20)  NULL,
    [PLAN_DESC]                   VARCHAR (100) NULL,
    [PatientCardID]               VARCHAR (20)  NULL,
    [MemberHealthPlanNumber]      VARCHAR (20)  NULL,
    [PatientBirthDate]            DATE          NULL,
    [PatientGender]               VARCHAR (50)  NULL,
    [PrimaryLanguage]             VARCHAR (50)  NULL,
    [Address]                     VARCHAR (20)  NULL,
    [City]                        VARCHAR (50)  NULL,
    [State]                       VARCHAR (10)  NULL,
    [Zip]                         VARCHAR (10)  NULL,
    [ContactPhoneNumber]          VARCHAR (20)  NULL,
    [AlternativePhoneNumber]      VARCHAR (20)  NULL,
    [LOB]                         VARCHAR (20)  NULL,
    [ServiceDate]                 DATE          NULL,
    [AdmitTime]                   DATE          NULL,
    [DischargeTime]               DATE          NULL,
    [ServiceDateReported]         DATE          NULL,
    [DayOfWeek]                   DATE          NULL,
    [ReOccuranceWithin30Days]     VARCHAR (100) NULL,
    [AvoidableERVisit]            VARCHAR (100) NULL,
    [LastIpVisitDate]             DATE          NULL,
    [PrimaryDiagnosisCode]        VARCHAR (50)  NULL,
    [PrimaryDiagnosisDescription] VARCHAR (50)  NULL,
    [AttendingPhysicianFirstName] VARCHAR (20)  NULL,
    [AttendingPhysicianLastName]  VARCHAR (20)  NULL,
    [FacilityName]                VARCHAR (20)  NULL,
    [FacilityState]               VARCHAR (20)  NULL,
    [PcpNpi]                      VARCHAR (20)  NULL,
    [TextSent]                    VARCHAR (20)  NULL,
    [Status]                      CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([MPulseDailyERCensusKey] ASC)
);

