CREATE TABLE [adi].[MPulseDailyIPCensus] (
    [MPulseDailyIPCensusKey]   INT           IDENTITY (1, 1) NOT NULL,
    [LoadDate]                 DATE          NOT NULL,
    [DataDate]                 DATE          NOT NULL,
    [SrcFileName]              VARCHAR (100) NOT NULL,
    [CreatedDate]              DATE          CONSTRAINT [DF_adiMPulseDailyIPCensus_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                VARCHAR (50)  CONSTRAINT [DF_adiMPulseDailyIPCensus_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]          DATE          CONSTRAINT [DF_adiMPulseDailyIPCensus_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]            VARCHAR (50)  CONSTRAINT [DF_adiMPulseDailyIPCensus_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ENTITY]                   VARCHAR (10)  NULL,
    [SITE]                     VARCHAR (20)  NULL,
    [UID_STATE]                VARCHAR (50)  NULL,
    [PRAC_NAME]                NUMERIC (15)  NULL,
    [UID_PROVIDER]             VARCHAR (15)  NULL,
    [TREATMENT_TYPE]           VARCHAR (10)  NULL,
    [MEMEBR_ID]                VARCHAR (10)  NULL,
    [MEMER_FIRST_NAME]         VARCHAR (20)  NULL,
    [MEMBER_LAST_NAME]         VARCHAR (20)  NULL,
    [MEMBER_DOB]               DATE          NULL,
    [CASE_ID]                  DATE          NULL,
    [CASE_TYPE]                VARCHAR (15)  NULL,
    [ADMIT_NOTIFICATION_DATE]  VARCHAR (15)  NULL,
    [ADIMSSION_DATE]           DATE          NULL,
    [DISCHARGE_DATE]           DATE          NULL,
    [DISCHARGE_DISPOSITION]    VARCHAR (20)  NULL,
    [FOLLOW_UP_VISIT_DUE_DATE] DATE          NULL,
    [SCHEDULED_VISIT_DATE]     DATE          NULL,
    [PRIMARY_DIAGNOSIS]        VARCHAR (10)  NULL,
    [ADMIT_HOSPITAL]           VARCHAR (10)  NULL,
    [CLIENT_ID]                VARCHAR (10)  NULL,
    [PhoneNumber]              VARCHAR (10)  NULL,
    [PhoneType]                VARCHAR (10)  NULL,
    [BenefitPlan]              VARCHAR (20)  NULL,
    [Status]                   CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([MPulseDailyIPCensusKey] ASC)
);

