CREATE TABLE [adi].[siuSchedule] (
    [siuScheduleKey]                INT           NOT NULL,
    [SrcFileName]                   VARCHAR (100) NOT NULL,
    [DataDate]                      DATE          NOT NULL,
    [CreatedDate]                   DATETIME      CONSTRAINT [DF_siuSchedule_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                     VARCHAR (50)  CONSTRAINT [DF_siuSchedule_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]               DATETIME      CONSTRAINT [DF_siuSchedule_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                 VARCHAR (50)  CONSTRAINT [DF_siuSchedule_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [AppointmentURN]                INT           NULL,
    [AceID]                         NUMERIC (15)  NOT NULL,
    [AceClientMemberID]             VARCHAR (30)  NOT NULL,
    [EmrID]                         VARCHAR (50)  NOT NULL,
    [AppointmentType]               VARCHAR (100) NOT NULL,
    [AppointmentReason]             VARCHAR (500) NULL,
    [AppointmentDate]               DATETIME      NULL,
    [AppointmentNotes]              VARCHAR (500) NULL,
    [AppointmentStatus]             VARCHAR (50)  NULL,
    [ProviderNpi]                   VARCHAR (10)  NOT NULL,
    [AppointmentDiagnosis]          VARCHAR (25)  NULL,
    [PracticeTIN]                   VARCHAR (10)  NOT NULL,
    [MshSendingApplication]         VARCHAR (50)  NULL,
    [MshFacilityID]                 VARCHAR (10)  NULL,
    [MshinterfaceName]              VARCHAR (10)  NULL,
    [MshType]                       VARCHAR (50)  NULL,
    [MshID]                         VARCHAR (50)  NULL,
    [MshProcessingID]               VARCHAR (1)   NULL,
    [MshHL7Ver]                     VARCHAR (10)  NULL,
    [AppointmentID]                 INT           NOT NULL,
    [AppointmentName]               VARCHAR (100) NULL,
    [AppointmentTimeStamp]          VARCHAR (20)  NULL,
    [AppointmentContact]            VARCHAR (50)  NULL,
    [PatientID1]                    VARCHAR (20)  NULL,
    [PatientID2]                    VARCHAR (20)  NULL,
    [PatientID3]                    VARCHAR (20)  NULL,
    [PatientLastName]               VARCHAR (50)  NULL,
    [PatientFirstName]              VARCHAR (50)  NULL,
    [PatientDOB]                    VARCHAR (10)  NULL,
    [PatientGender]                 VARCHAR (10)  NULL,
    [PatientAddress]                VARCHAR (50)  NULL,
    [PatientContact1]               VARCHAR (100) NULL,
    [PatientContact2]               VARCHAR (100) NULL,
    [PatientPrimLang]               VARCHAR (50)  NULL,
    [AppointmentLocation]           VARCHAR (50)  NULL,
    [AppointmentPrimaryNPI]         VARCHAR (10)  NULL,
    [AppointmentPrimaryLastName]    VARCHAR (50)  NULL,
    [AppointmentPrimaryFirstName]   VARCHAR (50)  NULL,
    [AppointmentReferringNPI]       VARCHAR (10)  NULL,
    [AppointmentReferringLastName]  VARCHAR (50)  NULL,
    [AppointmentReferringFirstName] VARCHAR (50)  NULL,
    [AppointmentPCPNPI]             VARCHAR (10)  NULL,
    [AppointmentPCPLastName]        VARCHAR (50)  NULL,
    [AppointmentPCPFirstName]       VARCHAR (50)  NULL,
    [AppointmentUsualNPI]           VARCHAR (10)  NULL,
    [AppointmentUsualLastName]      VARCHAR (50)  NULL,
    [AppointmentUsualFirstName]     VARCHAR (50)  NULL,
    [AppointmentPVID]               INT           NULL,
    PRIMARY KEY CLUSTERED ([siuScheduleKey] ASC)
);

