CREATE TABLE [adi].[tempmPulse_IP_Texting] (
    [tempmPulse_IP_TextingKey] INT           IDENTITY (1, 1) NOT NULL,
    [ENTITY]                   VARCHAR (20)  NULL,
    [SITE]                     VARCHAR (20)  NULL,
    [UID_STATE]                VARCHAR (20)  NULL,
    [PRAC_NAME]                VARCHAR (50)  NULL,
    [UID_PROVIDER]             VARCHAR (25)  NULL,
    [TREATMENT_TYPE]           VARCHAR (20)  NULL,
    [MEMEBR_ID]                VARCHAR (20)  NULL,
    [TEXT]                     VARCHAR (20)  NULL,
    [MEMER_FIRST_NAME]         VARCHAR (50)  NULL,
    [MEMBER_LAST_NAME]         VARCHAR (50)  NULL,
    [MEMBER_DOB]               DATE          NULL,
    [CASE_ID]                  VARCHAR (20)  NULL,
    [CASE_TYPE]                VARCHAR (20)  NULL,
    [ADMIT_NOTIFICATION_DATE]  DATE          NULL,
    [ADIMSSION_DATE]           DATE          NULL,
    [DISCHARGE_DATE]           DATE          NULL,
    [DISCHARGE_DISPOSITION]    VARCHAR (100) NULL,
    [FOLLOW_UP_VISIT_DUE_DATE] DATE          NULL,
    [SCHEDULED_VISIT_DATE]     DATE          NULL,
    [PRIMARY_DIAGNOSIS]        VARCHAR (50)  NULL,
    [ADMIT_HOSPITAL]           VARCHAR (50)  NULL,
    [CLIENT_ID]                VARCHAR (20)  NULL,
    [PhoneNumber]              VARCHAR (20)  NULL,
    [PhoneType]                VARCHAR (20)  NULL,
    [BenefitPlan]              VARCHAR (50)  NULL,
    [LoadDate]                 DATE          NOT NULL,
    [DataDate]                 DATE          NOT NULL,
    [OrignalSrcFileName]       VARCHAR (100) NOT NULL,
    [SrcFileName]              VARCHAR (100) NOT NULL,
    [CreatedDate]              DATETIME2 (7) CONSTRAINT [DF_tempmPulse_IP_Texting_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                VARCHAR (50)  CONSTRAINT [DF_tempmPulse_IP_Texting_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]          DATETIME2 (7) CONSTRAINT [DF_tempmPulse_IP_Texting_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]            VARCHAR (50)  CONSTRAINT [DF_tempmPulse_IP_Texting_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    PRIMARY KEY CLUSTERED ([tempmPulse_IP_TextingKey] ASC)
);

