CREATE TABLE [adi].[tempmPulse_ER_Texting] (
    [tempmPulse_ER_TextingKey]    INT           IDENTITY (1, 1) NOT NULL,
    [PcpID]                       VARCHAR (20)  NULL,
    [PcpFirstName]                VARCHAR (50)  NULL,
    [PcpLastName]                 VARCHAR (50)  NULL,
    [PatientFirstName]            VARCHAR (50)  NULL,
    [PatientLastName]             VARCHAR (50)  NULL,
    [PatientId]                   VARCHAR (50)  NULL,
    [PLAN_DESC]                   VARCHAR (100) NULL,
    [PatientCardID]               VARCHAR (50)  NULL,
    [Text]                        VARCHAR (10)  NULL,
    [MemberHealthPlanNumber]      VARCHAR (50)  NULL,
    [PatientBirthDate]            DATE          NULL,
    [PatientGender]               VARCHAR (10)  NULL,
    [PrimaryLanguage]             VARCHAR (10)  NULL,
    [Address]                     VARCHAR (50)  NULL,
    [City]                        VARCHAR (50)  NULL,
    [State]                       VARCHAR (20)  NULL,
    [Zip]                         VARCHAR (10)  NULL,
    [ContactPhoneNumber]          VARCHAR (15)  NULL,
    [AlternativePhoneNumber]      VARCHAR (15)  NULL,
    [LOB]                         VARCHAR (20)  NULL,
    [ServiceDate]                 DATE          NULL,
    [AdmitTime]                   VARCHAR (20)  NULL,
    [DischargeTime]               VARCHAR (20)  NULL,
    [ServiceDateReported]         DATE          NULL,
    [DayOfWeek]                   VARCHAR (50)  NULL,
    [ReOccuranceWithin30Days]     VARCHAR (50)  NULL,
    [AvoidableERVisit]            VARCHAR (50)  NULL,
    [LastIpVisitDate]             VARCHAR (10)  NULL,
    [PrimaryDiagnosisCode]        VARCHAR (10)  NULL,
    [PrimaryDiagnosisDescription] VARCHAR (50)  NULL,
    [AttendingPhysicianFirstName] VARCHAR (50)  NULL,
    [AttendingPhysicianLastName]  VARCHAR (50)  NULL,
    [FacilityName]                VARCHAR (50)  NULL,
    [FacilityState]               VARCHAR (50)  NULL,
    [PcpNpi]                      VARCHAR (50)  NULL,
    [TextSent]                    VARCHAR (10)  NULL,
    [LoadDate]                    DATE          NOT NULL,
    [DataDate]                    DATE          NOT NULL,
    [OrignalSrcFileName]          VARCHAR (100) NOT NULL,
    [SrcFileName]                 VARCHAR (100) NOT NULL,
    [CreatedDate]                 DATETIME2 (7) CONSTRAINT [DF_tempmPulse_ER_Texting_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                   VARCHAR (50)  CONSTRAINT [DF_tempmPulse_ER_Texting_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]             DATETIME2 (7) CONSTRAINT [DF_tempmPulse_ER_Texting_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]               VARCHAR (50)  CONSTRAINT [DF_tempmPulse_ER_Texting_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [Status]                      VARCHAR (1)   NULL,
    PRIMARY KEY CLUSTERED ([tempmPulse_ER_TextingKey] ASC)
);

