CREATE TABLE [adi].[UHC_EfficiencybyPCP] (
    [Membermonths]                 INT            NULL,
    [ProspectiveRisk]              DECIMAL (5, 2) NULL,
    [Iptnt]                        MONEY          NULL,
    [Optnt]                        MONEY          NULL,
    [Physn]                        MONEY          NULL,
    [Pharm]                        MONEY          NULL,
    [Total]                        MONEY          NULL,
    [ERVisitsPer_1000]             DECIMAL (5, 2) NULL,
    [AcuteAdmitsPer_1000]          DECIMAL (5, 2) NULL,
    [AcuteDaysPer_1000]            DECIMAL (5, 2) NULL,
    [ALOS]                         DECIMAL (3, 1) NULL,
    [Pct_Spec_VstsNonpar]          VARCHAR (10)   NULL,
    [RXGenericCompliance]          VARCHAR (10)   NULL,
    [Pct_Phys_VisitsSpecialists]   VARCHAR (10)   NULL,
    [Pct_Acute_AdmitsACOFacility]  VARCHAR (10)   NULL,
    [Pct_Spec_VisitsACOSpecialist] VARCHAR (10)   NULL,
    [SrcFileName]                  VARCHAR (100)  NULL,
    [OriginalFileName]             VARCHAR (100)  NULL,
    [LoadDate]                     DATE           NULL,
    [DataDate]                     DATE           NULL,
    [CreatedDate]                  DATETIME       CONSTRAINT [DF_UHC_EfficiencybyPCP_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]                    VARCHAR (50)   CONSTRAINT [DF_UHC_EfficiencybyPCP_CreatedBY] DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]              DATETIME       CONSTRAINT [DF_UHC_EfficiencybyPCP_LastUpdatedDate] DEFAULT (getdate()) NULL,
    [LastUpdatedBy]                VARCHAR (50)   CONSTRAINT [DF_UHC_EfficiencybyPCP_LastUpdatedBY] DEFAULT (suser_sname()) NULL,
    [LoadStatus]                   TINYINT        CONSTRAINT [DF_UHC_EfficiencybyPCP] DEFAULT ((0)) NULL,
    [ADIKey]                       BIGINT         IDENTITY (1, 1) NOT NULL
);

