CREATE TABLE [adi].[UHC_PvdrPanel_CareOpps] (
    [ACCOUNT_ID]                    VARCHAR (50)  NULL,
    [GROUP_NAME]                    VARCHAR (50)  NULL,
    [PRACTICE_NAME]                 VARCHAR (50)  NULL,
    [Member_Id]                     VARCHAR (50)  NULL,
    [MEDICAID_NO]                   VARCHAR (50)  NULL,
    [Lastname]                      VARCHAR (50)  NULL,
    [Firstname]                     VARCHAR (50)  NULL,
    [MEMB_GENDER]                   VARCHAR (10)  NULL,
    [DOB]                           VARCHAR (50)  NULL,
    [Telephone]                     VARCHAR (50)  NULL,
    [Measure_Id]                    VARCHAR (50)  NULL,
    [Measure_Description]           VARCHAR (200) NULL,
    [Submeasure_Id]                 VARCHAR (50)  NULL,
    [Submeasure_Description]        VARCHAR (50)  NULL,
    [Compliance_Date]               VARCHAR (50)  NULL,
    [COMPLIANCE]                    VARCHAR (50)  NULL,
    [MBR_HIST_LOB]                  VARCHAR (50)  NULL,
    [MBR_HIST_LOB_DESC]             VARCHAR (50)  NULL,
    [PLAN_CODE]                     VARCHAR (50)  NULL,
    [PLAN_DESC]                     VARCHAR (50)  NULL,
    [Assigned_Provider_TIN_Name]    VARCHAR (50)  NULL,
    [Assigned_Provider_Medicaid_Id] VARCHAR (50)  NULL,
    [Assigned_Provider_Lastname]    VARCHAR (50)  NULL,
    [Assigned_Provider_Firstname]   VARCHAR (50)  NULL,
    [Assigned_Provider_Address1]    VARCHAR (50)  NULL,
    [Assigned_Provider_Address2]    VARCHAR (50)  NULL,
    [Assigned_Provider_City]        VARCHAR (50)  NULL,
    [Assigned_Provider_County]      VARCHAR (50)  NULL,
    [Assigned_Provider_State]       VARCHAR (50)  NULL,
    [Assigned_Provider_Zipcode]     VARCHAR (50)  NULL,
    [Assigned_Provider_Telephone]   VARCHAR (50)  NULL,
    [Assigned_Provider_Last_Visit]  VARCHAR (50)  NULL,
    [Assigned_Provider_TIN]         VARCHAR (50)  NULL,
    [Assigned_Provider_NPI]         VARCHAR (50)  NULL,
    [Assigned_Provider_MPIN]        VARCHAR (50)  NULL,
    [Assigned_Provider_Id]          VARCHAR (50)  NULL,
    [Extract_Timestamp]             VARCHAR (50)  NULL,
    [SMART_Load_Timestamp]          VARCHAR (50)  NULL,
    [ReviewSet]                     VARCHAR (50)  NULL,
    [REPORTDATE]                    VARCHAR (50)  NULL,
    [MeasureID]                     VARCHAR (50)  NULL,
    [SubMeasure]                    VARCHAR (50)  NULL,
    [SrcFileName]                   VARCHAR (100) NULL,
    [OriginalFileName]              VARCHAR (100) NULL,
    [LoadDate]                      DATE          NULL,
    [DataDate]                      DATE          NULL,
    [CreatedDate]                   DATETIME      NULL,
    [CreatedBy]                     VARCHAR (50)  NULL,
    [LastUpdatedDate]               DATETIME      NULL,
    [LastUpdatedBy]                 VARCHAR (50)  NULL,
    [CopLoadStatus]                 TINYINT       CONSTRAINT [DF_UHC_PvdrPanel] DEFAULT ((0)) NULL,
    [ADIKey]                        BIGINT        IDENTITY (1, 1) NOT NULL
);

