CREATE TABLE [adi].[UHCContinuumHighRisk] (
    [ContinuumHighRiskKey]           INT            IDENTITY (1, 1) NOT NULL,
    [HotspotFlag]                    CHAR (1)       NULL,
    [PSUFlag]                        CHAR (1)       NULL,
    [NewMember]                      CHAR (1)       NULL,
    [UHC_SUBSCRIBER_ID]              NUMERIC (15)   NULL,
    [MEDICAID_ID]                    NUMERIC (15)   NULL,
    [MEMBER_LAST_NAME]               VARCHAR (50)   NULL,
    [MEMBER_FIRST_NAME]              VARCHAR (50)   NULL,
    [DATE_OF_BIRTH]                  DATE           NULL,
    [IPRO_ADMIT_RISK_SCORE]          NUMERIC (4, 2) NULL,
    [UHC_UNIQUE_SYSTEM_ID]           NUMERIC (15)   NULL,
    [MEMBER_ADDRESS]                 VARCHAR (50)   NULL,
    [MEMBER_CITY]                    VARCHAR (50)   NULL,
    [MEMBER_STATE]                   VARCHAR (50)   NULL,
    [MEMBER_COUNTY]                  VARCHAR (50)   NULL,
    [MEMBER_ZIP]                     VARCHAR (12)   NULL,
    [MEMBER_PHONE]                   VARCHAR (20)   NULL,
    [LINE_OF_BUSINESS]               VARCHAR (20)   NULL,
    [PLAN_CODE]                      VARCHAR (20)   NULL,
    [PLAN_DESC]                      VARCHAR (500)  NULL,
    [REGION_CODE]                    VARCHAR (20)   NULL,
    [REGION_DESC]                    VARCHAR (500)  NULL,
    [PCP_NAME]                       VARCHAR (20)   NULL,
    [PCP_ADDRESS]                    VARCHAR (100)  NULL,
    [PCP_CITY]                       VARCHAR (50)   NULL,
    [PCP_STATE]                      VARCHAR (20)   NULL,
    [PCP_COUNTY]                     VARCHAR (50)   NULL,
    [PCP_ZIP]                        VARCHAR (12)   NULL,
    [PCP_PRACTICE_TIN]               VARCHAR (20)   NULL,
    [PCP_PRACTICE_NAME]              VARCHAR (50)   NULL,
    [PRIMARY_RISK_FACTOR]            VARCHAR (20)   NULL,
    [TOTAL_COSTS_LAST_12_MOS]        MONEY          NULL,
    [COUNT_OPEN_CARE_OPPS]           VARCHAR (5)    NULL,
    [INP_COSTS_LAST_12_MOS]          MONEY          NULL,
    [ER_COSTS_LAST_12_MOS]           MONEY          NULL,
    [OUTP_COSTS_LAST_12_MOS]         MONEY          NULL,
    [PHARMACY_COSTS_LAST_12_MOS]     MONEY          NULL,
    [PRIMARY_CARE_COSTS_LAST_12_MOS] MONEY          NULL,
    [BEHAVIORAL_COSTS_LAST_12_MOS]   MONEY          NULL,
    [OTHER_OFFICE_COSTS_LAST_12_MOS] MONEY          NULL,
    [INP_ADMITS_LAST_12_MOS]         VARCHAR (5)    NULL,
    [LAST_INP_DISCHARGE]             DATE           NULL,
    [POST_DISCHARGE_FUP_VISIT]       DATE           NULL,
    [INP_FUP_WITHIN_7_DAYS]          VARCHAR (5)    NULL,
    [ER_VISITS_LAST_12_MOS]          INT            NULL,
    [LAST_ER_VISIT]                  DATE           NULL,
    [POST_ER_FUP_VISIT]              DATE           NULL,
    [ER_FUP_WITHIN_7_DAYS]           VARCHAR (5)    NULL,
    [LAST_PCP_VISIT]                 DATE           NULL,
    [LAST_PCP_PRACTICE_SEEN]         VARCHAR (20)   NULL,
    [LAST_BH_VISIT]                  DATE           NULL,
    [LAST_BH_PRACTICE_SEEN]          VARCHAR (20)   NULL,
    [MEMBER_MONTH_COUNT]             SMALLINT       NULL,
    [FILE_GENERATION_DATE]           DATE           NULL,
    [REPORT_MONTH]                   VARCHAR (6)    NULL,
    [LoadDate]                       DATE           NOT NULL,
    [DataDate]                       DATE           NOT NULL,
    [SrcFileName]                    VARCHAR (100)  NOT NULL,
    [CreatedDate]                    DATETIME       CONSTRAINT [DF_UHCContinuumHighRiskCreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                      VARCHAR (50)   CONSTRAINT [DF_UHCContinuumHighRiskCreatedBY] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                DATETIME       CONSTRAINT [DF_UHCContinuumHighRiskLastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                  VARCHAR (50)   CONSTRAINT [DF_UHCContinuumHighRiskLastUpdatedBY] DEFAULT (suser_sname()) NOT NULL,
    PRIMARY KEY CLUSTERED ([ContinuumHighRiskKey] ASC)
);

