CREATE TABLE [adi].[UhcPharmacy] (
    [clmsUhcPharmacyKey]            INT            IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                   VARCHAR (100)  NOT NULL,
    [OriginalFileName]              VARCHAR (100)  NULL,
    [LoadDate]                      DATE           NOT NULL,
    [DataDate]                      DATE           NOT NULL,
    [CreatedDate]                   DATETIME       CONSTRAINT [DF_adiClmsUhcPharmacy_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                     VARCHAR (50)   CONSTRAINT [DF_adiClmsUhcPharmacy_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]               DATETIME       CONSTRAINT [DF_adiClmsUhcPharmacy_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                 VARCHAR (50)   CONSTRAINT [DF_adiClmsUhcPharmacy_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [MEMBER_LAST_NAME]              VARCHAR (50)   NULL,
    [MEMBER_FIRST_NAME]             VARCHAR (50)   NULL,
    [DATE_OF_BIRTH]                 DATE           NULL,
    [MEDICATION_NAME]               VARCHAR (50)   NULL,
    [DAYS_SUPPLY]                   INT            NULL,
    [PRESCRIBE_DATE]                DATE           NULL,
    [PRESCRIPTION_NUMBER]           NUMERIC (20)   NULL,
    [PRESCRIBING_PROVIDER]          VARCHAR (50)   NULL,
    [PRESCRIBING_PROVIDER_PRACTICE] VARCHAR (100)  NULL,
    [PRESCRIBING_PROVIDER_PHONE]    VARCHAR (20)   NULL,
    [FILL_DATE]                     DATE           NULL,
    [FILL_PHARMACY]                 VARCHAR (50)   NULL,
    [IPRO_ADMIT_RISK_SCORE]         DECIMAL (5, 2) NULL,
    [UHC_SUBSCRIBER_ID]             VARCHAR (50)   NULL,
    [UHC_UNIQUE_SYSTEM_ID]          VARCHAR (50)   NULL,
    [MEMBER_ADDRESS]                VARCHAR (100)  NULL,
    [MEMBER_CITY]                   VARCHAR (50)   NULL,
    [MEMBER_STATE]                  VARCHAR (20)   NULL,
    [MEMBER_COUNTY]                 VARCHAR (50)   NULL,
    [MEMBER_ZIP]                    VARCHAR (10)   NULL,
    [MEMBER_PHONE]                  VARCHAR (20)   NULL,
    [PCP_NAME]                      VARCHAR (50)   NULL,
    [PCP_ADDRESS]                   VARCHAR (100)  NULL,
    [PCP_CITY]                      VARCHAR (20)   NULL,
    [PCP_STATE]                     VARCHAR (20)   NULL,
    [PCP_COUNTY]                    VARCHAR (50)   NULL,
    [PCP_ZIP]                       VARCHAR (10)   NULL,
    [PCP_PRACTICE_TIN]              VARCHAR (20)   NULL,
    [PCP_PRACTICE_NAME]             VARCHAR (50)   NULL,
    [LINE_OF_BUSINESS_DESC]         VARCHAR (200)  NULL,
    [PLAN_CODE]                     VARCHAR (20)   NULL,
    [PLAN_DESC]                     VARCHAR (200)  NULL,
    [FILE_GENERATION_DATE]          DATE           NULL,
    [NDC_CODE]                      VARCHAR (50)   NULL,
    [LoadToAhsStatus]               TINYINT        DEFAULT ((0)) NOT NULL
);

