CREATE TABLE [adi].[UHCQualityGapReport] (
    [UHCQualityGapReportKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]            VARCHAR (100) NOT NULL,
    [OriginalFileName]       VARCHAR (100) NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [DataDate]               DATE          NOT NULL,
    [CreatedDate]            DATETIME      CONSTRAINT [DF_UHCQualityGapReport_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              VARCHAR (50)  CONSTRAINT [DF_UHCQualityGapReport_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]        DATETIME      CONSTRAINT [DF_UHCQualityGapReport_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  CONSTRAINT [DF_UHCQualityGapReport_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ProductSugroup]         VARCHAR (50)  NULL,
    [MemberId]               VARCHAR (50)  NULL,
    [MedicaidId]             VARCHAR (50)  NULL,
    [Lastname]               VARCHAR (50)  NULL,
    [Firstname]              VARCHAR (50)  NULL,
    [Gender]                 VARCHAR (10)  NULL,
    [DOB]                    DATE          NULL,
    [Telephone]              VARCHAR (50)  NULL,
    [MeasureId]              VARCHAR (50)  NULL,
    [MeasureDescription]     VARCHAR (50)  NULL,
    [SubmeasureId]           VARCHAR (50)  NULL,
    [SubmeasureDescription]  VARCHAR (500) NULL,
    [ComplianceDate]         DATE          NULL,
    [COMPLIANCE]             VARCHAR (50)  NULL,
    [LOB]                    VARCHAR (50)  NULL,
    [ProviderTINName]        VARCHAR (50)  NULL,
    [ProviderMedicaidId]     VARCHAR (50)  NULL,
    [ProviderLastname]       VARCHAR (50)  NULL,
    [ProviderFirstname]      VARCHAR (50)  NULL,
    [ProviderAddress1]       VARCHAR (50)  NULL,
    [ProviderAddress2]       VARCHAR (50)  NULL,
    [ProviderCity]           VARCHAR (50)  NULL,
    [ProviderCounty]         VARCHAR (50)  NULL,
    [ProviderState]          VARCHAR (50)  NULL,
    [ProviderZipcode]        VARCHAR (20)  NULL,
    [ProviderTelephone]      VARCHAR (50)  NULL,
    [ProviderLastVisit]      VARCHAR (50)  NULL,
    [ProviderTIN]            VARCHAR (20)  NULL,
    [ProviderNPI]            VARCHAR (50)  NULL,
    [ProviderMPIN]           VARCHAR (50)  NULL,
    [ProviderId]             VARCHAR (50)  NULL,
    [CopLoadStatus]          TINYINT       DEFAULT ((0)) NOT NULL,
    [ReviewSet]              VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([UHCQualityGapReportKey] ASC)
);

