


CREATE VIEW [abo].[vw_Exp_UHCClaimHeader]
AS 
SELECT 
      [HLKey]
	  ,[CreateDate]
      ,[CreateBy]
      ,[DwDate]
      ,[DwKey]
      ,[ClientKey]
      ,[ClaimRecordID]
      ,[ClaimTypeDSC]
      ,[PatientID]
      ,[ClaimID]
      ,[ClaimHeaderStatusCode]
      ,[AdjustmentSeqNumber]
      ,[ClaimHeaderPaidDate]
      ,[FacilityName_BillingProviderName]
      ,[ServicingProviderTIN]
      ,[BillingProviderNPI]
      ,[HServicingProviderNPI]
      ,[HServicingProviderFirstName]
      ,[HServicingProviderMiddle]
      ,[HServicingProviderLastName]
      ,[HServicingProviderAddress1]
      ,[HServicingProviderStreetAddress]
      ,[HServicingProviderCity]
      ,[HServicingProviderState]
      ,[HServicingProviderZip]
      ,[HServicingProviderPhoneNumber]
      ,[HServicingProviderTaxonomyCode]
      ,[PlaceTreatmentCodec]
      ,[ICDVersionCode]
      ,[HLPrimaryDiagnosisCode]
      ,[HLDiagnosisCode2]
      ,[HLDiagnosisCode3]
      ,[HLDiagnosisCode4]
      ,[HLDiagnosisCode5]
      ,[HLDiagnosisCode6]
      ,[HLDiagnosisCode7]
      ,[HLDiagnosisCode8]
      ,[HLDiagnosisCode9]
      ,[HLDiagnosisCode10]
      ,[HLDiagnosisCode11]
      ,[HLDiagnosisCode12]
      ,[ProcedureCode1]
      ,[ProcedureCode2]
      ,[ProcedureCode3]
      ,[ProcedureCode4]
      ,[ProcedureCode5]
      ,[HLBilledAmount]
      ,[HLPaidAmount]
      ,[ServicingProviderSpecialtyCode]
      ,[ServicingProviderSpecialtyDescrip]
      ,[Inpatient_OutpatientCode]
      ,[ServiceFromDate]
      ,[ServiceToDate]
      ,[TypeBillCode]
      ,[FrequencyCode]
      ,[DischargeStatusCode]
      ,[DRGCode]
  FROM [ACECAREDW_TEST].[adi].[vw_Exp_UHCClaimHeader]

