CREATE TABLE [amd].[AceMbrLoadLog] (
    [AceMbrLoadLogKey]     INT           IDENTITY (1, 1) NOT NULL,
    [ClientKey]            INT           NOT NULL,
    [LoadDate]             DATE          NULL,
    [LoadType]             CHAR (1)      NULL,
    [countInsertLoadHist]  INT           DEFAULT ((0)) NULL,
    [countInsertMember]    INT           DEFAULT ((0)) NULL,
    [countInsertDemo]      INT           DEFAULT ((0)) NULL,
    [countUpdateDemo]      INT           DEFAULT ((0)) NULL,
    [countInsertPhone]     INT           DEFAULT ((0)) NULL,
    [countUpdatePhone]     INT           DEFAULT ((0)) NULL,
    [countInsertAddress]   INT           NULL,
    [countUpdateAddress]   INT           NULL,
    [countInsertPcp]       INT           DEFAULT ((0)) NULL,
    [countUpdatePcp]       INT           DEFAULT ((0)) NULL,
    [countInsertPlan]      INT           DEFAULT ((0)) NULL,
    [countUpdatePlan]      INT           DEFAULT ((0)) NULL,
    [countTermedPlanCnt]   INT           DEFAULT ((0)) NULL,
    [CountInsertCsPlan]    INT           DEFAULT ((0)) NULL,
    [countUpdateCsPlan]    INT           DEFAULT ((0)) NULL,
    [countTermedCsPlanCnt] INT           DEFAULT ((0)) NULL,
    [CreatedDate]          DATETIME2 (7) CONSTRAINT [DF_amdMbrLoadLog_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            VARCHAR (50)  CONSTRAINT [DF_amdMbrLoadLog_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]      DATETIME2 (7) CONSTRAINT [DF_amdMbrLoadLog_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]        VARCHAR (50)  CONSTRAINT [DF_amdMbrLoadLog_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [CountTermedPcp]       INT           NULL,
    PRIMARY KEY CLUSTERED ([AceMbrLoadLogKey] ASC)
);

