CREATE TABLE [lst].[lstPcp] (
    [lstPcpKey]         INT           IDENTITY (1, 1) NOT NULL,
    [ClientKey]         INT           NOT NULL,
    [lstLoadHistoryKey] INT           NOT NULL,
    [EffectiveDate]     DATE          NOT NULL,
    [ExpriationDate]    DATE          CONSTRAINT [DF_lstPcpExpirationDate] DEFAULT ('12/31/9999') NOT NULL,
    [FirstName]         VARCHAR (60)  NOT NULL,
    [LastName]          VARCHAR (60)  NOT NULL,
    [NPI]               VARCHAR (10)  NOT NULL,
    [ProvType]          INT           NOT NULL,
    [Phone]             VARCHAR (30)  NULL,
    [Fax]               VARCHAR (30)  NULL,
    [Address1]          VARCHAR (100) NULL,
    [Address2]          VARCHAR (100) NULL,
    [City]              VARCHAR (65)  NULL,
    [State]             VARCHAR (25)  NULL,
    [ZipCode]           VARCHAR (20)  NULL,
    [County]            VARCHAR (65)  NULL,
    [PracticeTIN]       VARCHAR (11)  NULL,
    [GroupID]           VARCHAR (50)  NULL,
    [PracticeName]      VARCHAR (100) NULL,
    [IndPracticeID]     VARCHAR (50)  NULL,
    [IndPracticeName]   VARCHAR (100) NULL,
    [MPIN]              VARCHAR (20)  NULL,
    [ClientProviderID]  VARCHAR (20)  NULL,
    [PcpDoNotCall]      TINYINT       CONSTRAINT [DF_lstPcp_PcpDoNotCall] DEFAULT ((0)) NOT NULL,
    [PcpDoNotText]      TINYINT       CONSTRAINT [DF_lstPcp_PcpDoNotText] DEFAULT ((0)) NOT NULL,
    [CreatedDate]       DATETIME2 (7) CONSTRAINT [DF_MbrDemographic_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]         VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]   DATETIME2 (7) CONSTRAINT [DF_MbrDemographic_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]     VARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([lstPcpKey] ASC)
);

